/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamics_deriv_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[24] = {6, 3, 0, 6, 12, 18, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

/* dynamics_deriv:(i0[6],i1[3])->(o0[6x6],o1[6x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a1=9.8100000000000005e+00;
  a2=arg[0]? arg[0][1] : 0;
  a3=cos(a2);
  a4=arg[0]? arg[0][2] : 0;
  a5=cos(a4);
  a6=(a3*a5);
  a7=sin(a2);
  a8=sin(a4);
  a9=(a7*a8);
  a6=(a6-a9);
  a9=arg[0]? arg[0][0] : 0;
  a10=(a9-a7);
  a11=(a3*a8);
  a12=(a7*a5);
  a11=(a11+a12);
  a11=(a10-a11);
  a12=(a11-a10);
  a13=casadi_sq(a11);
  a14=(a3+a6);
  a15=casadi_sq(a14);
  a13=(a13+a15);
  a15=(a14*a3);
  a16=(a11*a10);
  a15=(a15+a16);
  a15=(a13-a15);
  a16=(a3*a6);
  a17=(a10*a12);
  a16=(a16+a17);
  a16=(a15-a16);
  a17=(a12/a16);
  a18=(a17/a16);
  a19=(a11+a11);
  a20=(a10+a11);
  a20=(a19-a20);
  a21=(a20-a12);
  a22=(a18*a21);
  a23=(a6*a22);
  a24=(a6/a16);
  a25=(a24*a15);
  a25=(a25-a14);
  a25=(a25-a3);
  a26=(a24*a12);
  a27=(a26*a9);
  a25=(a25-a27);
  a27=1.;
  a28=(a17*a20);
  a29=(a15*a22);
  a28=(a28-a29);
  a28=(a27-a28);
  a28=(a27+a28);
  a29=(a12*a22);
  a30=(a9*a29);
  a31=(a17*a12);
  a31=(a27-a31);
  a32=(a27+a31);
  a30=(a30+a32);
  a28=(a28-a30);
  a30=(a9-a7);
  a33=casadi_sq(a30);
  a34=casadi_sq(a3);
  a33=(a33+a34);
  a34=(a15/a16);
  a35=(a34*a15);
  a13=(a13-a35);
  a33=(a33+a13);
  a13=(a34*a12);
  a13=(a11-a13);
  a35=(a30+a13);
  a36=(a35*a9);
  a33=(a33-a36);
  a36=(a17*a15);
  a36=(a11-a36);
  a36=(a30+a36);
  a32=(a32*a9);
  a36=(a36-a32);
  a32=(a9*a36);
  a33=(a33-a32);
  a32=(a28/a33);
  a37=(a36/a33);
  a38=(a37/a33);
  a39=(a30+a30);
  a40=(a20/a16);
  a41=(a34/a16);
  a42=(a41*a21);
  a40=(a40-a42);
  a42=(a15*a40);
  a43=(a34*a20);
  a42=(a42+a43);
  a42=(a19-a42);
  a42=(a39+a42);
  a43=(a12*a40);
  a43=(a27-a43);
  a44=(a27+a43);
  a44=(a9*a44);
  a44=(a44+a35);
  a42=(a42-a44);
  a44=(a9*a28);
  a44=(a36+a44);
  a42=(a42-a44);
  a44=(a38*a42);
  a32=(a32-a44);
  a44=(a25*a32);
  a20=(a24*a20);
  a35=(a24/a16);
  a45=(a35*a21);
  a46=(a15*a45);
  a20=(a20-a46);
  a46=(a12*a45);
  a47=(a9*a46);
  a47=(a26-a47);
  a20=(a20-a47);
  a47=(a37*a20);
  a44=(a44+a47);
  a44=(a23+a44);
  a47=(a24*a6);
  a47=(a27-a47);
  a48=(a27+a47);
  a49=(a25/a33);
  a50=(a49*a25);
  a48=(a48-a50);
  a48=(a27+a48);
  a44=(a44/a48);
  a50=(a17*a6);
  a51=(a37*a25);
  a51=(a50-a51);
  a51=(a51/a48);
  a52=(a51/a48);
  a53=(a6*a45);
  a54=(a20/a33);
  a55=(a49/a33);
  a56=(a55*a42);
  a54=(a54-a56);
  a56=(a25*a54);
  a20=(a49*a20);
  a56=(a56+a20);
  a56=(a53-a56);
  a20=(a52*a56);
  a44=(a44+a20);
  a44=(a1*a44);
  a20=arg[0]? arg[0][4] : 0;
  a57=arg[0]? arg[0][5] : 0;
  a58=(a10*a57);
  a59=(a9*a20);
  a58=(a58+a59);
  a60=(a20*a58);
  a61=(a57+a20);
  a62=(a59*a61);
  a60=(a60-a62);
  a53=(a60*a53);
  a62=(a57+a20);
  a63=(a20*a62);
  a64=(a61*a20);
  a63=(a63-a64);
  a64=(a47*a63);
  a53=(a53+a64);
  a64=(a3*a57);
  a65=arg[0]? arg[0][3] : 0;
  a66=(a64+a65);
  a67=(a20*a66);
  a68=(a65*a61);
  a67=(a67-a68);
  a68=(a67*a46);
  a53=(a53-a68);
  a68=arg[1]? arg[1][2] : 0;
  a69=(a11*a61);
  a70=(a69-a58);
  a71=(a66*a70);
  a72=(a14*a61);
  a72=(a66-a72);
  a73=(a58*a72);
  a71=(a71+a73);
  a73=(a61*a70);
  a74=(a3*a73);
  a75=(a61*a72);
  a76=(a10*a75);
  a74=(a74+a76);
  a74=(a71-a74);
  a68=(a68-a74);
  a74=(a68*a45);
  a62=(a72*a62);
  a76=(a62-a75);
  a77=(a24*a76);
  a74=(a74+a77);
  a53=(a53+a74);
  a74=(a65*a20);
  a77=(a36*a54);
  a28=(a49*a28);
  a77=(a77+a28);
  a46=(a46+a77);
  a46=(a74*a46);
  a53=(a53+a46);
  a46=arg[1]? arg[1][1] : 0;
  a77=(a30*a20);
  a28=(a77-a59);
  a78=(a65*a28);
  a79=(a3*a20);
  a79=(a65-a79);
  a80=(a59*a79);
  a78=(a78+a80);
  a80=(a34*a6);
  a80=(a80-a14);
  a81=(a80*a60);
  a82=(a13*a67);
  a81=(a81+a82);
  a71=(a71+a81);
  a81=(a34*a68);
  a71=(a71+a81);
  a78=(a78+a71);
  a71=(a20*a79);
  a81=(a50*a60);
  a82=(a31*a67);
  a81=(a81+a82);
  a81=(a75+a81);
  a82=(a17*a68);
  a81=(a81+a82);
  a71=(a71+a81);
  a81=(a9*a71);
  a78=(a78-a81);
  a46=(a46-a78);
  a78=(a46*a54);
  a81=(a79*a20);
  a82=(a6*a40);
  a82=(a60*a82);
  a83=(a80*a63);
  a82=(a82+a83);
  a43=(a67*a43);
  a82=(a82+a43);
  a62=(a62+a82);
  a82=(a68*a40);
  a43=(a34*a76);
  a82=(a82-a43);
  a62=(a62+a82);
  a81=(a81+a62);
  a62=(a50*a63);
  a23=(a60*a23);
  a62=(a62-a23);
  a29=(a67*a29);
  a62=(a62+a29);
  a29=(a68*a22);
  a23=(a17*a76);
  a29=(a29+a23);
  a62=(a62-a29);
  a62=(a9*a62);
  a71=(a71+a62);
  a81=(a81-a71);
  a71=(a49*a81);
  a78=(a78-a71);
  a53=(a53+a78);
  a53=(a53/a48);
  a78=arg[1]? arg[1][0] : 0;
  a71=(a47*a60);
  a62=(a26*a67);
  a71=(a71+a62);
  a71=(a71-a73);
  a62=(a24*a68);
  a71=(a71-a62);
  a62=(a20*a28);
  a71=(a71-a62);
  a62=(a49*a36);
  a62=(a26-a62);
  a29=(a62*a74);
  a71=(a71-a29);
  a29=(a49*a46);
  a71=(a71+a29);
  a78=(a78-a71);
  a78=(a78/a48);
  a71=(a78/a48);
  a56=(a71*a56);
  a53=(a53+a56);
  a44=(a44-a53);
  if (res[0]!=0) res[0][3]=a44;
  a81=(a81/a33);
  a53=(a46/a33);
  a56=(a53/a33);
  a42=(a56*a42);
  a81=(a81+a42);
  a51=(a1*a51);
  a78=(a78-a51);
  a54=(a78*a54);
  a51=(a49*a44);
  a54=(a54+a51);
  a51=(a1-a74);
  a32=(a51*a32);
  a54=(a54+a32);
  a81=(a81+a54);
  a54=(-a81);
  if (res[0]!=0) res[0][4]=a54;
  a76=(a76/a16);
  a54=(a68/a16);
  a54=(a54/a16);
  a21=(a54*a21);
  a76=(a76+a21);
  a21=(a49*a78);
  a32=(a37*a51);
  a21=(a21+a32);
  a53=(a53-a21);
  a40=(a53*a40);
  a21=(a34*a81);
  a40=(a40-a21);
  a21=(a9*a53);
  a21=(a51-a21);
  a21=(a67+a21);
  a22=(a21*a22);
  a81=(a9*a81);
  a81=(a53-a81);
  a81=(a17*a81);
  a22=(a22+a81);
  a63=(a63+a44);
  a63=(a24*a63);
  a44=(a60+a78);
  a45=(a44*a45);
  a63=(a63-a45);
  a22=(a22+a63);
  a40=(a40-a22);
  a76=(a76+a40);
  a76=(-a76);
  if (res[0]!=0) res[0][5]=a76;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  a76=cos(a2);
  a40=(a5*a76);
  a2=sin(a2);
  a22=(a8*a2);
  a40=(a40-a22);
  a22=(a40/a16);
  a5=(a5*a2);
  a8=(a8*a76);
  a5=(a5+a8);
  a8=(a2+a5);
  a63=(a3*a8);
  a45=(a14*a2);
  a63=(a63+a45);
  a45=(a76+a40);
  a81=(a10*a45);
  a32=(a11*a76);
  a81=(a81+a32);
  a63=(a63+a81);
  a81=(a19*a45);
  a32=(a14+a14);
  a42=(a32*a8);
  a81=(a81+a42);
  a63=(a63-a81);
  a42=(a6*a2);
  a29=(a3*a5);
  a42=(a42+a29);
  a29=(a12*a76);
  a23=(a10*a40);
  a29=(a29+a23);
  a42=(a42+a29);
  a42=(a63+a42);
  a29=(a18*a42);
  a22=(a22+a29);
  a29=(a6*a22);
  a23=(a17*a5);
  a29=(a29+a23);
  a23=(a24*a63);
  a82=(a5/a16);
  a43=(a35*a42);
  a82=(a82+a43);
  a43=(a15*a82);
  a23=(a23-a43);
  a23=(a23+a8);
  a23=(a23+a2);
  a43=(a12*a82);
  a83=(a24*a40);
  a43=(a43+a83);
  a83=(a9*a43);
  a23=(a23+a83);
  a83=(a37*a23);
  a84=(a17*a63);
  a85=(a15*a22);
  a84=(a84-a85);
  a84=(a45+a84);
  a84=(a76+a84);
  a85=(a12*a22);
  a86=(a17*a40);
  a85=(a85+a86);
  a86=(a9*a85);
  a84=(a84+a86);
  a86=(a84/a33);
  a87=(a63/a16);
  a88=(a41*a42);
  a87=(a87-a88);
  a88=(a12*a87);
  a40=(a34*a40);
  a88=(a88-a40);
  a88=(a45+a88);
  a40=(a76+a88);
  a40=(a9*a40);
  a39=(a39*a76);
  a89=(a3+a3);
  a89=(a89*a2);
  a39=(a39+a89);
  a89=(a15*a87);
  a63=(a34*a63);
  a89=(a89+a63);
  a81=(a81+a89);
  a39=(a39+a81);
  a40=(a40-a39);
  a39=(a9*a84);
  a40=(a40+a39);
  a39=(a38*a40);
  a86=(a86+a39);
  a39=(a25*a86);
  a83=(a83-a39);
  a83=(a29+a83);
  a83=(a83/a48);
  a39=(a6*a82);
  a81=(a24*a5);
  a39=(a39+a81);
  a81=(a23/a33);
  a89=(a55*a40);
  a81=(a81-a89);
  a89=(a25*a81);
  a23=(a49*a23);
  a89=(a89+a23);
  a89=(a39-a89);
  a23=(a52*a89);
  a83=(a83+a23);
  a83=(a1*a83);
  a39=(a60*a39);
  a23=(a57*a76);
  a63=(a20*a23);
  a90=(a47*a63);
  a39=(a39-a90);
  a90=(a67*a43);
  a91=(a57*a2);
  a92=(a20*a91);
  a93=(a26*a92);
  a90=(a90+a93);
  a39=(a39-a90);
  a45=(a61*a45);
  a45=(a23-a45);
  a90=(a61*a45);
  a39=(a39-a90);
  a93=(a68*a82);
  a45=(a66*a45);
  a94=(a70*a91);
  a45=(a45-a94);
  a94=(a61*a8);
  a94=(a94-a91);
  a91=(a58*a94);
  a23=(a72*a23);
  a91=(a91-a23);
  a45=(a45+a91);
  a90=(a3*a90);
  a73=(a73*a2);
  a90=(a90-a73);
  a94=(a61*a94);
  a73=(a10*a94);
  a75=(a75*a76);
  a73=(a73-a75);
  a90=(a90+a73);
  a90=(a45-a90);
  a73=(a24*a90);
  a93=(a93+a73);
  a39=(a39+a93);
  a76=(a20*a76);
  a93=(a20*a76);
  a39=(a39+a93);
  a93=(a36*a81);
  a84=(a49*a84);
  a93=(a93-a84);
  a43=(a43+a93);
  a43=(a74*a43);
  a39=(a39+a43);
  a43=(a46*a81);
  a2=(a20*a2);
  a93=(a59*a2);
  a76=(a65*a76);
  a93=(a93-a76);
  a76=(a6*a87);
  a5=(a34*a5);
  a76=(a76-a5);
  a76=(a76+a8);
  a76=(a60*a76);
  a8=(a80*a63);
  a76=(a76-a8);
  a88=(a67*a88);
  a8=(a13*a92);
  a88=(a88+a8);
  a76=(a76-a88);
  a45=(a45+a76);
  a76=(a68*a87);
  a88=(a34*a90);
  a76=(a76-a88);
  a45=(a45+a76);
  a93=(a93+a45);
  a2=(a20*a2);
  a85=(a67*a85);
  a45=(a31*a92);
  a85=(a85-a45);
  a29=(a60*a29);
  a45=(a50*a63);
  a29=(a29+a45);
  a85=(a85-a29);
  a94=(a94+a85);
  a85=(a68*a22);
  a29=(a17*a90);
  a85=(a85+a29);
  a94=(a94-a85);
  a2=(a2+a94);
  a2=(a9*a2);
  a93=(a93-a2);
  a2=(a49*a93);
  a43=(a43-a2);
  a39=(a39+a43);
  a39=(a39/a48);
  a89=(a71*a89);
  a39=(a39+a89);
  a83=(a83-a39);
  if (res[0]!=0) res[0][9]=a83;
  a93=(a93/a33);
  a40=(a56*a40);
  a93=(a93+a40);
  a81=(a78*a81);
  a40=(a49*a83);
  a81=(a81+a40);
  a86=(a51*a86);
  a81=(a81-a86);
  a93=(a93+a81);
  a81=(-a93);
  if (res[0]!=0) res[0][10]=a81;
  a90=(a90/a16);
  a42=(a54*a42);
  a90=(a90+a42);
  a42=(a9*a93);
  a42=(a42-a92);
  a42=(a17*a42);
  a22=(a21*a22);
  a42=(a42-a22);
  a83=(a83-a63);
  a83=(a24*a83);
  a82=(a44*a82);
  a83=(a83-a82);
  a42=(a42-a83);
  a87=(a53*a87);
  a93=(a34*a93);
  a87=(a87-a93);
  a42=(a42+a87);
  a90=(a90+a42);
  a90=(-a90);
  if (res[0]!=0) res[0][11]=a90;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  a90=cos(a4);
  a42=(a3*a90);
  a4=sin(a4);
  a87=(a7*a4);
  a42=(a42-a87);
  a87=(a42/a16);
  a4=(a3*a4);
  a7=(a7*a90);
  a4=(a4+a7);
  a7=(a3*a4);
  a90=(a10*a42);
  a7=(a7+a90);
  a19=(a19*a42);
  a32=(a32*a4);
  a19=(a19+a32);
  a7=(a7-a19);
  a32=(a3*a4);
  a90=(a10*a42);
  a32=(a32+a90);
  a32=(a7+a32);
  a18=(a18*a32);
  a87=(a87+a18);
  a18=(a6*a87);
  a90=(a17*a4);
  a18=(a18+a90);
  a90=(a24*a7);
  a93=(a4/a16);
  a35=(a35*a32);
  a93=(a93+a35);
  a35=(a15*a93);
  a90=(a90-a35);
  a90=(a90+a4);
  a35=(a12*a93);
  a83=(a24*a42);
  a35=(a35+a83);
  a83=(a9*a35);
  a90=(a90+a83);
  a83=(a37*a90);
  a82=(a17*a7);
  a63=(a15*a87);
  a82=(a82-a63);
  a82=(a42+a82);
  a63=(a12*a87);
  a22=(a17*a42);
  a63=(a63+a22);
  a22=(a9*a63);
  a82=(a82+a22);
  a22=(a82/a33);
  a92=(a7/a16);
  a41=(a41*a32);
  a92=(a92-a41);
  a12=(a12*a92);
  a41=(a34*a42);
  a12=(a12-a41);
  a12=(a42+a12);
  a41=(a9*a12);
  a15=(a15*a92);
  a7=(a34*a7);
  a15=(a15+a7);
  a19=(a19+a15);
  a41=(a41-a19);
  a19=(a9*a82);
  a41=(a41+a19);
  a38=(a38*a41);
  a22=(a22+a38);
  a38=(a25*a22);
  a83=(a83-a38);
  a83=(a18+a83);
  a83=(a83/a48);
  a38=(a6*a93);
  a19=(a24*a4);
  a38=(a38+a19);
  a19=(a90/a33);
  a55=(a55*a41);
  a19=(a19-a55);
  a25=(a25*a19);
  a90=(a49*a90);
  a25=(a25+a90);
  a25=(a38-a25);
  a52=(a52*a25);
  a83=(a83+a52);
  a1=(a1*a83);
  a38=(a60*a38);
  a83=(a67*a35);
  a38=(a38-a83);
  a42=(a61*a42);
  a83=(a61*a42);
  a38=(a38+a83);
  a52=(a68*a93);
  a90=(a61*a4);
  a55=(a58*a90);
  a42=(a66*a42);
  a55=(a55-a42);
  a90=(a61*a90);
  a42=(a10*a90);
  a83=(a3*a83);
  a42=(a42-a83);
  a42=(a55-a42);
  a83=(a24*a42);
  a52=(a52+a83);
  a38=(a38+a52);
  a36=(a36*a19);
  a82=(a49*a82);
  a36=(a36-a82);
  a35=(a35+a36);
  a74=(a74*a35);
  a38=(a38+a74);
  a46=(a46*a19);
  a74=(a6*a92);
  a35=(a34*a4);
  a74=(a74-a35);
  a74=(a74+a4);
  a74=(a60*a74);
  a12=(a67*a12);
  a74=(a74-a12);
  a55=(a55+a74);
  a74=(a68*a92);
  a12=(a34*a42);
  a74=(a74-a12);
  a55=(a55+a74);
  a67=(a67*a63);
  a60=(a60*a18);
  a67=(a67-a60);
  a90=(a90+a67);
  a68=(a68*a87);
  a67=(a17*a42);
  a68=(a68+a67);
  a90=(a90-a68);
  a90=(a9*a90);
  a55=(a55-a90);
  a90=(a49*a55);
  a46=(a46-a90);
  a38=(a38+a46);
  a38=(a38/a48);
  a71=(a71*a25);
  a38=(a38+a71);
  a1=(a1-a38);
  if (res[0]!=0) res[0][15]=a1;
  a55=(a55/a33);
  a56=(a56*a41);
  a55=(a55+a56);
  a78=(a78*a19);
  a19=(a49*a1);
  a78=(a78+a19);
  a51=(a51*a22);
  a78=(a78-a51);
  a55=(a55+a78);
  a78=(-a55);
  if (res[0]!=0) res[0][16]=a78;
  a42=(a42/a16);
  a54=(a54*a32);
  a42=(a42+a54);
  a54=(a9*a55);
  a54=(a17*a54);
  a21=(a21*a87);
  a54=(a54-a21);
  a1=(a24*a1);
  a44=(a44*a93);
  a1=(a1-a44);
  a54=(a54-a1);
  a53=(a53*a92);
  a55=(a34*a55);
  a53=(a53-a55);
  a54=(a54+a53);
  a42=(a42+a54);
  a42=(-a42);
  if (res[0]!=0) res[0][17]=a42;
  if (res[0]!=0) res[0][18]=a27;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  a42=(a10*a61);
  a42=(a69-a42);
  a54=(a24*a42);
  a53=(a26*a57);
  a54=(a54-a53);
  a53=(a62*a20);
  a54=(a54-a53);
  a53=(a13*a57);
  a69=(a69-a53);
  a53=(a34*a42);
  a69=(a69-a53);
  a77=(a77+a69);
  a69=(a31*a57);
  a69=(a61-a69);
  a53=(a17*a42);
  a69=(a69-a53);
  a69=(a20+a69);
  a69=(a9*a69);
  a77=(a77-a69);
  a69=(a49*a77);
  a54=(a54-a69);
  a54=(a54/a48);
  a69=(-a54);
  if (res[0]!=0) res[0][21]=a69;
  a69=(a49*a54);
  a53=(a37*a20);
  a69=(a69+a53);
  a77=(a77/a33);
  a69=(a69-a77);
  if (res[0]!=0) res[0][22]=a69;
  a42=(a42/a16);
  a54=(a24*a54);
  a77=(a9*a69);
  a77=(a20+a77);
  a57=(a57+a77);
  a57=(a17*a57);
  a54=(a54-a57);
  a69=(a34*a69);
  a54=(a54+a69);
  a42=(a42+a54);
  a42=(-a42);
  if (res[0]!=0) res[0][23]=a42;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a27;
  if (res[0]!=0) res[0][26]=a0;
  a42=(a20*a9);
  a42=(a58+a42);
  a54=(a61*a9);
  a54=(a54+a59);
  a42=(a42-a54);
  a54=(a47*a42);
  a69=(a26*a64);
  a54=(a54+a69);
  a69=(a11-a9);
  a57=(a61*a69);
  a57=(a70+a57);
  a54=(a54-a57);
  a69=(a66*a69);
  a77=(a72*a9);
  a53=(a58*a14);
  a77=(a77-a53);
  a69=(a69+a77);
  a57=(a3*a57);
  a14=(a61*a14);
  a14=(a72-a14);
  a77=(a10*a14);
  a57=(a57+a77);
  a57=(a69-a57);
  a77=(a24*a57);
  a54=(a54+a77);
  a30=(a30-a9);
  a77=(a20*a30);
  a28=(a28+a77);
  a54=(a54-a28);
  a62=(a62*a65);
  a54=(a54-a62);
  a30=(a65*a30);
  a62=(a79*a9);
  a28=(a59*a3);
  a62=(a62-a28);
  a30=(a30+a62);
  a62=(a80*a42);
  a28=(a13*a64);
  a62=(a62+a28);
  a69=(a69+a62);
  a62=(a34*a57);
  a69=(a69-a62);
  a30=(a30+a69);
  a69=(a20*a3);
  a79=(a79-a69);
  a69=(a50*a42);
  a62=(a31*a64);
  a69=(a69+a62);
  a14=(a14+a69);
  a69=(a17*a57);
  a14=(a14-a69);
  a79=(a79+a14);
  a79=(a9*a79);
  a30=(a30-a79);
  a79=(a49*a30);
  a54=(a54-a79);
  a54=(a54/a48);
  a79=(-a54);
  if (res[0]!=0) res[0][27]=a79;
  a79=(a49*a54);
  a37=(a37*a65);
  a79=(a79+a37);
  a30=(a30/a33);
  a79=(a79-a30);
  if (res[0]!=0) res[0][28]=a79;
  a57=(a57/a16);
  a30=(a9*a79);
  a30=(a65+a30);
  a64=(a64-a30);
  a64=(a17*a64);
  a42=(a42-a54);
  a42=(a24*a42);
  a64=(a64-a42);
  a79=(a34*a79);
  a64=(a64+a79);
  a57=(a57+a64);
  a57=(-a57);
  if (res[0]!=0) res[0][29]=a57;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a27;
  a27=(a20*a10);
  a27=(a27-a59);
  a47=(a47*a27);
  a20=(a20*a3);
  a20=(a20-a65);
  a26=(a26*a20);
  a47=(a47+a26);
  a11=(a11-a10);
  a26=(a61*a11);
  a26=(a70+a26);
  a47=(a47-a26);
  a70=(a70*a3);
  a66=(a66*a11);
  a70=(a70+a66);
  a66=(a72*a10);
  a58=(a58*a6);
  a66=(a66-a58);
  a70=(a70+a66);
  a3=(a3*a26);
  a61=(a61*a6);
  a72=(a72-a61);
  a10=(a10*a72);
  a3=(a3+a10);
  a3=(a70-a3);
  a10=(a24*a3);
  a47=(a47+a10);
  a80=(a80*a27);
  a13=(a13*a20);
  a80=(a80+a13);
  a70=(a70+a80);
  a80=(a34*a3);
  a70=(a70-a80);
  a50=(a50*a27);
  a31=(a31*a20);
  a50=(a50+a31);
  a72=(a72+a50);
  a50=(a17*a3);
  a72=(a72-a50);
  a72=(a9*a72);
  a70=(a70-a72);
  a72=(a49*a70);
  a47=(a47-a72);
  a47=(a47/a48);
  a72=(-a47);
  if (res[0]!=0) res[0][33]=a72;
  a72=(a49*a47);
  a70=(a70/a33);
  a72=(a72-a70);
  if (res[0]!=0) res[0][34]=a72;
  a3=(a3/a16);
  a70=(a9*a72);
  a20=(a20-a70);
  a20=(a17*a20);
  a27=(a27-a47);
  a27=(a24*a27);
  a20=(a20-a27);
  a72=(a34*a72);
  a20=(a20+a72);
  a3=(a3+a20);
  a3=(-a3);
  if (res[0]!=0) res[0][35]=a3;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  a3=(1./a48);
  if (res[1]!=0) res[1][3]=a3;
  a3=(a49/a48);
  a20=(-a3);
  if (res[1]!=0) res[1][4]=a20;
  a20=(a9*a3);
  a20=(a17*a20);
  a72=(a24/a48);
  a20=(a20-a72);
  a3=(a34*a3);
  a20=(a20-a3);
  a20=(-a20);
  if (res[1]!=0) res[1][5]=a20;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a0;
  if (res[1]!=0) res[1][8]=a0;
  a20=(a49/a48);
  a3=(-a20);
  if (res[1]!=0) res[1][9]=a3;
  a3=(1./a33);
  a72=(a49*a20);
  a3=(a3+a72);
  if (res[1]!=0) res[1][10]=a3;
  a20=(a24*a20);
  a72=(a9*a3);
  a72=(a17*a72);
  a20=(a20-a72);
  a3=(a34*a3);
  a20=(a20+a3);
  a20=(-a20);
  if (res[1]!=0) res[1][11]=a20;
  if (res[1]!=0) res[1][12]=a0;
  if (res[1]!=0) res[1][13]=a0;
  if (res[1]!=0) res[1][14]=a0;
  a0=(a9*a17);
  a0=(a34-a0);
  a20=(a49*a0);
  a20=(a24+a20);
  a20=(a20/a48);
  if (res[1]!=0) res[1][15]=a20;
  a0=(a0/a33);
  a49=(a49*a20);
  a0=(a0+a49);
  a49=(-a0);
  if (res[1]!=0) res[1][16]=a49;
  a16=(1./a16);
  a9=(a9*a0);
  a17=(a17*a9);
  a24=(a24*a20);
  a17=(a17-a24);
  a34=(a34*a0);
  a17=(a17-a34);
  a16=(a16-a17);
  if (res[1]!=0) res[1][17]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_deriv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dynamics_deriv_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_deriv_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_deriv_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dynamics_deriv_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_deriv_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dynamics_deriv_incref(void) {
}

CASADI_SYMBOL_EXPORT void dynamics_deriv_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dynamics_deriv_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int dynamics_deriv_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real dynamics_deriv_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_deriv_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_deriv_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_deriv_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_deriv_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dynamics_deriv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_deriv_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
