/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) inverse_dynamics_hvp_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {3, 6, 1};
static const casadi_int casadi_s3[3] = {3, 3, 1};

/* inverse_dynamics_hvp:(i0[6],i1[3],i2[6])->(o0[3x6],o1[3x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a01=arg[0]? arg[0][1] : 0;
  a02=cos(a01);
  a03=arg[2]? arg[2][4] : 0;
  a04=arg[0]? arg[0][3] : 0;
  a05=cos(a01);
  a06=(a04*a05);
  a07=(a03*a06);
  a08=arg[0]? arg[0][4] : 0;
  a09=arg[2]? arg[2][3] : 0;
  a10=(a09*a05);
  a11=arg[2]? arg[2][1] : 0;
  a12=sin(a01);
  a12=(a11*a12);
  a13=(a04*a12);
  a10=(a10-a13);
  a13=(a08*a10);
  a07=(a07+a13);
  a13=9.8100000000000005e+00;
  a14=(a13*a12);
  a15=arg[1]? arg[1][0] : 0;
  a16=cos(a01);
  a16=(a11*a16);
  a17=(a15*a16);
  a14=(a14+a17);
  a17=(a03*a06);
  a18=(a08*a10);
  a17=(a17+a18);
  a14=(a14+a17);
  a07=(a07-a14);
  a17=arg[0]? arg[0][2] : 0;
  a18=cos(a17);
  a19=cos(a17);
  a20=arg[2]? arg[2][2] : 0;
  a19=(a19*a20);
  a21=sin(a01);
  a22=(a04*a21);
  a23=(a08*a22);
  a24=(a13*a21);
  a25=(a15*a05);
  a24=(a24+a25);
  a23=(a23-a24);
  a24=(a19*a23);
  a25=sin(a17);
  a26=(a13*a16);
  a27=(a15*a12);
  a26=(a26-a27);
  a27=(a03*a22);
  a28=(a09*a21);
  a29=(a04*a16);
  a28=(a28+a29);
  a29=(a08*a28);
  a27=(a27+a29);
  a26=(a26-a27);
  a27=(a25*a26);
  a24=(a24-a27);
  a27=(a18*a14);
  a29=sin(a17);
  a29=(a29*a20);
  a30=(a13*a05);
  a31=(a15*a21);
  a30=(a30-a31);
  a31=(a08*a06);
  a31=(a30-a31);
  a32=(a29*a31);
  a27=(a27+a32);
  a24=(a24-a27);
  a27=arg[2]? arg[2][5] : 0;
  a32=(a18*a06);
  a33=(a25*a22);
  a32=(a32-a33);
  a33=(a27*a32);
  a34=arg[0]? arg[0][5] : 0;
  a35=(a18*a10);
  a36=(a29*a06);
  a35=(a35-a36);
  a36=(a19*a22);
  a37=(a25*a28);
  a36=(a36+a37);
  a35=(a35-a36);
  a36=(a34*a35);
  a33=(a33+a36);
  a24=(a24-a33);
  a33=(a27+a03);
  a36=(a33*a32);
  a37=(a34+a08);
  a38=(a37*a35);
  a36=(a36+a38);
  a36=(a24+a36);
  a38=(a18*a36);
  a39=(a18*a31);
  a40=(a25*a23);
  a39=(a39+a40);
  a40=(a34*a32);
  a39=(a39-a40);
  a40=(a37*a32);
  a39=(a39+a40);
  a40=(a29*a39);
  a38=(a38-a40);
  a40=(a18*a23);
  a41=(a25*a31);
  a40=(a40-a41);
  a41=(a18*a22);
  a42=(a25*a06);
  a41=(a41+a42);
  a42=(a34*a41);
  a40=(a40+a42);
  a42=(a37*a41);
  a40=(a40-a42);
  a42=(a19*a40);
  a43=(a29*a22);
  a44=(a18*a28);
  a43=(a43-a44);
  a44=(a19*a06);
  a45=(a25*a10);
  a44=(a44+a45);
  a43=(a43-a44);
  a44=(a37*a43);
  a45=(a33*a41);
  a44=(a44-a45);
  a45=(a29*a23);
  a46=(a18*a26);
  a45=(a45+a46);
  a31=(a19*a31);
  a46=(a25*a14);
  a31=(a31-a46);
  a45=(a45+a31);
  a31=(a34*a43);
  a46=(a27*a41);
  a31=(a31-a46);
  a45=(a45+a31);
  a44=(a44-a45);
  a45=(a25*a44);
  a42=(a42+a45);
  a38=(a38-a42);
  a07=(a07+a38);
  a07=(a02*a07);
  a42=cos(a01);
  a42=(a42*a11);
  a45=(a13*a42);
  a31=sin(a01);
  a31=(a31*a11);
  a46=(a15*a31);
  a45=(a45-a46);
  a46=sin(a01);
  a47=(a46*a04);
  a48=(a47*a03);
  a49=(a04*a42);
  a50=(a46*a09);
  a49=(a49+a50);
  a50=(a08*a49);
  a48=(a48+a50);
  a45=(a45-a48);
  a48=(a47*a03);
  a50=(a08*a49);
  a48=(a48+a50);
  a48=(a45+a48);
  a50=(a18*a45);
  a51=(a02*a15);
  a52=(a13*a46);
  a51=(a51+a52);
  a52=(a08*a47);
  a51=(a51-a52);
  a52=arg[1]? arg[1][1] : 0;
  a53=(a51-a52);
  a54=(a53*a29);
  a50=(a50-a54);
  a54=(a13*a02);
  a55=(a46*a15);
  a54=(a54-a55);
  a55=(a02*a04);
  a56=(a08*a55);
  a54=(a54-a56);
  a56=(a54*a19);
  a13=(a13*a31);
  a15=(a15*a42);
  a13=(a13+a15);
  a15=(a55*a03);
  a09=(a02*a09);
  a04=(a04*a31);
  a09=(a09-a04);
  a04=(a08*a09);
  a15=(a15+a04);
  a13=(a13+a15);
  a15=(a25*a13);
  a56=(a56-a15);
  a50=(a50+a56);
  a56=(a55-a08);
  a15=(a25*a56);
  a04=(a18*a47);
  a15=(a15+a04);
  a04=(a15*a27);
  a57=(a56*a19);
  a58=(a09-a03);
  a59=(a25*a58);
  a57=(a57+a59);
  a59=(a18*a49);
  a60=(a47*a29);
  a59=(a59-a60);
  a57=(a57+a59);
  a59=(a34*a57);
  a04=(a04+a59);
  a50=(a50-a04);
  a04=(a15*a33);
  a59=(a37*a57);
  a04=(a04+a59);
  a50=(a50+a04);
  a04=(a18*a50);
  a59=(a18*a53);
  a60=(a25*a54);
  a59=(a59+a60);
  a60=(a34*a15);
  a59=(a59-a60);
  a60=arg[1]? arg[1][2] : 0;
  a60=(a60+a52);
  a59=(a59-a60);
  a60=(a37*a15);
  a59=(a59+a60);
  a60=(a59*a29);
  a04=(a04-a60);
  a60=(a18*a54);
  a61=(a25*a53);
  a60=(a60-a61);
  a61=(a18*a56);
  a62=(a25*a47);
  a61=(a61-a62);
  a62=(a34*a61);
  a60=(a60-a62);
  a62=(a61-a37);
  a63=(a37*a62);
  a60=(a60+a63);
  a63=(a60*a19);
  a64=(a62*a33);
  a65=(a18*a58);
  a66=(a56*a29);
  a65=(a65-a66);
  a66=(a47*a19);
  a67=(a25*a49);
  a66=(a66+a67);
  a65=(a65-a66);
  a66=(a65-a33);
  a67=(a37*a66);
  a64=(a64+a67);
  a67=(a54*a29);
  a68=(a18*a13);
  a67=(a67+a68);
  a68=(a53*a19);
  a69=(a25*a45);
  a68=(a68+a69);
  a67=(a67+a68);
  a68=(a61*a27);
  a69=(a34*a65);
  a68=(a68+a69);
  a67=(a67+a68);
  a64=(a64-a67);
  a67=(a25*a64);
  a63=(a63+a67);
  a04=(a04-a63);
  a48=(a48+a04);
  a48=(a48*a21);
  a07=(a07-a48);
  a48=(a18*a39);
  a21=(a25*a40);
  a48=(a48-a21);
  a30=(a30+a48);
  a30=(a31*a30);
  a51=(a51-a52);
  a52=(a08*a47);
  a51=(a51+a52);
  a52=(a18*a59);
  a48=(a25*a60);
  a52=(a52-a48);
  a51=(a51+a52);
  a51=(a51*a16);
  a30=(a30+a51);
  a07=(a07-a30);
  a30=(a08*a22);
  a23=(a23-a30);
  a30=(a25*a39);
  a51=(a18*a40);
  a30=(a30+a51);
  a23=(a23+a30);
  a23=(a42*a23);
  a30=(a55-a08);
  a51=(a08*a30);
  a51=(a54+a51);
  a16=(a25*a59);
  a52=(a18*a60);
  a16=(a16+a52);
  a51=(a51+a16);
  a51=(a51*a12);
  a23=(a23-a51);
  a51=(a30*a03);
  a12=(a09-a03);
  a16=(a08*a12);
  a51=(a51+a16);
  a51=(a51-a13);
  a16=(a59*a19);
  a52=(a25*a50);
  a16=(a16+a52);
  a52=(a18*a64);
  a48=(a60*a29);
  a52=(a52-a48);
  a16=(a16+a52);
  a51=(a51+a16);
  a51=(a51*a05);
  a39=(a19*a39);
  a36=(a25*a36);
  a39=(a39+a36);
  a44=(a18*a44);
  a40=(a29*a40);
  a44=(a44-a40);
  a39=(a39+a44);
  a44=(a03*a22);
  a40=(a08*a28);
  a44=(a44+a40);
  a44=(a44+a26);
  a39=(a39-a44);
  a39=(a46*a39);
  a51=(a51+a39);
  a23=(a23+a51);
  a07=(a07-a23);
  if (res[0]!=0) res[0][3]=a07;
  a07=(a30*a10);
  a23=(a49*a22);
  a07=(a07-a23);
  a23=(a12*a06);
  a51=(a47*a28);
  a23=(a23-a51);
  a07=(a07+a23);
  a06=(a09*a06);
  a28=(a47*a28);
  a06=(a06-a28);
  a10=(a55*a10);
  a22=(a49*a22);
  a10=(a10-a22);
  a06=(a06+a10);
  a07=(a07-a06);
  a07=(a07+a14);
  a14=(a62*a35);
  a06=(a57*a41);
  a14=(a14-a06);
  a06=(a66*a32);
  a10=(a15*a43);
  a06=(a06+a10);
  a14=(a14+a06);
  a32=(a65*a32);
  a43=(a15*a43);
  a32=(a32+a43);
  a35=(a61*a35);
  a41=(a57*a41);
  a35=(a35-a41);
  a32=(a32+a35);
  a14=(a14-a32);
  a14=(a14-a24);
  a38=(a14-a38);
  a07=(a07+a38);
  if (res[0]!=0) res[0][4]=a07;
  if (res[0]!=0) res[0][5]=a14;
  a14=cos(a17);
  a07=(a56*a14);
  a38=sin(a17);
  a24=(a47*a38);
  a07=(a07-a24);
  a24=(a33*a07);
  a32=(a58*a14);
  a35=sin(a17);
  a35=(a20*a35);
  a41=(a56*a35);
  a32=(a32-a41);
  a41=(a49*a38);
  a43=cos(a17);
  a43=(a20*a43);
  a06=(a47*a43);
  a41=(a41+a06);
  a32=(a32-a41);
  a41=(a37*a32);
  a24=(a24+a41);
  a41=(a45*a38);
  a06=(a53*a43);
  a41=(a41+a06);
  a06=(a54*a35);
  a10=(a13*a14);
  a06=(a06+a10);
  a41=(a41+a06);
  a06=(a27*a07);
  a10=(a34*a32);
  a06=(a06+a10);
  a41=(a41+a06);
  a24=(a24-a41);
  a06=(a18*a24);
  a10=(a50*a38);
  a06=(a06-a10);
  a10=(a54*a14);
  a22=(a53*a38);
  a10=(a10-a22);
  a22=(a34*a07);
  a10=(a10-a22);
  a22=(a37*a07);
  a10=(a10+a22);
  a22=(a29*a10);
  a28=(a59*a43);
  a22=(a22+a28);
  a06=(a06-a22);
  a22=(a56*a38);
  a28=(a47*a14);
  a22=(a22+a28);
  a28=(a34*a22);
  a23=(a54*a38);
  a51=(a53*a14);
  a23=(a23+a51);
  a28=(a28-a23);
  a23=(a37*a22);
  a28=(a28-a23);
  a23=(a19*a28);
  a51=(a60*a35);
  a23=(a23-a51);
  a51=(a64*a14);
  a39=(a33*a22);
  a58=(a58*a38);
  a56=(a56*a43);
  a58=(a58+a56);
  a56=(a49*a14);
  a44=(a47*a35);
  a56=(a56-a44);
  a58=(a58+a56);
  a56=(a37*a58);
  a39=(a39+a56);
  a54=(a54*a43);
  a13=(a13*a38);
  a54=(a54-a13);
  a45=(a45*a14);
  a53=(a53*a35);
  a45=(a45-a53);
  a54=(a54+a45);
  a45=(a27*a22);
  a53=(a34*a58);
  a45=(a45+a53);
  a54=(a54-a45);
  a39=(a39+a54);
  a54=(a25*a39);
  a51=(a51-a54);
  a23=(a23+a51);
  a06=(a06-a23);
  a23=(a02*a06);
  a51=(a18*a10);
  a54=(a59*a38);
  a51=(a51-a54);
  a54=(a60*a14);
  a45=(a25*a28);
  a54=(a54+a45);
  a51=(a51-a54);
  a51=(a31*a51);
  a23=(a23-a51);
  a51=(a59*a14);
  a54=(a25*a10);
  a51=(a51+a54);
  a54=(a18*a28);
  a45=(a60*a38);
  a54=(a54-a45);
  a51=(a51+a54);
  a51=(a42*a51);
  a10=(a19*a10);
  a59=(a59*a35);
  a10=(a10-a59);
  a50=(a50*a14);
  a24=(a25*a24);
  a50=(a50+a24);
  a10=(a10+a50);
  a64=(a64*a38);
  a39=(a18*a39);
  a64=(a64+a39);
  a28=(a29*a28);
  a60=(a60*a43);
  a28=(a28+a60);
  a64=(a64+a28);
  a10=(a10-a64);
  a10=(a46*a10);
  a51=(a51+a10);
  a23=(a23-a51);
  if (res[0]!=0) res[0][6]=a23;
  a23=(a62*a32);
  a51=(a57*a22);
  a23=(a23-a51);
  a51=(a66*a07);
  a10=(a15*a58);
  a51=(a51-a10);
  a23=(a23+a51);
  a07=(a65*a07);
  a58=(a15*a58);
  a07=(a07-a58);
  a32=(a61*a32);
  a22=(a57*a22);
  a32=(a32-a22);
  a07=(a07+a32);
  a23=(a23-a07);
  a23=(a23+a41);
  a06=(a23-a06);
  if (res[0]!=0) res[0][7]=a06;
  if (res[0]!=0) res[0][8]=a23;
  a23=(a03*a46);
  a06=(a08*a42);
  a23=(a23+a06);
  a06=(a03*a46);
  a41=(a08*a42);
  a06=(a06+a41);
  a23=(a23-a06);
  a41=(a08*a46);
  a07=(a29*a41);
  a32=(a18*a06);
  a07=(a07-a32);
  a32=(a08*a02);
  a22=(a19*a32);
  a58=(a03*a02);
  a51=(a08*a31);
  a58=(a58-a51);
  a51=(a25*a58);
  a22=(a22+a51);
  a07=(a07-a22);
  a22=(a25*a02);
  a51=(a18*a46);
  a22=(a22+a51);
  a51=(a27*a22);
  a10=(a19*a02);
  a64=(a25*a31);
  a10=(a10-a64);
  a64=(a18*a42);
  a28=(a29*a46);
  a64=(a64-a28);
  a10=(a10+a64);
  a64=(a34*a10);
  a51=(a51+a64);
  a07=(a07-a51);
  a51=(a33*a22);
  a64=(a37*a10);
  a51=(a51+a64);
  a51=(a07+a51);
  a64=(a18*a51);
  a28=(a37*a22);
  a60=(a18*a41);
  a43=(a25*a32);
  a60=(a60+a43);
  a43=(a34*a22);
  a60=(a60+a43);
  a28=(a28-a60);
  a60=(a29*a28);
  a64=(a64-a60);
  a60=(a25*a41);
  a43=(a18*a32);
  a60=(a60-a43);
  a43=(a18*a02);
  a39=(a25*a46);
  a43=(a43-a39);
  a39=(a34*a43);
  a60=(a60-a39);
  a39=(a37*a43);
  a60=(a60+a39);
  a39=(a19*a60);
  a38=(a33*a43);
  a50=(a18*a31);
  a24=(a29*a02);
  a50=(a50+a24);
  a24=(a19*a46);
  a14=(a25*a42);
  a24=(a24+a14);
  a50=(a50+a24);
  a24=(a37*a50);
  a38=(a38-a24);
  a24=(a18*a58);
  a32=(a29*a32);
  a24=(a24-a32);
  a41=(a19*a41);
  a32=(a25*a06);
  a41=(a41+a32);
  a24=(a24-a41);
  a41=(a27*a43);
  a32=(a34*a50);
  a41=(a41-a32);
  a24=(a24+a41);
  a38=(a38-a24);
  a24=(a25*a38);
  a39=(a39+a24);
  a64=(a64-a39);
  a23=(a23+a64);
  a23=(a02*a23);
  a39=(a18*a28);
  a24=(a25*a60);
  a39=(a39-a24);
  a39=(a31*a39);
  a23=(a23-a39);
  a39=(a25*a28);
  a24=(a18*a60);
  a39=(a39+a24);
  a39=(a42*a39);
  a24=(a03*a02);
  a41=(a08*a31);
  a24=(a24-a41);
  a24=(a24-a58);
  a28=(a19*a28);
  a51=(a25*a51);
  a28=(a28+a51);
  a38=(a18*a38);
  a60=(a29*a60);
  a38=(a38-a60);
  a28=(a28+a38);
  a24=(a24+a28);
  a24=(a46*a24);
  a39=(a39+a24);
  a23=(a23-a39);
  if (res[0]!=0) res[0][9]=a23;
  a23=(a49*a02);
  a39=(a30*a42);
  a23=(a23+a39);
  a39=(a12*a46);
  a24=(a47*a31);
  a39=(a39-a24);
  a23=(a23+a39);
  a39=(a09*a46);
  a24=(a47*a31);
  a39=(a39-a24);
  a24=(a49*a02);
  a28=(a55*a42);
  a24=(a24+a28);
  a39=(a39+a24);
  a23=(a23-a39);
  a23=(a23+a06);
  a06=(a57*a43);
  a39=(a62*a10);
  a06=(a06+a39);
  a39=(a66*a22);
  a24=(a15*a50);
  a39=(a39-a24);
  a06=(a06+a39);
  a22=(a65*a22);
  a50=(a15*a50);
  a22=(a22-a50);
  a43=(a57*a43);
  a10=(a61*a10);
  a43=(a43+a10);
  a22=(a22+a43);
  a06=(a06-a22);
  a06=(a06-a07);
  a64=(a06-a64);
  a23=(a23+a64);
  if (res[0]!=0) res[0][10]=a23;
  if (res[0]!=0) res[0][11]=a06;
  a06=(a29*a47);
  a23=(a18*a49);
  a06=(a06-a23);
  a23=(a19*a55);
  a64=(a25*a09);
  a23=(a23+a64);
  a06=(a06-a23);
  a23=(a27*a25);
  a64=(a34*a19);
  a23=(a23+a64);
  a06=(a06+a23);
  a23=(a37*a19);
  a23=(a57-a23);
  a64=(a33*a25);
  a23=(a23-a64);
  a23=(a06+a23);
  a64=(a18*a23);
  a07=(a34*a25);
  a22=(a18*a47);
  a43=(a25*a55);
  a22=(a22+a43);
  a07=(a07-a22);
  a22=(a37*a25);
  a22=(a15-a22);
  a07=(a07+a22);
  a22=(a29*a07);
  a64=(a64-a22);
  a22=(a25*a47);
  a43=(a18*a55);
  a22=(a22-a43);
  a43=(a34*a18);
  a22=(a22+a43);
  a43=-1.;
  a10=(a43-a18);
  a50=(a37*a10);
  a50=(a62+a50);
  a22=(a22+a50);
  a50=(a19*a22);
  a39=(a33*a10);
  a24=(a37*a29);
  a24=(a66+a24);
  a39=(a39+a24);
  a24=(a18*a09);
  a28=(a29*a55);
  a24=(a24-a28);
  a47=(a19*a47);
  a49=(a25*a49);
  a47=(a47+a49);
  a24=(a24-a47);
  a34=(a34*a29);
  a27=(a27*a18);
  a34=(a34-a27);
  a24=(a24+a34);
  a39=(a39-a24);
  a24=(a25*a39);
  a50=(a50+a24);
  a64=(a64-a50);
  a50=(a02*a64);
  a24=(a18*a07);
  a34=(a25*a22);
  a24=(a24-a34);
  a24=(a31*a24);
  a50=(a50-a24);
  a30=(a30-a08);
  a30=(a30-a55);
  a55=(a25*a07);
  a08=(a18*a22);
  a55=(a55+a08);
  a30=(a30+a55);
  a30=(a42*a30);
  a12=(a12-a03);
  a12=(a12-a09);
  a07=(a19*a07);
  a23=(a25*a23);
  a07=(a07+a23);
  a39=(a18*a39);
  a22=(a29*a22);
  a39=(a39-a22);
  a07=(a07+a39);
  a12=(a12+a07);
  a12=(a46*a12);
  a30=(a30+a12);
  a50=(a50-a30);
  if (res[0]!=0) res[0][12]=a50;
  a10=(a57*a10);
  a50=(a62*a19);
  a10=(a10-a50);
  a50=(a15*a29);
  a30=(a66*a25);
  a50=(a50-a30);
  a10=(a10+a50);
  a15=(a15*a29);
  a50=(a65*a25);
  a15=(a15-a50);
  a57=(a57*a18);
  a50=(a61*a19);
  a57=(a57+a50);
  a15=(a15-a57);
  a10=(a10-a15);
  a10=(a10-a06);
  a64=(a10-a64);
  if (res[0]!=0) res[0][13]=a64;
  if (res[0]!=0) res[0][14]=a10;
  a62=(a62-a37);
  a62=(a62-a61);
  a61=(a25*a62);
  a31=(a31*a61);
  a19=(a19*a62);
  a66=(a66-a33);
  a66=(a66-a65);
  a65=(a25*a66);
  a19=(a19+a65);
  a65=(a02*a19);
  a31=(a31-a65);
  a65=(a18*a62);
  a42=(a42*a65);
  a66=(a18*a66);
  a29=(a29*a62);
  a66=(a66-a29);
  a66=(a46*a66);
  a42=(a42+a66);
  a31=(a31-a42);
  if (res[0]!=0) res[0][15]=a31;
  if (res[0]!=0) res[0][16]=a19;
  if (res[0]!=0) res[0][17]=a00;
  a19=cos(a17);
  a19=(a19*a20);
  a31=(a18*a46);
  a42=(a25*a02);
  a31=(a31+a42);
  a42=(a19*a31);
  a66=cos(a01);
  a66=(a66*a11);
  a29=(a18*a66);
  a17=sin(a17);
  a17=(a17*a20);
  a20=(a17*a46);
  a29=(a29-a20);
  a20=(a19*a02);
  a01=sin(a01);
  a01=(a01*a11);
  a11=(a25*a01);
  a20=(a20-a11);
  a29=(a29+a20);
  a20=(a25*a29);
  a42=(a42+a20);
  a20=(a18*a01);
  a11=(a17*a02);
  a20=(a20+a11);
  a11=(a19*a46);
  a62=(a25*a66);
  a11=(a11+a62);
  a20=(a20+a11);
  a11=(a18*a20);
  a62=(a18*a02);
  a65=(a25*a46);
  a62=(a62-a65);
  a65=(a17*a62);
  a11=(a11+a65);
  a42=(a42-a11);
  a11=(a42-a01);
  a11=(a02*a11);
  a65=(a18*a62);
  a33=(a25*a31);
  a65=(a65+a33);
  a65=(a02+a65);
  a65=(a01*a65);
  a11=(a11-a65);
  a65=(a25*a62);
  a33=(a18*a31);
  a65=(a65-a33);
  a65=(a65-a46);
  a65=(a66*a65);
  a62=(a19*a62);
  a33=(a25*a20);
  a62=(a62-a33);
  a31=(a17*a31);
  a29=(a18*a29);
  a31=(a31-a29);
  a62=(a62+a31);
  a62=(a62-a66);
  a62=(a46*a62);
  a65=(a65+a62);
  a11=(a11-a65);
  if (res[1]!=0) res[1][0]=a11;
  a42=(a20-a42);
  a42=(a01+a42);
  if (res[1]!=0) res[1][1]=a42;
  if (res[1]!=0) res[1][2]=a20;
  a20=(a18*a17);
  a42=(a43-a18);
  a11=(a17*a42);
  a20=(a20-a11);
  a11=(a19*a25);
  a65=(a25*a19);
  a11=(a11+a65);
  a20=(a20-a11);
  a11=(a02*a20);
  a65=(a18*a42);
  a62=casadi_sq(a25);
  a65=(a65-a62);
  a43=(a43+a65);
  a43=(a01*a43);
  a11=(a11-a43);
  a43=(a25*a42);
  a65=(a18*a25);
  a43=(a43+a65);
  a43=(a66*a43);
  a42=(a19*a42);
  a65=(a25*a17);
  a42=(a42+a65);
  a65=(a18*a19);
  a62=(a17*a25);
  a65=(a65-a62);
  a42=(a42+a65);
  a42=(a46*a42);
  a43=(a43+a42);
  a11=(a11-a43);
  if (res[1]!=0) res[1][3]=a11;
  a20=(a17+a20);
  a20=(-a20);
  if (res[1]!=0) res[1][4]=a20;
  a20=(-a17);
  if (res[1]!=0) res[1][5]=a20;
  a02=(a02*a17);
  a01=(a01*a18);
  a02=(a02+a01);
  a66=(a66*a25);
  a46=(a46*a19);
  a66=(a66+a46);
  a02=(a02+a66);
  if (res[1]!=0) res[1][6]=a02;
  a17=(-a17);
  if (res[1]!=0) res[1][7]=a17;
  if (res[1]!=0) res[1][8]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int inverse_dynamics_hvp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int inverse_dynamics_hvp_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int inverse_dynamics_hvp_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void inverse_dynamics_hvp_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int inverse_dynamics_hvp_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void inverse_dynamics_hvp_release(int mem) {
}

CASADI_SYMBOL_EXPORT void inverse_dynamics_hvp_incref(void) {
}

CASADI_SYMBOL_EXPORT void inverse_dynamics_hvp_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int inverse_dynamics_hvp_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int inverse_dynamics_hvp_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real inverse_dynamics_hvp_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* inverse_dynamics_hvp_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* inverse_dynamics_hvp_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* inverse_dynamics_hvp_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* inverse_dynamics_hvp_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int inverse_dynamics_hvp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int inverse_dynamics_hvp_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
