/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_force_hTvp_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {6, 6, 1};
static const casadi_int casadi_s3[3] = {6, 3, 1};

/* kinematics_force_hTvp:(i0[6],i1[3],i2[3])->(o0[6x6],o1[6x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  if (res[0]!=0) res[0][3]=a00;
  if (res[0]!=0) res[0][4]=a00;
  if (res[0]!=0) res[0][5]=a00;
  if (res[0]!=0) res[0][6]=a00;
  a01=arg[1]? arg[1][1] : 0;
  a02=arg[0]? arg[0][2] : 0;
  a03=cos(a02);
  a04=arg[2]? arg[2][2] : 0;
  a03=(a03*a04);
  a05=(a01*a03);
  a06=arg[1]? arg[1][2] : 0;
  a07=sin(a02);
  a07=(a07*a04);
  a08=(a06*a07);
  a05=(a05+a08);
  a08=arg[0]? arg[0][1] : 0;
  a09=cos(a08);
  a05=(a05*a09);
  a07=(a01*a07);
  a03=(a06*a03);
  a07=(a07-a03);
  a03=sin(a08);
  a07=(a07*a03);
  a05=(a05-a07);
  a07=sin(a02);
  a03=(a07*a06);
  a09=cos(a02);
  a10=(a09*a01);
  a03=(a03+a10);
  a03=(a03+a01);
  a10=arg[2]? arg[2][1] : 0;
  a03=(a03*a10);
  a11=cos(a08);
  a03=(a03*a11);
  a05=(a05+a03);
  a03=(a09*a06);
  a03=(a06+a03);
  a11=(a07*a01);
  a03=(a03-a11);
  a03=(a03*a10);
  a11=sin(a08);
  a03=(a03*a11);
  a05=(a05+a03);
  if (res[0]!=0) res[0][7]=a05;
  a05=sin(a02);
  a03=cos(a08);
  a11=(a06*a03);
  a12=sin(a08);
  a13=(a01*a12);
  a11=(a11-a13);
  a11=(a04*a11);
  a05=(a05*a11);
  a11=cos(a02);
  a12=(a06*a12);
  a03=(a01*a03);
  a12=(a12+a03);
  a12=(a04*a12);
  a11=(a11*a12);
  a05=(a05+a11);
  a11=cos(a02);
  a12=cos(a08);
  a12=(a10*a12);
  a03=(a01*a12);
  a13=sin(a08);
  a13=(a10*a13);
  a14=(a06*a13);
  a03=(a03+a14);
  a11=(a11*a03);
  a05=(a05+a11);
  a11=sin(a02);
  a12=(a06*a12);
  a13=(a01*a13);
  a12=(a12-a13);
  a11=(a11*a12);
  a05=(a05+a11);
  if (res[0]!=0) res[0][8]=a05;
  if (res[0]!=0) res[0][9]=a00;
  if (res[0]!=0) res[0][10]=a00;
  if (res[0]!=0) res[0][11]=a00;
  if (res[0]!=0) res[0][12]=a00;
  a05=cos(a08);
  a11=cos(a02);
  a11=(a04*a11);
  a12=(a01*a11);
  a13=sin(a02);
  a13=(a04*a13);
  a03=(a06*a13);
  a12=(a12+a03);
  a05=(a05*a12);
  a12=sin(a08);
  a11=(a06*a11);
  a13=(a01*a13);
  a11=(a11-a13);
  a12=(a12*a11);
  a05=(a05+a12);
  a12=sin(a08);
  a11=cos(a02);
  a13=(a06*a11);
  a03=sin(a02);
  a14=(a01*a03);
  a13=(a13-a14);
  a13=(a10*a13);
  a12=(a12*a13);
  a05=(a05+a12);
  a12=cos(a08);
  a03=(a06*a03);
  a11=(a01*a11);
  a03=(a03+a11);
  a03=(a10*a03);
  a12=(a12*a03);
  a05=(a05+a12);
  if (res[0]!=0) res[0][13]=a05;
  a05=sin(a08);
  a12=(a05*a06);
  a03=cos(a08);
  a11=(a03*a01);
  a12=(a12+a11);
  a12=(a12*a04);
  a11=cos(a02);
  a12=(a12*a11);
  a11=(a03*a06);
  a13=(a05*a01);
  a11=(a11-a13);
  a11=(a11*a04);
  a13=sin(a02);
  a11=(a11*a13);
  a12=(a12+a11);
  a11=sin(a08);
  a11=(a11*a10);
  a13=(a01*a11);
  a14=cos(a08);
  a14=(a14*a10);
  a15=(a06*a14);
  a13=(a13-a15);
  a15=sin(a02);
  a13=(a13*a15);
  a12=(a12-a13);
  a01=(a01*a14);
  a06=(a06*a11);
  a01=(a01+a06);
  a06=cos(a02);
  a01=(a01*a06);
  a12=(a12+a01);
  if (res[0]!=0) res[0][14]=a12;
  if (res[0]!=0) res[0][15]=a00;
  if (res[0]!=0) res[0][16]=a00;
  if (res[0]!=0) res[0][17]=a00;
  if (res[0]!=0) res[0][18]=a00;
  if (res[0]!=0) res[0][19]=a00;
  if (res[0]!=0) res[0][20]=a00;
  if (res[0]!=0) res[0][21]=a00;
  if (res[0]!=0) res[0][22]=a00;
  if (res[0]!=0) res[0][23]=a00;
  if (res[0]!=0) res[0][24]=a00;
  if (res[0]!=0) res[0][25]=a00;
  if (res[0]!=0) res[0][26]=a00;
  if (res[0]!=0) res[0][27]=a00;
  if (res[0]!=0) res[0][28]=a00;
  if (res[0]!=0) res[0][29]=a00;
  if (res[0]!=0) res[0][30]=a00;
  if (res[0]!=0) res[0][31]=a00;
  if (res[0]!=0) res[0][32]=a00;
  if (res[0]!=0) res[0][33]=a00;
  if (res[0]!=0) res[0][34]=a00;
  if (res[0]!=0) res[0][35]=a00;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a00;
  if (res[1]!=0) res[1][3]=a00;
  if (res[1]!=0) res[1][4]=a00;
  if (res[1]!=0) res[1][5]=a00;
  if (res[1]!=0) res[1][6]=a00;
  a12=sin(a08);
  a12=(a10*a12);
  a01=cos(a02);
  a01=(a01*a04);
  a06=sin(a08);
  a11=(a01*a06);
  a14=cos(a08);
  a14=(a10*a14);
  a13=(a07*a14);
  a11=(a11+a13);
  a13=(a09*a12);
  a15=sin(a02);
  a15=(a15*a04);
  a16=cos(a08);
  a17=(a15*a16);
  a13=(a13+a17);
  a11=(a11+a13);
  a11=(a12+a11);
  if (res[1]!=0) res[1][7]=a11;
  a11=sin(a02);
  a11=(a04*a11);
  a13=(a03*a11);
  a17=sin(a08);
  a17=(a17*a10);
  a18=cos(a02);
  a19=(a17*a18);
  a13=(a13+a19);
  a08=cos(a08);
  a08=(a08*a10);
  a10=sin(a02);
  a19=(a08*a10);
  a02=cos(a02);
  a04=(a04*a02);
  a02=(a05*a04);
  a19=(a19+a02);
  a13=(a13+a19);
  if (res[1]!=0) res[1][8]=a13;
  if (res[1]!=0) res[1][9]=a00;
  if (res[1]!=0) res[1][10]=a00;
  if (res[1]!=0) res[1][11]=a00;
  if (res[1]!=0) res[1][12]=a00;
  a09=(a09*a14);
  a15=(a15*a06);
  a09=(a09-a15);
  a01=(a01*a16);
  a07=(a07*a12);
  a01=(a01-a07);
  a09=(a09+a01);
  a14=(a14+a09);
  a14=(-a14);
  if (res[1]!=0) res[1][13]=a14;
  a03=(a03*a04);
  a17=(a17*a10);
  a03=(a03-a17);
  a08=(a08*a18);
  a05=(a05*a11);
  a08=(a08-a05);
  a03=(a03+a08);
  a03=(-a03);
  if (res[1]!=0) res[1][14]=a03;
  if (res[1]!=0) res[1][15]=a00;
  if (res[1]!=0) res[1][16]=a00;
  if (res[1]!=0) res[1][17]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_force_hTvp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_force_hTvp_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_force_hTvp_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_force_hTvp_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_force_hTvp_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_force_hTvp_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_force_hTvp_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_force_hTvp_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_force_hTvp_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_force_hTvp_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_force_hTvp_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_force_hTvp_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_force_hTvp_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_force_hTvp_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_force_hTvp_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_force_hTvp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_force_hTvp_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
