name = "PinnZoo"
uuid = "d97c57dc-d26a-4eb6-834c-6dc76ba72308"
authors = ["Arun Bishop <arunleob@umich.edu>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
