/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamics_deriv_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};

/* dynamics_deriv:(i0[4],i1[2])->(o0[4x4],o1[4x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a1=-1.;
  a2=arg[0]? arg[0][1] : 0;
  a3=sin(a2);
  a4=casadi_sq(a3);
  a1=(a1-a4);
  a5=1.;
  a4=(a5+a4);
  a1=(a1/a4);
  a6=9.8100000000000005e+00;
  a7=arg[0]? arg[0][0] : 0;
  a8=cos(a7);
  a8=(a6*a8);
  a9=(a1*a8);
  a10=cos(a2);
  a11=(a3*a10);
  a11=(a11/a4);
  a12=sin(a7);
  a12=(a6*a12);
  a13=(a11*a12);
  a9=(a9-a13);
  a13=(-a9);
  if (res[0]!=0) res[0][2]=a13;
  a8=(a8+a9);
  a8=(a10*a8);
  a12=(a3*a12);
  a8=(a8-a12);
  a9=(a9+a8);
  if (res[0]!=0) res[0][3]=a9;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  a9=arg[0]? arg[0][3] : 0;
  a8=arg[0]? arg[0][2] : 0;
  a12=(a9+a8);
  a13=cos(a2);
  a14=(a8*a13);
  a15=(a12*a14);
  a16=(a10*a8);
  a17=(a16+a12);
  a18=(a17*a14);
  a19=(a3*a8);
  a2=sin(a2);
  a8=(a8*a2);
  a20=(a19*a8);
  a18=(a18-a20);
  a20=(a16*a14);
  a21=(a19*a8);
  a20=(a20-a21);
  a18=(a18-a20);
  a15=(a15-a18);
  a15=(a10*a15);
  a20=(a12*a19);
  a21=arg[1]? arg[1][1] : 0;
  a22=(a19*a17);
  a23=(a16*a19);
  a22=(a22-a23);
  a22=(a21-a22);
  a20=(a20+a22);
  a22=(a20*a2);
  a15=(a15-a22);
  a22=(a9*a16);
  a23=(a12*a17);
  a22=(a22-a23);
  a23=(a22*a13);
  a24=(a12*a8);
  a8=(a9*a8);
  a24=(a24-a8);
  a24=(a3*a24);
  a23=(a23+a24);
  a15=(a15+a23);
  a15=(a15/a4);
  a23=arg[1]? arg[1][0] : 0;
  a20=(a10*a20);
  a22=(a3*a22);
  a20=(a20+a22);
  a21=(a21+a20);
  a23=(a23-a21);
  a23=(a23/a4);
  a21=(a23/a4);
  a20=(a3+a3);
  a20=(a20*a13);
  a21=(a21*a20);
  a15=(a15+a21);
  a21=cos(a7);
  a21=(a6*a21);
  a22=casadi_sq(a10);
  a24=casadi_sq(a3);
  a22=(a22-a24);
  a22=(a22/a4);
  a24=(a11/a4);
  a24=(a24*a20);
  a22=(a22-a24);
  a22=(a21*a22);
  a7=sin(a7);
  a6=(a6*a7);
  a7=(a20/a4);
  a24=(a1/a4);
  a24=(a24*a20);
  a7=(a7+a24);
  a7=(a6*a7);
  a22=(a22-a7);
  a15=(a15+a22);
  a22=(-a15);
  if (res[0]!=0) res[0][6]=a22;
  a14=(a9*a14);
  a22=(a10*a15);
  a1=(a1*a6);
  a11=(a11*a21);
  a1=(a1+a11);
  a23=(a23-a1);
  a6=(a6-a23);
  a6=(a6*a2);
  a22=(a22-a6);
  a21=(a21*a13);
  a22=(a22+a21);
  a14=(a14+a22);
  a15=(a15+a14);
  a15=(a15-a18);
  if (res[0]!=0) res[0][7]=a15;
  if (res[0]!=0) res[0][8]=a5;
  if (res[0]!=0) res[0][9]=a0;
  a15=(a12*a3);
  a15=(a19+a15);
  a18=(a17*a3);
  a14=(a10+a5);
  a22=(a19*a14);
  a18=(a18+a22);
  a22=(a19*a10);
  a21=(a16*a3);
  a22=(a22+a21);
  a18=(a18-a22);
  a15=(a15-a18);
  a15=(a10*a15);
  a22=(a9*a10);
  a14=(a12*a14);
  a14=(a17+a14);
  a22=(a22-a14);
  a22=(a3*a22);
  a15=(a15+a22);
  a15=(a15/a4);
  a22=(-a15);
  if (res[0]!=0) res[0][10]=a22;
  a9=(a9*a3);
  a22=(a10*a15);
  a9=(a9+a22);
  a15=(a15+a9);
  a15=(a15-a18);
  if (res[0]!=0) res[0][11]=a15;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a5;
  a17=(a17+a12);
  a16=(a16-a17);
  a3=(a3*a16);
  a3=(a3/a4);
  a16=(-a3);
  if (res[0]!=0) res[0][14]=a16;
  a16=(a10*a3);
  a16=(a19+a16);
  a3=(a3+a16);
  a3=(a3-a19);
  if (res[0]!=0) res[0][15]=a3;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  a3=(1./a4);
  if (res[1]!=0) res[1][2]=a3;
  a19=(a10/a4);
  a3=(a3+a19);
  a3=(-a3);
  if (res[1]!=0) res[1][3]=a3;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a0;
  a0=(a5+a10);
  a0=(a0/a4);
  a4=(-a0);
  if (res[1]!=0) res[1][6]=a4;
  a10=(a10*a0);
  a0=(a0+a10);
  a5=(a5+a0);
  if (res[1]!=0) res[1][7]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_deriv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dynamics_deriv_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_deriv_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_deriv_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dynamics_deriv_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dynamics_deriv_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dynamics_deriv_incref(void) {
}

CASADI_SYMBOL_EXPORT void dynamics_deriv_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dynamics_deriv_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int dynamics_deriv_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real dynamics_deriv_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_deriv_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dynamics_deriv_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_deriv_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dynamics_deriv_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dynamics_deriv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int dynamics_deriv_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
