/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_velocity_jacobian_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[19] = {3, 4, 0, 3, 6, 9, 12, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* kinematics_velocity_jacobian:(i0[4])->(o0[3x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[0]? arg[0][0] : 0;
  a3=sin(a2);
  a3=(a1*a3);
  a4=arg[0]? arg[0][1] : 0;
  a5=cos(a4);
  a6=arg[0]? arg[0][3] : 0;
  a7=(a5*a6);
  a8=sin(a2);
  a9=(a7*a8);
  a10=sin(a4);
  a11=cos(a2);
  a11=(a1*a11);
  a12=(a10*a11);
  a9=(a9+a12);
  a12=cos(a4);
  a13=(a12*a3);
  a14=sin(a4);
  a15=(a14*a6);
  a16=cos(a2);
  a17=(a15*a16);
  a13=(a13+a17);
  a9=(a9+a13);
  a9=(a3+a9);
  if (res[0]!=0) res[0][1]=a9;
  a9=(a12*a11);
  a15=(a15*a8);
  a9=(a9-a15);
  a7=(a7*a16);
  a3=(a10*a3);
  a7=(a7-a3);
  a9=(a9+a7);
  a11=(a11+a9);
  a11=(-a11);
  if (res[0]!=0) res[0][2]=a11;
  if (res[0]!=0) res[0][3]=a0;
  a11=cos(a2);
  a9=sin(a4);
  a9=(a6*a9);
  a7=(a11*a9);
  a3=sin(a2);
  a16=(a3*a1);
  a15=cos(a4);
  a8=(a16*a15);
  a7=(a7+a8);
  a8=cos(a2);
  a1=(a8*a1);
  a13=sin(a4);
  a17=(a1*a13);
  a2=sin(a2);
  a4=cos(a4);
  a6=(a6*a4);
  a4=(a2*a6);
  a17=(a17+a4);
  a7=(a7+a17);
  if (res[0]!=0) res[0][4]=a7;
  a6=(a11*a6);
  a16=(a16*a13);
  a6=(a6-a16);
  a1=(a1*a15);
  a9=(a2*a9);
  a1=(a1-a9);
  a6=(a6+a1);
  a6=(-a6);
  if (res[0]!=0) res[0][5]=a6;
  if (res[0]!=0) res[0][6]=a0;
  a6=(a12*a8);
  a1=(a10*a3);
  a6=(a6-a1);
  a6=(a8+a6);
  a6=(-a6);
  if (res[0]!=0) res[0][7]=a6;
  a12=(a12*a3);
  a10=(a10*a8);
  a12=(a12+a10);
  a3=(a3+a12);
  a3=(-a3);
  if (res[0]!=0) res[0][8]=a3;
  if (res[0]!=0) res[0][9]=a0;
  a0=(a11*a5);
  a3=(a2*a14);
  a0=(a0-a3);
  a0=(-a0);
  if (res[0]!=0) res[0][10]=a0;
  a11=(a11*a14);
  a2=(a2*a5);
  a11=(a11+a2);
  a11=(-a11);
  if (res[0]!=0) res[0][11]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_jacobian(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_jacobian_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_jacobian_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_jacobian_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_jacobian_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_jacobian_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_jacobian_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_jacobian_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_velocity_jacobian_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_velocity_jacobian_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_velocity_jacobian_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_velocity_jacobian_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_velocity_jacobian_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_velocity_jacobian_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_velocity_jacobian_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_jacobian_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_jacobian_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
