/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) velocity_kinematics_T_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[33] = {29, 1, 0, 29, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28};
static const casadi_int casadi_s1[228] = {14, 15, 0, 14, 28, 42, 56, 70, 84, 98, 112, 126, 140, 154, 168, 182, 196, 210, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};

/* velocity_kinematics_T:(i0[29])->(o0[14x15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=1.;
  a1=2.;
  a2=arg[0]? arg[0][6] : 0;
  a3=(a1*a2);
  a4=(a3*a2);
  a5=arg[0]? arg[0][5] : 0;
  a6=(a1*a5);
  a7=(a6*a5);
  a4=(a4+a7);
  a4=(a0-a4);
  if (res[0]!=0) res[0][0]=a4;
  a4=arg[0]? arg[0][4] : 0;
  a6=(a6*a4);
  a7=arg[0]? arg[0][3] : 0;
  a8=(a1*a7);
  a9=(a8*a2);
  a6=(a6-a9);
  if (res[0]!=0) res[0][1]=a6;
  a6=(a8*a5);
  a3=(a3*a4);
  a6=(a6+a3);
  if (res[0]!=0) res[0][2]=a6;
  a6=0.;
  if (res[0]!=0) res[0][3]=a6;
  if (res[0]!=0) res[0][4]=a6;
  if (res[0]!=0) res[0][5]=a6;
  if (res[0]!=0) res[0][6]=a6;
  if (res[0]!=0) res[0][7]=a6;
  if (res[0]!=0) res[0][8]=a6;
  if (res[0]!=0) res[0][9]=a6;
  if (res[0]!=0) res[0][10]=a6;
  if (res[0]!=0) res[0][11]=a6;
  if (res[0]!=0) res[0][12]=a6;
  if (res[0]!=0) res[0][13]=a6;
  a3=(a8*a2);
  a9=(a1*a4);
  a10=(a9*a5);
  a3=(a3+a10);
  if (res[0]!=0) res[0][14]=a3;
  a3=(a1*a2);
  a10=(a3*a2);
  a9=(a9*a4);
  a10=(a10+a9);
  a10=(a0-a10);
  if (res[0]!=0) res[0][15]=a10;
  a3=(a3*a5);
  a10=(a8*a4);
  a3=(a3-a10);
  if (res[0]!=0) res[0][16]=a3;
  if (res[0]!=0) res[0][17]=a6;
  if (res[0]!=0) res[0][18]=a6;
  if (res[0]!=0) res[0][19]=a6;
  if (res[0]!=0) res[0][20]=a6;
  if (res[0]!=0) res[0][21]=a6;
  if (res[0]!=0) res[0][22]=a6;
  if (res[0]!=0) res[0][23]=a6;
  if (res[0]!=0) res[0][24]=a6;
  if (res[0]!=0) res[0][25]=a6;
  if (res[0]!=0) res[0][26]=a6;
  if (res[0]!=0) res[0][27]=a6;
  a3=(a1*a4);
  a10=(a3*a2);
  a9=(a8*a5);
  a10=(a10-a9);
  if (res[0]!=0) res[0][28]=a10;
  a8=(a8*a4);
  a10=(a1*a5);
  a9=(a10*a2);
  a8=(a8+a9);
  if (res[0]!=0) res[0][29]=a8;
  a10=(a10*a5);
  a3=(a3*a4);
  a10=(a10+a3);
  a10=(a0-a10);
  if (res[0]!=0) res[0][30]=a10;
  if (res[0]!=0) res[0][31]=a6;
  if (res[0]!=0) res[0][32]=a6;
  if (res[0]!=0) res[0][33]=a6;
  if (res[0]!=0) res[0][34]=a6;
  if (res[0]!=0) res[0][35]=a6;
  if (res[0]!=0) res[0][36]=a6;
  if (res[0]!=0) res[0][37]=a6;
  if (res[0]!=0) res[0][38]=a6;
  if (res[0]!=0) res[0][39]=a6;
  if (res[0]!=0) res[0][40]=a6;
  if (res[0]!=0) res[0][41]=a6;
  if (res[0]!=0) res[0][42]=a6;
  if (res[0]!=0) res[0][43]=a6;
  if (res[0]!=0) res[0][44]=a6;
  a10=(a1*a4);
  a10=(-a10);
  if (res[0]!=0) res[0][45]=a10;
  a10=(a1*a5);
  a10=(-a10);
  if (res[0]!=0) res[0][46]=a10;
  a10=(a1*a2);
  a10=(-a10);
  if (res[0]!=0) res[0][47]=a10;
  if (res[0]!=0) res[0][48]=a6;
  if (res[0]!=0) res[0][49]=a6;
  if (res[0]!=0) res[0][50]=a6;
  if (res[0]!=0) res[0][51]=a6;
  if (res[0]!=0) res[0][52]=a6;
  if (res[0]!=0) res[0][53]=a6;
  if (res[0]!=0) res[0][54]=a6;
  if (res[0]!=0) res[0][55]=a6;
  if (res[0]!=0) res[0][56]=a6;
  if (res[0]!=0) res[0][57]=a6;
  if (res[0]!=0) res[0][58]=a6;
  a10=(a1*a7);
  if (res[0]!=0) res[0][59]=a10;
  a10=(a1*a2);
  a10=(-a10);
  if (res[0]!=0) res[0][60]=a10;
  a10=(a1*a5);
  if (res[0]!=0) res[0][61]=a10;
  if (res[0]!=0) res[0][62]=a6;
  if (res[0]!=0) res[0][63]=a6;
  if (res[0]!=0) res[0][64]=a6;
  if (res[0]!=0) res[0][65]=a6;
  if (res[0]!=0) res[0][66]=a6;
  if (res[0]!=0) res[0][67]=a6;
  if (res[0]!=0) res[0][68]=a6;
  if (res[0]!=0) res[0][69]=a6;
  if (res[0]!=0) res[0][70]=a6;
  if (res[0]!=0) res[0][71]=a6;
  if (res[0]!=0) res[0][72]=a6;
  a2=(a1*a2);
  if (res[0]!=0) res[0][73]=a2;
  a2=(a1*a7);
  if (res[0]!=0) res[0][74]=a2;
  a2=(a1*a4);
  a2=(-a2);
  if (res[0]!=0) res[0][75]=a2;
  if (res[0]!=0) res[0][76]=a6;
  if (res[0]!=0) res[0][77]=a6;
  if (res[0]!=0) res[0][78]=a6;
  if (res[0]!=0) res[0][79]=a6;
  if (res[0]!=0) res[0][80]=a6;
  if (res[0]!=0) res[0][81]=a6;
  if (res[0]!=0) res[0][82]=a6;
  if (res[0]!=0) res[0][83]=a6;
  if (res[0]!=0) res[0][84]=a6;
  if (res[0]!=0) res[0][85]=a6;
  if (res[0]!=0) res[0][86]=a6;
  a5=(a1*a5);
  a5=(-a5);
  if (res[0]!=0) res[0][87]=a5;
  a4=(a1*a4);
  if (res[0]!=0) res[0][88]=a4;
  a1=(a1*a7);
  if (res[0]!=0) res[0][89]=a1;
  if (res[0]!=0) res[0][90]=a6;
  if (res[0]!=0) res[0][91]=a6;
  if (res[0]!=0) res[0][92]=a6;
  if (res[0]!=0) res[0][93]=a6;
  if (res[0]!=0) res[0][94]=a6;
  if (res[0]!=0) res[0][95]=a6;
  if (res[0]!=0) res[0][96]=a6;
  if (res[0]!=0) res[0][97]=a6;
  if (res[0]!=0) res[0][98]=a6;
  if (res[0]!=0) res[0][99]=a6;
  if (res[0]!=0) res[0][100]=a6;
  if (res[0]!=0) res[0][101]=a6;
  if (res[0]!=0) res[0][102]=a6;
  if (res[0]!=0) res[0][103]=a6;
  if (res[0]!=0) res[0][104]=a0;
  if (res[0]!=0) res[0][105]=a6;
  if (res[0]!=0) res[0][106]=a6;
  if (res[0]!=0) res[0][107]=a6;
  if (res[0]!=0) res[0][108]=a6;
  if (res[0]!=0) res[0][109]=a6;
  if (res[0]!=0) res[0][110]=a6;
  if (res[0]!=0) res[0][111]=a6;
  if (res[0]!=0) res[0][112]=a6;
  if (res[0]!=0) res[0][113]=a6;
  if (res[0]!=0) res[0][114]=a6;
  if (res[0]!=0) res[0][115]=a6;
  if (res[0]!=0) res[0][116]=a6;
  if (res[0]!=0) res[0][117]=a6;
  if (res[0]!=0) res[0][118]=a6;
  if (res[0]!=0) res[0][119]=a0;
  if (res[0]!=0) res[0][120]=a6;
  if (res[0]!=0) res[0][121]=a6;
  if (res[0]!=0) res[0][122]=a6;
  if (res[0]!=0) res[0][123]=a6;
  if (res[0]!=0) res[0][124]=a6;
  if (res[0]!=0) res[0][125]=a6;
  if (res[0]!=0) res[0][126]=a6;
  if (res[0]!=0) res[0][127]=a6;
  if (res[0]!=0) res[0][128]=a6;
  if (res[0]!=0) res[0][129]=a6;
  if (res[0]!=0) res[0][130]=a6;
  if (res[0]!=0) res[0][131]=a6;
  if (res[0]!=0) res[0][132]=a6;
  if (res[0]!=0) res[0][133]=a6;
  if (res[0]!=0) res[0][134]=a0;
  if (res[0]!=0) res[0][135]=a6;
  if (res[0]!=0) res[0][136]=a6;
  if (res[0]!=0) res[0][137]=a6;
  if (res[0]!=0) res[0][138]=a6;
  if (res[0]!=0) res[0][139]=a6;
  if (res[0]!=0) res[0][140]=a6;
  if (res[0]!=0) res[0][141]=a6;
  if (res[0]!=0) res[0][142]=a6;
  if (res[0]!=0) res[0][143]=a6;
  if (res[0]!=0) res[0][144]=a6;
  if (res[0]!=0) res[0][145]=a6;
  if (res[0]!=0) res[0][146]=a6;
  if (res[0]!=0) res[0][147]=a6;
  if (res[0]!=0) res[0][148]=a6;
  if (res[0]!=0) res[0][149]=a0;
  if (res[0]!=0) res[0][150]=a6;
  if (res[0]!=0) res[0][151]=a6;
  if (res[0]!=0) res[0][152]=a6;
  if (res[0]!=0) res[0][153]=a6;
  if (res[0]!=0) res[0][154]=a6;
  if (res[0]!=0) res[0][155]=a6;
  if (res[0]!=0) res[0][156]=a6;
  if (res[0]!=0) res[0][157]=a6;
  if (res[0]!=0) res[0][158]=a6;
  if (res[0]!=0) res[0][159]=a6;
  if (res[0]!=0) res[0][160]=a6;
  if (res[0]!=0) res[0][161]=a6;
  if (res[0]!=0) res[0][162]=a6;
  if (res[0]!=0) res[0][163]=a6;
  if (res[0]!=0) res[0][164]=a0;
  if (res[0]!=0) res[0][165]=a6;
  if (res[0]!=0) res[0][166]=a6;
  if (res[0]!=0) res[0][167]=a6;
  if (res[0]!=0) res[0][168]=a6;
  if (res[0]!=0) res[0][169]=a6;
  if (res[0]!=0) res[0][170]=a6;
  if (res[0]!=0) res[0][171]=a6;
  if (res[0]!=0) res[0][172]=a6;
  if (res[0]!=0) res[0][173]=a6;
  if (res[0]!=0) res[0][174]=a6;
  if (res[0]!=0) res[0][175]=a6;
  if (res[0]!=0) res[0][176]=a6;
  if (res[0]!=0) res[0][177]=a6;
  if (res[0]!=0) res[0][178]=a6;
  if (res[0]!=0) res[0][179]=a0;
  if (res[0]!=0) res[0][180]=a6;
  if (res[0]!=0) res[0][181]=a6;
  if (res[0]!=0) res[0][182]=a6;
  if (res[0]!=0) res[0][183]=a6;
  if (res[0]!=0) res[0][184]=a6;
  if (res[0]!=0) res[0][185]=a6;
  if (res[0]!=0) res[0][186]=a6;
  if (res[0]!=0) res[0][187]=a6;
  if (res[0]!=0) res[0][188]=a6;
  if (res[0]!=0) res[0][189]=a6;
  if (res[0]!=0) res[0][190]=a6;
  if (res[0]!=0) res[0][191]=a6;
  if (res[0]!=0) res[0][192]=a6;
  if (res[0]!=0) res[0][193]=a6;
  if (res[0]!=0) res[0][194]=a0;
  if (res[0]!=0) res[0][195]=a6;
  if (res[0]!=0) res[0][196]=a6;
  if (res[0]!=0) res[0][197]=a6;
  if (res[0]!=0) res[0][198]=a6;
  if (res[0]!=0) res[0][199]=a6;
  if (res[0]!=0) res[0][200]=a6;
  if (res[0]!=0) res[0][201]=a6;
  if (res[0]!=0) res[0][202]=a6;
  if (res[0]!=0) res[0][203]=a6;
  if (res[0]!=0) res[0][204]=a6;
  if (res[0]!=0) res[0][205]=a6;
  if (res[0]!=0) res[0][206]=a6;
  if (res[0]!=0) res[0][207]=a6;
  if (res[0]!=0) res[0][208]=a6;
  if (res[0]!=0) res[0][209]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_release(int mem) {
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_incref(void) {
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int velocity_kinematics_T_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int velocity_kinematics_T_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real velocity_kinematics_T_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* velocity_kinematics_T_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* velocity_kinematics_T_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* velocity_kinematics_T_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* velocity_kinematics_T_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
