/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) velocity_kinematics_jvp_deriv_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {25, 1, 1};
static const casadi_int casadi_s1[3] = {12, 1, 1};
static const casadi_int casadi_s2[3] = {13, 25, 1};

/* velocity_kinematics_jvp_deriv:(i0[25],i1[12])->(o0[13x25]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  if (res[0]!=0) res[0][3]=a00;
  if (res[0]!=0) res[0][4]=a00;
  if (res[0]!=0) res[0][5]=a00;
  if (res[0]!=0) res[0][6]=a00;
  if (res[0]!=0) res[0][7]=a00;
  if (res[0]!=0) res[0][8]=a00;
  if (res[0]!=0) res[0][9]=a00;
  if (res[0]!=0) res[0][10]=a00;
  if (res[0]!=0) res[0][11]=a00;
  if (res[0]!=0) res[0][12]=a00;
  if (res[0]!=0) res[0][13]=a00;
  if (res[0]!=0) res[0][14]=a00;
  if (res[0]!=0) res[0][15]=a00;
  if (res[0]!=0) res[0][16]=a00;
  if (res[0]!=0) res[0][17]=a00;
  if (res[0]!=0) res[0][18]=a00;
  if (res[0]!=0) res[0][19]=a00;
  if (res[0]!=0) res[0][20]=a00;
  if (res[0]!=0) res[0][21]=a00;
  if (res[0]!=0) res[0][22]=a00;
  if (res[0]!=0) res[0][23]=a00;
  if (res[0]!=0) res[0][24]=a00;
  if (res[0]!=0) res[0][25]=a00;
  if (res[0]!=0) res[0][26]=a00;
  if (res[0]!=0) res[0][27]=a00;
  if (res[0]!=0) res[0][28]=a00;
  if (res[0]!=0) res[0][29]=a00;
  if (res[0]!=0) res[0][30]=a00;
  if (res[0]!=0) res[0][31]=a00;
  if (res[0]!=0) res[0][32]=a00;
  if (res[0]!=0) res[0][33]=a00;
  if (res[0]!=0) res[0][34]=a00;
  if (res[0]!=0) res[0][35]=a00;
  if (res[0]!=0) res[0][36]=a00;
  if (res[0]!=0) res[0][37]=a00;
  if (res[0]!=0) res[0][38]=a00;
  a01=arg[1]? arg[1][2] : 0;
  a02=2.;
  a03=arg[0]? arg[0][5] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a05=arg[1]? arg[1][1] : 0;
  a06=arg[0]? arg[0][6] : 0;
  a07=(a02*a06);
  a07=(a05*a07);
  a04=(a04-a07);
  if (res[0]!=0) res[0][39]=a04;
  a04=arg[1]? arg[1][0] : 0;
  a07=(a02*a06);
  a07=(a04*a07);
  a08=arg[0]? arg[0][4] : 0;
  a09=(a02*a08);
  a09=(a01*a09);
  a07=(a07-a09);
  if (res[0]!=0) res[0][40]=a07;
  a07=(a02*a08);
  a07=(a05*a07);
  a09=(a02*a03);
  a09=(a04*a09);
  a07=(a07-a09);
  if (res[0]!=0) res[0][41]=a07;
  if (res[0]!=0) res[0][42]=a00;
  a07=5.0000000000000000e-01;
  a09=arg[1]? arg[1][3] : 0;
  a10=(a07*a09);
  if (res[0]!=0) res[0][43]=a10;
  a10=arg[1]? arg[1][4] : 0;
  a11=(a07*a10);
  if (res[0]!=0) res[0][44]=a11;
  a11=arg[1]? arg[1][5] : 0;
  a12=(a07*a11);
  if (res[0]!=0) res[0][45]=a12;
  if (res[0]!=0) res[0][46]=a00;
  if (res[0]!=0) res[0][47]=a00;
  if (res[0]!=0) res[0][48]=a00;
  if (res[0]!=0) res[0][49]=a00;
  if (res[0]!=0) res[0][50]=a00;
  if (res[0]!=0) res[0][51]=a00;
  a12=(a02*a03);
  a13=(a05*a12);
  a14=(a02*a06);
  a15=(a01*a14);
  a13=(a13+a15);
  if (res[0]!=0) res[0][52]=a13;
  a13=(a02*a03);
  a13=(a04*a13);
  a15=(a02*a08);
  a16=(a02*a08);
  a15=(a15+a16);
  a15=(a05*a15);
  a13=(a13-a15);
  a15=arg[0]? arg[0][3] : 0;
  a15=(a02*a15);
  a17=(a01*a15);
  a13=(a13-a17);
  if (res[0]!=0) res[0][53]=a13;
  a13=(a02*a06);
  a13=(a04*a13);
  a17=(a05*a15);
  a13=(a13+a17);
  a17=(a02*a08);
  a18=(a02*a08);
  a17=(a17+a18);
  a17=(a01*a17);
  a13=(a13-a17);
  if (res[0]!=0) res[0][54]=a13;
  a13=(a07*a09);
  a13=(-a13);
  if (res[0]!=0) res[0][55]=a13;
  if (res[0]!=0) res[0][56]=a00;
  a13=(a07*a11);
  a13=(-a13);
  if (res[0]!=0) res[0][57]=a13;
  a13=(a07*a10);
  if (res[0]!=0) res[0][58]=a13;
  if (res[0]!=0) res[0][59]=a00;
  if (res[0]!=0) res[0][60]=a00;
  if (res[0]!=0) res[0][61]=a00;
  if (res[0]!=0) res[0][62]=a00;
  if (res[0]!=0) res[0][63]=a00;
  if (res[0]!=0) res[0][64]=a00;
  a13=(a02*a08);
  a13=(a05*a13);
  a17=(a02*a03);
  a17=(a17+a12);
  a17=(a04*a17);
  a13=(a13-a17);
  a17=(a01*a15);
  a13=(a13+a17);
  if (res[0]!=0) res[0][65]=a13;
  a16=(a04*a16);
  a13=(a02*a06);
  a17=(a01*a13);
  a16=(a16+a17);
  if (res[0]!=0) res[0][66]=a16;
  a16=(a02*a06);
  a16=(a05*a16);
  a17=(a04*a15);
  a16=(a16-a17);
  a17=(a02*a03);
  a12=(a02*a03);
  a17=(a17+a12);
  a17=(a01*a17);
  a16=(a16-a17);
  if (res[0]!=0) res[0][67]=a16;
  a16=(a07*a10);
  a16=(-a16);
  if (res[0]!=0) res[0][68]=a16;
  a16=(a07*a11);
  if (res[0]!=0) res[0][69]=a16;
  if (res[0]!=0) res[0][70]=a00;
  a16=(a07*a09);
  a16=(-a16);
  if (res[0]!=0) res[0][71]=a16;
  if (res[0]!=0) res[0][72]=a00;
  if (res[0]!=0) res[0][73]=a00;
  if (res[0]!=0) res[0][74]=a00;
  if (res[0]!=0) res[0][75]=a00;
  if (res[0]!=0) res[0][76]=a00;
  if (res[0]!=0) res[0][77]=a00;
  a08=(a02*a08);
  a08=(a01*a08);
  a16=(a02*a06);
  a16=(a16+a14);
  a16=(a04*a16);
  a14=(a05*a15);
  a16=(a16+a14);
  a08=(a08-a16);
  if (res[0]!=0) res[0][78]=a08;
  a15=(a04*a15);
  a06=(a02*a06);
  a06=(a06+a13);
  a06=(a05*a06);
  a15=(a15-a06);
  a02=(a02*a03);
  a01=(a01*a02);
  a15=(a15+a01);
  if (res[0]!=0) res[0][79]=a15;
  a04=(a04*a18);
  a05=(a05*a12);
  a04=(a04+a05);
  if (res[0]!=0) res[0][80]=a04;
  a11=(a07*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][81]=a11;
  a10=(a07*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][82]=a10;
  a07=(a07*a09);
  if (res[0]!=0) res[0][83]=a07;
  if (res[0]!=0) res[0][84]=a00;
  if (res[0]!=0) res[0][85]=a00;
  if (res[0]!=0) res[0][86]=a00;
  if (res[0]!=0) res[0][87]=a00;
  if (res[0]!=0) res[0][88]=a00;
  if (res[0]!=0) res[0][89]=a00;
  if (res[0]!=0) res[0][90]=a00;
  if (res[0]!=0) res[0][91]=a00;
  if (res[0]!=0) res[0][92]=a00;
  if (res[0]!=0) res[0][93]=a00;
  if (res[0]!=0) res[0][94]=a00;
  if (res[0]!=0) res[0][95]=a00;
  if (res[0]!=0) res[0][96]=a00;
  if (res[0]!=0) res[0][97]=a00;
  if (res[0]!=0) res[0][98]=a00;
  if (res[0]!=0) res[0][99]=a00;
  if (res[0]!=0) res[0][100]=a00;
  if (res[0]!=0) res[0][101]=a00;
  if (res[0]!=0) res[0][102]=a00;
  if (res[0]!=0) res[0][103]=a00;
  if (res[0]!=0) res[0][104]=a00;
  if (res[0]!=0) res[0][105]=a00;
  if (res[0]!=0) res[0][106]=a00;
  if (res[0]!=0) res[0][107]=a00;
  if (res[0]!=0) res[0][108]=a00;
  if (res[0]!=0) res[0][109]=a00;
  if (res[0]!=0) res[0][110]=a00;
  if (res[0]!=0) res[0][111]=a00;
  if (res[0]!=0) res[0][112]=a00;
  if (res[0]!=0) res[0][113]=a00;
  if (res[0]!=0) res[0][114]=a00;
  if (res[0]!=0) res[0][115]=a00;
  if (res[0]!=0) res[0][116]=a00;
  if (res[0]!=0) res[0][117]=a00;
  if (res[0]!=0) res[0][118]=a00;
  if (res[0]!=0) res[0][119]=a00;
  if (res[0]!=0) res[0][120]=a00;
  if (res[0]!=0) res[0][121]=a00;
  if (res[0]!=0) res[0][122]=a00;
  if (res[0]!=0) res[0][123]=a00;
  if (res[0]!=0) res[0][124]=a00;
  if (res[0]!=0) res[0][125]=a00;
  if (res[0]!=0) res[0][126]=a00;
  if (res[0]!=0) res[0][127]=a00;
  if (res[0]!=0) res[0][128]=a00;
  if (res[0]!=0) res[0][129]=a00;
  if (res[0]!=0) res[0][130]=a00;
  if (res[0]!=0) res[0][131]=a00;
  if (res[0]!=0) res[0][132]=a00;
  if (res[0]!=0) res[0][133]=a00;
  if (res[0]!=0) res[0][134]=a00;
  if (res[0]!=0) res[0][135]=a00;
  if (res[0]!=0) res[0][136]=a00;
  if (res[0]!=0) res[0][137]=a00;
  if (res[0]!=0) res[0][138]=a00;
  if (res[0]!=0) res[0][139]=a00;
  if (res[0]!=0) res[0][140]=a00;
  if (res[0]!=0) res[0][141]=a00;
  if (res[0]!=0) res[0][142]=a00;
  if (res[0]!=0) res[0][143]=a00;
  if (res[0]!=0) res[0][144]=a00;
  if (res[0]!=0) res[0][145]=a00;
  if (res[0]!=0) res[0][146]=a00;
  if (res[0]!=0) res[0][147]=a00;
  if (res[0]!=0) res[0][148]=a00;
  if (res[0]!=0) res[0][149]=a00;
  if (res[0]!=0) res[0][150]=a00;
  if (res[0]!=0) res[0][151]=a00;
  if (res[0]!=0) res[0][152]=a00;
  if (res[0]!=0) res[0][153]=a00;
  if (res[0]!=0) res[0][154]=a00;
  if (res[0]!=0) res[0][155]=a00;
  if (res[0]!=0) res[0][156]=a00;
  if (res[0]!=0) res[0][157]=a00;
  if (res[0]!=0) res[0][158]=a00;
  if (res[0]!=0) res[0][159]=a00;
  if (res[0]!=0) res[0][160]=a00;
  if (res[0]!=0) res[0][161]=a00;
  if (res[0]!=0) res[0][162]=a00;
  if (res[0]!=0) res[0][163]=a00;
  if (res[0]!=0) res[0][164]=a00;
  if (res[0]!=0) res[0][165]=a00;
  if (res[0]!=0) res[0][166]=a00;
  if (res[0]!=0) res[0][167]=a00;
  if (res[0]!=0) res[0][168]=a00;
  if (res[0]!=0) res[0][169]=a00;
  if (res[0]!=0) res[0][170]=a00;
  if (res[0]!=0) res[0][171]=a00;
  if (res[0]!=0) res[0][172]=a00;
  if (res[0]!=0) res[0][173]=a00;
  if (res[0]!=0) res[0][174]=a00;
  if (res[0]!=0) res[0][175]=a00;
  if (res[0]!=0) res[0][176]=a00;
  if (res[0]!=0) res[0][177]=a00;
  if (res[0]!=0) res[0][178]=a00;
  if (res[0]!=0) res[0][179]=a00;
  if (res[0]!=0) res[0][180]=a00;
  if (res[0]!=0) res[0][181]=a00;
  if (res[0]!=0) res[0][182]=a00;
  if (res[0]!=0) res[0][183]=a00;
  if (res[0]!=0) res[0][184]=a00;
  if (res[0]!=0) res[0][185]=a00;
  if (res[0]!=0) res[0][186]=a00;
  if (res[0]!=0) res[0][187]=a00;
  if (res[0]!=0) res[0][188]=a00;
  if (res[0]!=0) res[0][189]=a00;
  if (res[0]!=0) res[0][190]=a00;
  if (res[0]!=0) res[0][191]=a00;
  if (res[0]!=0) res[0][192]=a00;
  if (res[0]!=0) res[0][193]=a00;
  if (res[0]!=0) res[0][194]=a00;
  if (res[0]!=0) res[0][195]=a00;
  if (res[0]!=0) res[0][196]=a00;
  if (res[0]!=0) res[0][197]=a00;
  if (res[0]!=0) res[0][198]=a00;
  if (res[0]!=0) res[0][199]=a00;
  if (res[0]!=0) res[0][200]=a00;
  if (res[0]!=0) res[0][201]=a00;
  if (res[0]!=0) res[0][202]=a00;
  if (res[0]!=0) res[0][203]=a00;
  if (res[0]!=0) res[0][204]=a00;
  if (res[0]!=0) res[0][205]=a00;
  if (res[0]!=0) res[0][206]=a00;
  if (res[0]!=0) res[0][207]=a00;
  if (res[0]!=0) res[0][208]=a00;
  if (res[0]!=0) res[0][209]=a00;
  if (res[0]!=0) res[0][210]=a00;
  if (res[0]!=0) res[0][211]=a00;
  if (res[0]!=0) res[0][212]=a00;
  if (res[0]!=0) res[0][213]=a00;
  if (res[0]!=0) res[0][214]=a00;
  if (res[0]!=0) res[0][215]=a00;
  if (res[0]!=0) res[0][216]=a00;
  if (res[0]!=0) res[0][217]=a00;
  if (res[0]!=0) res[0][218]=a00;
  if (res[0]!=0) res[0][219]=a00;
  if (res[0]!=0) res[0][220]=a00;
  if (res[0]!=0) res[0][221]=a00;
  if (res[0]!=0) res[0][222]=a00;
  if (res[0]!=0) res[0][223]=a00;
  if (res[0]!=0) res[0][224]=a00;
  if (res[0]!=0) res[0][225]=a00;
  if (res[0]!=0) res[0][226]=a00;
  if (res[0]!=0) res[0][227]=a00;
  if (res[0]!=0) res[0][228]=a00;
  if (res[0]!=0) res[0][229]=a00;
  if (res[0]!=0) res[0][230]=a00;
  if (res[0]!=0) res[0][231]=a00;
  if (res[0]!=0) res[0][232]=a00;
  if (res[0]!=0) res[0][233]=a00;
  if (res[0]!=0) res[0][234]=a00;
  if (res[0]!=0) res[0][235]=a00;
  if (res[0]!=0) res[0][236]=a00;
  if (res[0]!=0) res[0][237]=a00;
  if (res[0]!=0) res[0][238]=a00;
  if (res[0]!=0) res[0][239]=a00;
  if (res[0]!=0) res[0][240]=a00;
  if (res[0]!=0) res[0][241]=a00;
  if (res[0]!=0) res[0][242]=a00;
  if (res[0]!=0) res[0][243]=a00;
  if (res[0]!=0) res[0][244]=a00;
  if (res[0]!=0) res[0][245]=a00;
  if (res[0]!=0) res[0][246]=a00;
  if (res[0]!=0) res[0][247]=a00;
  if (res[0]!=0) res[0][248]=a00;
  if (res[0]!=0) res[0][249]=a00;
  if (res[0]!=0) res[0][250]=a00;
  if (res[0]!=0) res[0][251]=a00;
  if (res[0]!=0) res[0][252]=a00;
  if (res[0]!=0) res[0][253]=a00;
  if (res[0]!=0) res[0][254]=a00;
  if (res[0]!=0) res[0][255]=a00;
  if (res[0]!=0) res[0][256]=a00;
  if (res[0]!=0) res[0][257]=a00;
  if (res[0]!=0) res[0][258]=a00;
  if (res[0]!=0) res[0][259]=a00;
  if (res[0]!=0) res[0][260]=a00;
  if (res[0]!=0) res[0][261]=a00;
  if (res[0]!=0) res[0][262]=a00;
  if (res[0]!=0) res[0][263]=a00;
  if (res[0]!=0) res[0][264]=a00;
  if (res[0]!=0) res[0][265]=a00;
  if (res[0]!=0) res[0][266]=a00;
  if (res[0]!=0) res[0][267]=a00;
  if (res[0]!=0) res[0][268]=a00;
  if (res[0]!=0) res[0][269]=a00;
  if (res[0]!=0) res[0][270]=a00;
  if (res[0]!=0) res[0][271]=a00;
  if (res[0]!=0) res[0][272]=a00;
  if (res[0]!=0) res[0][273]=a00;
  if (res[0]!=0) res[0][274]=a00;
  if (res[0]!=0) res[0][275]=a00;
  if (res[0]!=0) res[0][276]=a00;
  if (res[0]!=0) res[0][277]=a00;
  if (res[0]!=0) res[0][278]=a00;
  if (res[0]!=0) res[0][279]=a00;
  if (res[0]!=0) res[0][280]=a00;
  if (res[0]!=0) res[0][281]=a00;
  if (res[0]!=0) res[0][282]=a00;
  if (res[0]!=0) res[0][283]=a00;
  if (res[0]!=0) res[0][284]=a00;
  if (res[0]!=0) res[0][285]=a00;
  if (res[0]!=0) res[0][286]=a00;
  if (res[0]!=0) res[0][287]=a00;
  if (res[0]!=0) res[0][288]=a00;
  if (res[0]!=0) res[0][289]=a00;
  if (res[0]!=0) res[0][290]=a00;
  if (res[0]!=0) res[0][291]=a00;
  if (res[0]!=0) res[0][292]=a00;
  if (res[0]!=0) res[0][293]=a00;
  if (res[0]!=0) res[0][294]=a00;
  if (res[0]!=0) res[0][295]=a00;
  if (res[0]!=0) res[0][296]=a00;
  if (res[0]!=0) res[0][297]=a00;
  if (res[0]!=0) res[0][298]=a00;
  if (res[0]!=0) res[0][299]=a00;
  if (res[0]!=0) res[0][300]=a00;
  if (res[0]!=0) res[0][301]=a00;
  if (res[0]!=0) res[0][302]=a00;
  if (res[0]!=0) res[0][303]=a00;
  if (res[0]!=0) res[0][304]=a00;
  if (res[0]!=0) res[0][305]=a00;
  if (res[0]!=0) res[0][306]=a00;
  if (res[0]!=0) res[0][307]=a00;
  if (res[0]!=0) res[0][308]=a00;
  if (res[0]!=0) res[0][309]=a00;
  if (res[0]!=0) res[0][310]=a00;
  if (res[0]!=0) res[0][311]=a00;
  if (res[0]!=0) res[0][312]=a00;
  if (res[0]!=0) res[0][313]=a00;
  if (res[0]!=0) res[0][314]=a00;
  if (res[0]!=0) res[0][315]=a00;
  if (res[0]!=0) res[0][316]=a00;
  if (res[0]!=0) res[0][317]=a00;
  if (res[0]!=0) res[0][318]=a00;
  if (res[0]!=0) res[0][319]=a00;
  if (res[0]!=0) res[0][320]=a00;
  if (res[0]!=0) res[0][321]=a00;
  if (res[0]!=0) res[0][322]=a00;
  if (res[0]!=0) res[0][323]=a00;
  if (res[0]!=0) res[0][324]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_jvp_deriv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_jvp_deriv_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_jvp_deriv_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_jvp_deriv_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_jvp_deriv_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_jvp_deriv_release(int mem) {
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_jvp_deriv_incref(void) {
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_jvp_deriv_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int velocity_kinematics_jvp_deriv_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int velocity_kinematics_jvp_deriv_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real velocity_kinematics_jvp_deriv_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* velocity_kinematics_jvp_deriv_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* velocity_kinematics_jvp_deriv_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* velocity_kinematics_jvp_deriv_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* velocity_kinematics_jvp_deriv_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_jvp_deriv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_jvp_deriv_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
