/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) C_func_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};

/* C_func:(i0[4])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[0]? arg[0][1] : 0;
  a1=cos(a0);
  a2=9.8100000000000005e+00;
  a0=sin(a0);
  a3=(a2*a0);
  a4=(a1*a3);
  a2=(a2*a1);
  a5=arg[0]? arg[0][3] : 0;
  a6=arg[0]? arg[0][2] : 0;
  a1=(a1*a6);
  a6=(a5*a1);
  a2=(a2-a6);
  a1=(a1-a5);
  a5=(a5*a1);
  a2=(a2+a5);
  a0=(a0*a2);
  a4=(a4-a0);
  if (res[0]!=0) res[0][0]=a4;
  a3=(-a3);
  if (res[0]!=0) res[0][1]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int C_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int C_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int C_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void C_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int C_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void C_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void C_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void C_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int C_func_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int C_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real C_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* C_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* C_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* C_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* C_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int C_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int C_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
