/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {59, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};

/* kinematics:(i0[59])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.1500000000000000e-01;
  a02=2.;
  a03=arg[0]? arg[0][5] : 0;
  a04=(a02*a03);
  a05=arg[0]? arg[0][4] : 0;
  a06=(a04*a05);
  a07=arg[0]? arg[0][6] : 0;
  a08=(a02*a07);
  a09=arg[0]? arg[0][3] : 0;
  a10=(a08*a09);
  a11=(a06-a10);
  a12=(a01*a11);
  a13=-7.1849999999999997e-02;
  a14=(a08*a05);
  a15=(a04*a09);
  a16=(a14+a15);
  a17=(a13*a16);
  a12=(a12+a17);
  a12=(a00+a12);
  a17=3.5000000000000003e-02;
  a18=1.;
  a04=(a04*a03);
  a07=(a08*a07);
  a19=(a04+a07);
  a19=(a18-a19);
  a20=arg[0]? arg[0][7] : 0;
  a21=cos(a20);
  a22=(a19*a21);
  a20=sin(a20);
  a23=(a11*a20);
  a22=(a22-a23);
  a23=(a17*a22);
  a24=1.4999999999999999e-02;
  a25=(a19*a20);
  a26=(a11*a21);
  a25=(a25+a26);
  a26=(a24*a25);
  a27=-4.9750000000000003e-02;
  a28=(a27*a16);
  a26=(a26+a28);
  a23=(a23+a26);
  a12=(a12+a23);
  a23=-7.9067999999999999e-02;
  a26=arg[0]? arg[0][8] : 0;
  a28=cos(a26);
  a29=(a16*a28);
  a26=sin(a26);
  a30=(a25*a26);
  a29=(a29-a30);
  a30=(a23*a29);
  a12=(a12+a30);
  a30=-3.8000000000000000e-01;
  a31=arg[0]? arg[0][9] : 0;
  a32=sin(a31);
  a33=(a22*a32);
  a31=cos(a31);
  a34=(a29*a31);
  a33=(a33+a34);
  a34=(a30*a33);
  a12=(a12+a34);
  a34=-8.3022200000000008e-03;
  a22=(a22*a31);
  a29=(a29*a32);
  a22=(a22-a29);
  a29=arg[0]? arg[0][10] : 0;
  a35=cos(a29);
  a36=(a22*a35);
  a29=sin(a29);
  a37=(a33*a29);
  a36=(a36-a37);
  a37=(a34*a36);
  a38=-4.0213937999999999e-01;
  a22=(a22*a29);
  a33=(a33*a35);
  a22=(a22+a33);
  a33=(a38*a22);
  a37=(a37+a33);
  a12=(a12+a37);
  a37=-1.0000000000000000e-02;
  a33=arg[0]? arg[0][11] : 0;
  a39=sin(a33);
  a40=(a36*a39);
  a33=cos(a33);
  a41=(a22*a33);
  a40=(a40+a41);
  a41=(a37*a40);
  a12=(a12+a41);
  a41=5.2999999999999999e-02;
  a36=(a36*a33);
  a22=(a22*a39);
  a36=(a36-a22);
  a36=(a41*a36);
  a22=8.5000000000000006e-03;
  a25=(a25*a28);
  a42=(a16*a26);
  a25=(a25+a42);
  a42=arg[0]? arg[0][12] : 0;
  a43=cos(a42);
  a44=(a25*a43);
  a42=sin(a42);
  a45=(a40*a42);
  a44=(a44+a45);
  a44=(a22*a44);
  a45=-8.7999999999999995e-02;
  a40=(a40*a43);
  a25=(a25*a42);
  a40=(a40-a25);
  a40=(a45*a40);
  a44=(a44+a40);
  a36=(a36+a44);
  a12=(a12+a36);
  if (res[0]!=0) res[0][0]=a12;
  a12=arg[0]? arg[0][1] : 0;
  a02=(a02*a05);
  a05=(a02*a05);
  a07=(a05+a07);
  a07=(a18-a07);
  a36=(a01*a07);
  a08=(a08*a03);
  a02=(a02*a09);
  a09=(a08-a02);
  a03=(a13*a09);
  a36=(a36+a03);
  a36=(a12+a36);
  a06=(a06+a10);
  a10=(a06*a21);
  a03=(a07*a20);
  a10=(a10-a03);
  a03=(a17*a10);
  a44=(a06*a20);
  a40=(a07*a21);
  a44=(a44+a40);
  a40=(a24*a44);
  a25=(a27*a09);
  a40=(a40+a25);
  a03=(a03+a40);
  a36=(a36+a03);
  a03=(a09*a28);
  a40=(a44*a26);
  a03=(a03-a40);
  a40=(a23*a03);
  a36=(a36+a40);
  a40=(a10*a32);
  a25=(a03*a31);
  a40=(a40+a25);
  a25=(a30*a40);
  a36=(a36+a25);
  a10=(a10*a31);
  a03=(a03*a32);
  a10=(a10-a03);
  a03=(a10*a35);
  a25=(a40*a29);
  a03=(a03-a25);
  a25=(a34*a03);
  a10=(a10*a29);
  a40=(a40*a35);
  a10=(a10+a40);
  a40=(a38*a10);
  a25=(a25+a40);
  a36=(a36+a25);
  a25=(a03*a39);
  a40=(a10*a33);
  a25=(a25+a40);
  a40=(a37*a25);
  a36=(a36+a40);
  a03=(a03*a33);
  a10=(a10*a39);
  a03=(a03-a10);
  a03=(a41*a03);
  a44=(a44*a28);
  a10=(a09*a26);
  a44=(a44+a10);
  a10=(a44*a43);
  a40=(a25*a42);
  a10=(a10+a40);
  a10=(a22*a10);
  a25=(a25*a43);
  a44=(a44*a42);
  a25=(a25-a44);
  a25=(a45*a25);
  a10=(a10+a25);
  a03=(a03+a10);
  a36=(a36+a03);
  if (res[0]!=0) res[0][1]=a36;
  a36=arg[0]? arg[0][2] : 0;
  a08=(a08+a02);
  a01=(a01*a08);
  a05=(a05+a04);
  a18=(a18-a05);
  a05=(a13*a18);
  a01=(a01+a05);
  a01=(a36+a01);
  a14=(a14-a15);
  a15=(a14*a21);
  a05=(a08*a20);
  a15=(a15-a05);
  a05=(a17*a15);
  a20=(a14*a20);
  a21=(a08*a21);
  a20=(a20+a21);
  a24=(a24*a20);
  a21=(a27*a18);
  a24=(a24+a21);
  a05=(a05+a24);
  a01=(a01+a05);
  a05=(a18*a28);
  a24=(a20*a26);
  a05=(a05-a24);
  a24=(a23*a05);
  a01=(a01+a24);
  a24=(a15*a32);
  a21=(a05*a31);
  a24=(a24+a21);
  a21=(a30*a24);
  a01=(a01+a21);
  a15=(a15*a31);
  a05=(a05*a32);
  a15=(a15-a05);
  a05=(a15*a35);
  a32=(a24*a29);
  a05=(a05-a32);
  a32=(a34*a05);
  a15=(a15*a29);
  a24=(a24*a35);
  a15=(a15+a24);
  a24=(a38*a15);
  a32=(a32+a24);
  a01=(a01+a32);
  a32=(a05*a39);
  a24=(a15*a33);
  a32=(a32+a24);
  a24=(a37*a32);
  a01=(a01+a24);
  a05=(a05*a33);
  a15=(a15*a39);
  a05=(a05-a15);
  a05=(a41*a05);
  a20=(a20*a28);
  a26=(a18*a26);
  a20=(a20+a26);
  a26=(a20*a43);
  a28=(a32*a42);
  a26=(a26+a28);
  a26=(a22*a26);
  a32=(a32*a43);
  a20=(a20*a42);
  a32=(a32-a20);
  a32=(a45*a32);
  a26=(a26+a32);
  a05=(a05+a26);
  a01=(a01+a05);
  if (res[0]!=0) res[0][2]=a01;
  a01=-1.1500000000000000e-01;
  a05=(a01*a11);
  a26=(a13*a16);
  a05=(a05+a26);
  a00=(a00+a05);
  a05=arg[0]? arg[0][13] : 0;
  a26=cos(a05);
  a32=(a19*a26);
  a05=sin(a05);
  a20=(a11*a05);
  a32=(a32-a20);
  a20=(a17*a32);
  a42=-1.4999999999999999e-02;
  a19=(a19*a05);
  a11=(a11*a26);
  a19=(a19+a11);
  a11=(a42*a19);
  a43=(a27*a16);
  a11=(a11+a43);
  a20=(a20+a11);
  a00=(a00+a20);
  a20=arg[0]? arg[0][14] : 0;
  a11=cos(a20);
  a43=(a16*a11);
  a20=sin(a20);
  a28=(a19*a20);
  a43=(a43-a28);
  a28=(a23*a43);
  a00=(a00+a28);
  a28=arg[0]? arg[0][15] : 0;
  a15=sin(a28);
  a39=(a32*a15);
  a28=cos(a28);
  a33=(a43*a28);
  a39=(a39+a33);
  a33=(a30*a39);
  a00=(a00+a33);
  a32=(a32*a28);
  a43=(a43*a15);
  a32=(a32-a43);
  a43=arg[0]? arg[0][16] : 0;
  a33=cos(a43);
  a24=(a32*a33);
  a43=sin(a43);
  a35=(a39*a43);
  a24=(a24-a35);
  a35=(a34*a24);
  a32=(a32*a43);
  a39=(a39*a33);
  a32=(a32+a39);
  a39=(a38*a32);
  a35=(a35+a39);
  a00=(a00+a35);
  a35=arg[0]? arg[0][17] : 0;
  a39=sin(a35);
  a29=(a24*a39);
  a35=cos(a35);
  a31=(a32*a35);
  a29=(a29+a31);
  a31=(a37*a29);
  a00=(a00+a31);
  a24=(a24*a35);
  a32=(a32*a39);
  a24=(a24-a32);
  a24=(a41*a24);
  a19=(a19*a11);
  a16=(a16*a20);
  a19=(a19+a16);
  a16=arg[0]? arg[0][18] : 0;
  a32=cos(a16);
  a31=(a19*a32);
  a16=sin(a16);
  a21=(a29*a16);
  a31=(a31+a21);
  a31=(a22*a31);
  a29=(a29*a32);
  a19=(a19*a16);
  a29=(a29-a19);
  a29=(a45*a29);
  a31=(a31+a29);
  a24=(a24+a31);
  a00=(a00+a24);
  if (res[0]!=0) res[0][3]=a00;
  a00=(a01*a07);
  a24=(a13*a09);
  a00=(a00+a24);
  a12=(a12+a00);
  a00=(a06*a26);
  a24=(a07*a05);
  a00=(a00-a24);
  a24=(a17*a00);
  a06=(a06*a05);
  a07=(a07*a26);
  a06=(a06+a07);
  a07=(a42*a06);
  a31=(a27*a09);
  a07=(a07+a31);
  a24=(a24+a07);
  a12=(a12+a24);
  a24=(a09*a11);
  a07=(a06*a20);
  a24=(a24-a07);
  a07=(a23*a24);
  a12=(a12+a07);
  a07=(a00*a15);
  a31=(a24*a28);
  a07=(a07+a31);
  a31=(a30*a07);
  a12=(a12+a31);
  a00=(a00*a28);
  a24=(a24*a15);
  a00=(a00-a24);
  a24=(a00*a33);
  a31=(a07*a43);
  a24=(a24-a31);
  a31=(a34*a24);
  a00=(a00*a43);
  a07=(a07*a33);
  a00=(a00+a07);
  a07=(a38*a00);
  a31=(a31+a07);
  a12=(a12+a31);
  a31=(a24*a39);
  a07=(a00*a35);
  a31=(a31+a07);
  a07=(a37*a31);
  a12=(a12+a07);
  a24=(a24*a35);
  a00=(a00*a39);
  a24=(a24-a00);
  a24=(a41*a24);
  a06=(a06*a11);
  a09=(a09*a20);
  a06=(a06+a09);
  a09=(a06*a32);
  a00=(a31*a16);
  a09=(a09+a00);
  a09=(a22*a09);
  a31=(a31*a32);
  a06=(a06*a16);
  a31=(a31-a06);
  a31=(a45*a31);
  a09=(a09+a31);
  a24=(a24+a09);
  a12=(a12+a24);
  if (res[0]!=0) res[0][4]=a12;
  a01=(a01*a08);
  a13=(a13*a18);
  a01=(a01+a13);
  a36=(a36+a01);
  a01=(a14*a26);
  a13=(a08*a05);
  a01=(a01-a13);
  a17=(a17*a01);
  a14=(a14*a05);
  a08=(a08*a26);
  a14=(a14+a08);
  a42=(a42*a14);
  a27=(a27*a18);
  a42=(a42+a27);
  a17=(a17+a42);
  a36=(a36+a17);
  a17=(a18*a11);
  a42=(a14*a20);
  a17=(a17-a42);
  a23=(a23*a17);
  a36=(a36+a23);
  a23=(a01*a15);
  a42=(a17*a28);
  a23=(a23+a42);
  a30=(a30*a23);
  a36=(a36+a30);
  a01=(a01*a28);
  a17=(a17*a15);
  a01=(a01-a17);
  a17=(a01*a33);
  a15=(a23*a43);
  a17=(a17-a15);
  a34=(a34*a17);
  a01=(a01*a43);
  a23=(a23*a33);
  a01=(a01+a23);
  a38=(a38*a01);
  a34=(a34+a38);
  a36=(a36+a34);
  a34=(a17*a39);
  a38=(a01*a35);
  a34=(a34+a38);
  a37=(a37*a34);
  a36=(a36+a37);
  a17=(a17*a35);
  a01=(a01*a39);
  a17=(a17-a01);
  a41=(a41*a17);
  a14=(a14*a11);
  a18=(a18*a20);
  a14=(a14+a18);
  a18=(a14*a32);
  a20=(a34*a16);
  a18=(a18+a20);
  a22=(a22*a18);
  a34=(a34*a32);
  a14=(a14*a16);
  a34=(a34-a14);
  a45=(a45*a34);
  a22=(a22+a45);
  a41=(a41+a22);
  a36=(a36+a41);
  if (res[0]!=0) res[0][5]=a36;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
