/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) velocity_kinematics_T_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {59, 1, 1};
static const casadi_int casadi_s1[3] = {29, 30, 1};

/* velocity_kinematics_T:(i0[59])->(o0[29x30]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10;
  a00=1.;
  a01=2.;
  a02=arg[0]? arg[0][6] : 0;
  a03=(a01*a02);
  a04=(a03*a02);
  a05=arg[0]? arg[0][5] : 0;
  a06=(a01*a05);
  a07=(a06*a05);
  a04=(a04+a07);
  a04=(a00-a04);
  if (res[0]!=0) res[0][0]=a04;
  a04=arg[0]? arg[0][4] : 0;
  a06=(a06*a04);
  a07=arg[0]? arg[0][3] : 0;
  a08=(a01*a07);
  a09=(a08*a02);
  a06=(a06-a09);
  if (res[0]!=0) res[0][1]=a06;
  a06=(a08*a05);
  a03=(a03*a04);
  a06=(a06+a03);
  if (res[0]!=0) res[0][2]=a06;
  a06=0.;
  if (res[0]!=0) res[0][3]=a06;
  if (res[0]!=0) res[0][4]=a06;
  if (res[0]!=0) res[0][5]=a06;
  if (res[0]!=0) res[0][6]=a06;
  if (res[0]!=0) res[0][7]=a06;
  if (res[0]!=0) res[0][8]=a06;
  if (res[0]!=0) res[0][9]=a06;
  if (res[0]!=0) res[0][10]=a06;
  if (res[0]!=0) res[0][11]=a06;
  if (res[0]!=0) res[0][12]=a06;
  if (res[0]!=0) res[0][13]=a06;
  if (res[0]!=0) res[0][14]=a06;
  if (res[0]!=0) res[0][15]=a06;
  if (res[0]!=0) res[0][16]=a06;
  if (res[0]!=0) res[0][17]=a06;
  if (res[0]!=0) res[0][18]=a06;
  if (res[0]!=0) res[0][19]=a06;
  if (res[0]!=0) res[0][20]=a06;
  if (res[0]!=0) res[0][21]=a06;
  if (res[0]!=0) res[0][22]=a06;
  if (res[0]!=0) res[0][23]=a06;
  if (res[0]!=0) res[0][24]=a06;
  if (res[0]!=0) res[0][25]=a06;
  if (res[0]!=0) res[0][26]=a06;
  if (res[0]!=0) res[0][27]=a06;
  if (res[0]!=0) res[0][28]=a06;
  a03=(a08*a02);
  a09=(a01*a04);
  a10=(a09*a05);
  a03=(a03+a10);
  if (res[0]!=0) res[0][29]=a03;
  a03=(a01*a02);
  a10=(a03*a02);
  a09=(a09*a04);
  a10=(a10+a09);
  a10=(a00-a10);
  if (res[0]!=0) res[0][30]=a10;
  a03=(a03*a05);
  a10=(a08*a04);
  a03=(a03-a10);
  if (res[0]!=0) res[0][31]=a03;
  if (res[0]!=0) res[0][32]=a06;
  if (res[0]!=0) res[0][33]=a06;
  if (res[0]!=0) res[0][34]=a06;
  if (res[0]!=0) res[0][35]=a06;
  if (res[0]!=0) res[0][36]=a06;
  if (res[0]!=0) res[0][37]=a06;
  if (res[0]!=0) res[0][38]=a06;
  if (res[0]!=0) res[0][39]=a06;
  if (res[0]!=0) res[0][40]=a06;
  if (res[0]!=0) res[0][41]=a06;
  if (res[0]!=0) res[0][42]=a06;
  if (res[0]!=0) res[0][43]=a06;
  if (res[0]!=0) res[0][44]=a06;
  if (res[0]!=0) res[0][45]=a06;
  if (res[0]!=0) res[0][46]=a06;
  if (res[0]!=0) res[0][47]=a06;
  if (res[0]!=0) res[0][48]=a06;
  if (res[0]!=0) res[0][49]=a06;
  if (res[0]!=0) res[0][50]=a06;
  if (res[0]!=0) res[0][51]=a06;
  if (res[0]!=0) res[0][52]=a06;
  if (res[0]!=0) res[0][53]=a06;
  if (res[0]!=0) res[0][54]=a06;
  if (res[0]!=0) res[0][55]=a06;
  if (res[0]!=0) res[0][56]=a06;
  if (res[0]!=0) res[0][57]=a06;
  a03=(a01*a04);
  a10=(a03*a02);
  a09=(a08*a05);
  a10=(a10-a09);
  if (res[0]!=0) res[0][58]=a10;
  a08=(a08*a04);
  a10=(a01*a05);
  a09=(a10*a02);
  a08=(a08+a09);
  if (res[0]!=0) res[0][59]=a08;
  a10=(a10*a05);
  a03=(a03*a04);
  a10=(a10+a03);
  a10=(a00-a10);
  if (res[0]!=0) res[0][60]=a10;
  if (res[0]!=0) res[0][61]=a06;
  if (res[0]!=0) res[0][62]=a06;
  if (res[0]!=0) res[0][63]=a06;
  if (res[0]!=0) res[0][64]=a06;
  if (res[0]!=0) res[0][65]=a06;
  if (res[0]!=0) res[0][66]=a06;
  if (res[0]!=0) res[0][67]=a06;
  if (res[0]!=0) res[0][68]=a06;
  if (res[0]!=0) res[0][69]=a06;
  if (res[0]!=0) res[0][70]=a06;
  if (res[0]!=0) res[0][71]=a06;
  if (res[0]!=0) res[0][72]=a06;
  if (res[0]!=0) res[0][73]=a06;
  if (res[0]!=0) res[0][74]=a06;
  if (res[0]!=0) res[0][75]=a06;
  if (res[0]!=0) res[0][76]=a06;
  if (res[0]!=0) res[0][77]=a06;
  if (res[0]!=0) res[0][78]=a06;
  if (res[0]!=0) res[0][79]=a06;
  if (res[0]!=0) res[0][80]=a06;
  if (res[0]!=0) res[0][81]=a06;
  if (res[0]!=0) res[0][82]=a06;
  if (res[0]!=0) res[0][83]=a06;
  if (res[0]!=0) res[0][84]=a06;
  if (res[0]!=0) res[0][85]=a06;
  if (res[0]!=0) res[0][86]=a06;
  if (res[0]!=0) res[0][87]=a06;
  if (res[0]!=0) res[0][88]=a06;
  if (res[0]!=0) res[0][89]=a06;
  a10=(a01*a04);
  a10=(-a10);
  if (res[0]!=0) res[0][90]=a10;
  a10=(a01*a05);
  a10=(-a10);
  if (res[0]!=0) res[0][91]=a10;
  a10=(a01*a02);
  a10=(-a10);
  if (res[0]!=0) res[0][92]=a10;
  if (res[0]!=0) res[0][93]=a06;
  if (res[0]!=0) res[0][94]=a06;
  if (res[0]!=0) res[0][95]=a06;
  if (res[0]!=0) res[0][96]=a06;
  if (res[0]!=0) res[0][97]=a06;
  if (res[0]!=0) res[0][98]=a06;
  if (res[0]!=0) res[0][99]=a06;
  if (res[0]!=0) res[0][100]=a06;
  if (res[0]!=0) res[0][101]=a06;
  if (res[0]!=0) res[0][102]=a06;
  if (res[0]!=0) res[0][103]=a06;
  if (res[0]!=0) res[0][104]=a06;
  if (res[0]!=0) res[0][105]=a06;
  if (res[0]!=0) res[0][106]=a06;
  if (res[0]!=0) res[0][107]=a06;
  if (res[0]!=0) res[0][108]=a06;
  if (res[0]!=0) res[0][109]=a06;
  if (res[0]!=0) res[0][110]=a06;
  if (res[0]!=0) res[0][111]=a06;
  if (res[0]!=0) res[0][112]=a06;
  if (res[0]!=0) res[0][113]=a06;
  if (res[0]!=0) res[0][114]=a06;
  if (res[0]!=0) res[0][115]=a06;
  if (res[0]!=0) res[0][116]=a06;
  if (res[0]!=0) res[0][117]=a06;
  if (res[0]!=0) res[0][118]=a06;
  a10=(a01*a07);
  if (res[0]!=0) res[0][119]=a10;
  a10=(a01*a02);
  a10=(-a10);
  if (res[0]!=0) res[0][120]=a10;
  a10=(a01*a05);
  if (res[0]!=0) res[0][121]=a10;
  if (res[0]!=0) res[0][122]=a06;
  if (res[0]!=0) res[0][123]=a06;
  if (res[0]!=0) res[0][124]=a06;
  if (res[0]!=0) res[0][125]=a06;
  if (res[0]!=0) res[0][126]=a06;
  if (res[0]!=0) res[0][127]=a06;
  if (res[0]!=0) res[0][128]=a06;
  if (res[0]!=0) res[0][129]=a06;
  if (res[0]!=0) res[0][130]=a06;
  if (res[0]!=0) res[0][131]=a06;
  if (res[0]!=0) res[0][132]=a06;
  if (res[0]!=0) res[0][133]=a06;
  if (res[0]!=0) res[0][134]=a06;
  if (res[0]!=0) res[0][135]=a06;
  if (res[0]!=0) res[0][136]=a06;
  if (res[0]!=0) res[0][137]=a06;
  if (res[0]!=0) res[0][138]=a06;
  if (res[0]!=0) res[0][139]=a06;
  if (res[0]!=0) res[0][140]=a06;
  if (res[0]!=0) res[0][141]=a06;
  if (res[0]!=0) res[0][142]=a06;
  if (res[0]!=0) res[0][143]=a06;
  if (res[0]!=0) res[0][144]=a06;
  if (res[0]!=0) res[0][145]=a06;
  if (res[0]!=0) res[0][146]=a06;
  if (res[0]!=0) res[0][147]=a06;
  a02=(a01*a02);
  if (res[0]!=0) res[0][148]=a02;
  a02=(a01*a07);
  if (res[0]!=0) res[0][149]=a02;
  a02=(a01*a04);
  a02=(-a02);
  if (res[0]!=0) res[0][150]=a02;
  if (res[0]!=0) res[0][151]=a06;
  if (res[0]!=0) res[0][152]=a06;
  if (res[0]!=0) res[0][153]=a06;
  if (res[0]!=0) res[0][154]=a06;
  if (res[0]!=0) res[0][155]=a06;
  if (res[0]!=0) res[0][156]=a06;
  if (res[0]!=0) res[0][157]=a06;
  if (res[0]!=0) res[0][158]=a06;
  if (res[0]!=0) res[0][159]=a06;
  if (res[0]!=0) res[0][160]=a06;
  if (res[0]!=0) res[0][161]=a06;
  if (res[0]!=0) res[0][162]=a06;
  if (res[0]!=0) res[0][163]=a06;
  if (res[0]!=0) res[0][164]=a06;
  if (res[0]!=0) res[0][165]=a06;
  if (res[0]!=0) res[0][166]=a06;
  if (res[0]!=0) res[0][167]=a06;
  if (res[0]!=0) res[0][168]=a06;
  if (res[0]!=0) res[0][169]=a06;
  if (res[0]!=0) res[0][170]=a06;
  if (res[0]!=0) res[0][171]=a06;
  if (res[0]!=0) res[0][172]=a06;
  if (res[0]!=0) res[0][173]=a06;
  if (res[0]!=0) res[0][174]=a06;
  if (res[0]!=0) res[0][175]=a06;
  if (res[0]!=0) res[0][176]=a06;
  a05=(a01*a05);
  a05=(-a05);
  if (res[0]!=0) res[0][177]=a05;
  a04=(a01*a04);
  if (res[0]!=0) res[0][178]=a04;
  a01=(a01*a07);
  if (res[0]!=0) res[0][179]=a01;
  if (res[0]!=0) res[0][180]=a06;
  if (res[0]!=0) res[0][181]=a06;
  if (res[0]!=0) res[0][182]=a06;
  if (res[0]!=0) res[0][183]=a06;
  if (res[0]!=0) res[0][184]=a06;
  if (res[0]!=0) res[0][185]=a06;
  if (res[0]!=0) res[0][186]=a06;
  if (res[0]!=0) res[0][187]=a06;
  if (res[0]!=0) res[0][188]=a06;
  if (res[0]!=0) res[0][189]=a06;
  if (res[0]!=0) res[0][190]=a06;
  if (res[0]!=0) res[0][191]=a06;
  if (res[0]!=0) res[0][192]=a06;
  if (res[0]!=0) res[0][193]=a06;
  if (res[0]!=0) res[0][194]=a06;
  if (res[0]!=0) res[0][195]=a06;
  if (res[0]!=0) res[0][196]=a06;
  if (res[0]!=0) res[0][197]=a06;
  if (res[0]!=0) res[0][198]=a06;
  if (res[0]!=0) res[0][199]=a06;
  if (res[0]!=0) res[0][200]=a06;
  if (res[0]!=0) res[0][201]=a06;
  if (res[0]!=0) res[0][202]=a06;
  if (res[0]!=0) res[0][203]=a06;
  if (res[0]!=0) res[0][204]=a06;
  if (res[0]!=0) res[0][205]=a06;
  if (res[0]!=0) res[0][206]=a06;
  if (res[0]!=0) res[0][207]=a06;
  if (res[0]!=0) res[0][208]=a06;
  if (res[0]!=0) res[0][209]=a00;
  if (res[0]!=0) res[0][210]=a06;
  if (res[0]!=0) res[0][211]=a06;
  if (res[0]!=0) res[0][212]=a06;
  if (res[0]!=0) res[0][213]=a06;
  if (res[0]!=0) res[0][214]=a06;
  if (res[0]!=0) res[0][215]=a06;
  if (res[0]!=0) res[0][216]=a06;
  if (res[0]!=0) res[0][217]=a06;
  if (res[0]!=0) res[0][218]=a06;
  if (res[0]!=0) res[0][219]=a06;
  if (res[0]!=0) res[0][220]=a06;
  if (res[0]!=0) res[0][221]=a06;
  if (res[0]!=0) res[0][222]=a06;
  if (res[0]!=0) res[0][223]=a06;
  if (res[0]!=0) res[0][224]=a06;
  if (res[0]!=0) res[0][225]=a06;
  if (res[0]!=0) res[0][226]=a06;
  if (res[0]!=0) res[0][227]=a06;
  if (res[0]!=0) res[0][228]=a06;
  if (res[0]!=0) res[0][229]=a06;
  if (res[0]!=0) res[0][230]=a06;
  if (res[0]!=0) res[0][231]=a06;
  if (res[0]!=0) res[0][232]=a06;
  if (res[0]!=0) res[0][233]=a06;
  if (res[0]!=0) res[0][234]=a06;
  if (res[0]!=0) res[0][235]=a06;
  if (res[0]!=0) res[0][236]=a06;
  if (res[0]!=0) res[0][237]=a06;
  if (res[0]!=0) res[0][238]=a06;
  if (res[0]!=0) res[0][239]=a00;
  if (res[0]!=0) res[0][240]=a06;
  if (res[0]!=0) res[0][241]=a06;
  if (res[0]!=0) res[0][242]=a06;
  if (res[0]!=0) res[0][243]=a06;
  if (res[0]!=0) res[0][244]=a06;
  if (res[0]!=0) res[0][245]=a06;
  if (res[0]!=0) res[0][246]=a06;
  if (res[0]!=0) res[0][247]=a06;
  if (res[0]!=0) res[0][248]=a06;
  if (res[0]!=0) res[0][249]=a06;
  if (res[0]!=0) res[0][250]=a06;
  if (res[0]!=0) res[0][251]=a06;
  if (res[0]!=0) res[0][252]=a06;
  if (res[0]!=0) res[0][253]=a06;
  if (res[0]!=0) res[0][254]=a06;
  if (res[0]!=0) res[0][255]=a06;
  if (res[0]!=0) res[0][256]=a06;
  if (res[0]!=0) res[0][257]=a06;
  if (res[0]!=0) res[0][258]=a06;
  if (res[0]!=0) res[0][259]=a06;
  if (res[0]!=0) res[0][260]=a06;
  if (res[0]!=0) res[0][261]=a06;
  if (res[0]!=0) res[0][262]=a06;
  if (res[0]!=0) res[0][263]=a06;
  if (res[0]!=0) res[0][264]=a06;
  if (res[0]!=0) res[0][265]=a06;
  if (res[0]!=0) res[0][266]=a06;
  if (res[0]!=0) res[0][267]=a06;
  if (res[0]!=0) res[0][268]=a06;
  if (res[0]!=0) res[0][269]=a00;
  if (res[0]!=0) res[0][270]=a06;
  if (res[0]!=0) res[0][271]=a06;
  if (res[0]!=0) res[0][272]=a06;
  if (res[0]!=0) res[0][273]=a06;
  if (res[0]!=0) res[0][274]=a06;
  if (res[0]!=0) res[0][275]=a06;
  if (res[0]!=0) res[0][276]=a06;
  if (res[0]!=0) res[0][277]=a06;
  if (res[0]!=0) res[0][278]=a06;
  if (res[0]!=0) res[0][279]=a06;
  if (res[0]!=0) res[0][280]=a06;
  if (res[0]!=0) res[0][281]=a06;
  if (res[0]!=0) res[0][282]=a06;
  if (res[0]!=0) res[0][283]=a06;
  if (res[0]!=0) res[0][284]=a06;
  if (res[0]!=0) res[0][285]=a06;
  if (res[0]!=0) res[0][286]=a06;
  if (res[0]!=0) res[0][287]=a06;
  if (res[0]!=0) res[0][288]=a06;
  if (res[0]!=0) res[0][289]=a06;
  if (res[0]!=0) res[0][290]=a06;
  if (res[0]!=0) res[0][291]=a06;
  if (res[0]!=0) res[0][292]=a06;
  if (res[0]!=0) res[0][293]=a06;
  if (res[0]!=0) res[0][294]=a06;
  if (res[0]!=0) res[0][295]=a06;
  if (res[0]!=0) res[0][296]=a06;
  if (res[0]!=0) res[0][297]=a06;
  if (res[0]!=0) res[0][298]=a06;
  if (res[0]!=0) res[0][299]=a00;
  if (res[0]!=0) res[0][300]=a06;
  if (res[0]!=0) res[0][301]=a06;
  if (res[0]!=0) res[0][302]=a06;
  if (res[0]!=0) res[0][303]=a06;
  if (res[0]!=0) res[0][304]=a06;
  if (res[0]!=0) res[0][305]=a06;
  if (res[0]!=0) res[0][306]=a06;
  if (res[0]!=0) res[0][307]=a06;
  if (res[0]!=0) res[0][308]=a06;
  if (res[0]!=0) res[0][309]=a06;
  if (res[0]!=0) res[0][310]=a06;
  if (res[0]!=0) res[0][311]=a06;
  if (res[0]!=0) res[0][312]=a06;
  if (res[0]!=0) res[0][313]=a06;
  if (res[0]!=0) res[0][314]=a06;
  if (res[0]!=0) res[0][315]=a06;
  if (res[0]!=0) res[0][316]=a06;
  if (res[0]!=0) res[0][317]=a06;
  if (res[0]!=0) res[0][318]=a06;
  if (res[0]!=0) res[0][319]=a06;
  if (res[0]!=0) res[0][320]=a06;
  if (res[0]!=0) res[0][321]=a06;
  if (res[0]!=0) res[0][322]=a06;
  if (res[0]!=0) res[0][323]=a06;
  if (res[0]!=0) res[0][324]=a06;
  if (res[0]!=0) res[0][325]=a06;
  if (res[0]!=0) res[0][326]=a06;
  if (res[0]!=0) res[0][327]=a06;
  if (res[0]!=0) res[0][328]=a06;
  if (res[0]!=0) res[0][329]=a00;
  if (res[0]!=0) res[0][330]=a06;
  if (res[0]!=0) res[0][331]=a06;
  if (res[0]!=0) res[0][332]=a06;
  if (res[0]!=0) res[0][333]=a06;
  if (res[0]!=0) res[0][334]=a06;
  if (res[0]!=0) res[0][335]=a06;
  if (res[0]!=0) res[0][336]=a06;
  if (res[0]!=0) res[0][337]=a06;
  if (res[0]!=0) res[0][338]=a06;
  if (res[0]!=0) res[0][339]=a06;
  if (res[0]!=0) res[0][340]=a06;
  if (res[0]!=0) res[0][341]=a06;
  if (res[0]!=0) res[0][342]=a06;
  if (res[0]!=0) res[0][343]=a06;
  if (res[0]!=0) res[0][344]=a06;
  if (res[0]!=0) res[0][345]=a06;
  if (res[0]!=0) res[0][346]=a06;
  if (res[0]!=0) res[0][347]=a06;
  if (res[0]!=0) res[0][348]=a06;
  if (res[0]!=0) res[0][349]=a06;
  if (res[0]!=0) res[0][350]=a06;
  if (res[0]!=0) res[0][351]=a06;
  if (res[0]!=0) res[0][352]=a06;
  if (res[0]!=0) res[0][353]=a06;
  if (res[0]!=0) res[0][354]=a06;
  if (res[0]!=0) res[0][355]=a06;
  if (res[0]!=0) res[0][356]=a06;
  if (res[0]!=0) res[0][357]=a06;
  if (res[0]!=0) res[0][358]=a06;
  if (res[0]!=0) res[0][359]=a00;
  if (res[0]!=0) res[0][360]=a06;
  if (res[0]!=0) res[0][361]=a06;
  if (res[0]!=0) res[0][362]=a06;
  if (res[0]!=0) res[0][363]=a06;
  if (res[0]!=0) res[0][364]=a06;
  if (res[0]!=0) res[0][365]=a06;
  if (res[0]!=0) res[0][366]=a06;
  if (res[0]!=0) res[0][367]=a06;
  if (res[0]!=0) res[0][368]=a06;
  if (res[0]!=0) res[0][369]=a06;
  if (res[0]!=0) res[0][370]=a06;
  if (res[0]!=0) res[0][371]=a06;
  if (res[0]!=0) res[0][372]=a06;
  if (res[0]!=0) res[0][373]=a06;
  if (res[0]!=0) res[0][374]=a06;
  if (res[0]!=0) res[0][375]=a06;
  if (res[0]!=0) res[0][376]=a06;
  if (res[0]!=0) res[0][377]=a06;
  if (res[0]!=0) res[0][378]=a06;
  if (res[0]!=0) res[0][379]=a06;
  if (res[0]!=0) res[0][380]=a06;
  if (res[0]!=0) res[0][381]=a06;
  if (res[0]!=0) res[0][382]=a06;
  if (res[0]!=0) res[0][383]=a06;
  if (res[0]!=0) res[0][384]=a06;
  if (res[0]!=0) res[0][385]=a06;
  if (res[0]!=0) res[0][386]=a06;
  if (res[0]!=0) res[0][387]=a06;
  if (res[0]!=0) res[0][388]=a06;
  if (res[0]!=0) res[0][389]=a00;
  if (res[0]!=0) res[0][390]=a06;
  if (res[0]!=0) res[0][391]=a06;
  if (res[0]!=0) res[0][392]=a06;
  if (res[0]!=0) res[0][393]=a06;
  if (res[0]!=0) res[0][394]=a06;
  if (res[0]!=0) res[0][395]=a06;
  if (res[0]!=0) res[0][396]=a06;
  if (res[0]!=0) res[0][397]=a06;
  if (res[0]!=0) res[0][398]=a06;
  if (res[0]!=0) res[0][399]=a06;
  if (res[0]!=0) res[0][400]=a06;
  if (res[0]!=0) res[0][401]=a06;
  if (res[0]!=0) res[0][402]=a06;
  if (res[0]!=0) res[0][403]=a06;
  if (res[0]!=0) res[0][404]=a06;
  if (res[0]!=0) res[0][405]=a06;
  if (res[0]!=0) res[0][406]=a06;
  if (res[0]!=0) res[0][407]=a06;
  if (res[0]!=0) res[0][408]=a06;
  if (res[0]!=0) res[0][409]=a06;
  if (res[0]!=0) res[0][410]=a06;
  if (res[0]!=0) res[0][411]=a06;
  if (res[0]!=0) res[0][412]=a06;
  if (res[0]!=0) res[0][413]=a06;
  if (res[0]!=0) res[0][414]=a06;
  if (res[0]!=0) res[0][415]=a06;
  if (res[0]!=0) res[0][416]=a06;
  if (res[0]!=0) res[0][417]=a06;
  if (res[0]!=0) res[0][418]=a06;
  if (res[0]!=0) res[0][419]=a00;
  if (res[0]!=0) res[0][420]=a06;
  if (res[0]!=0) res[0][421]=a06;
  if (res[0]!=0) res[0][422]=a06;
  if (res[0]!=0) res[0][423]=a06;
  if (res[0]!=0) res[0][424]=a06;
  if (res[0]!=0) res[0][425]=a06;
  if (res[0]!=0) res[0][426]=a06;
  if (res[0]!=0) res[0][427]=a06;
  if (res[0]!=0) res[0][428]=a06;
  if (res[0]!=0) res[0][429]=a06;
  if (res[0]!=0) res[0][430]=a06;
  if (res[0]!=0) res[0][431]=a06;
  if (res[0]!=0) res[0][432]=a06;
  if (res[0]!=0) res[0][433]=a06;
  if (res[0]!=0) res[0][434]=a06;
  if (res[0]!=0) res[0][435]=a06;
  if (res[0]!=0) res[0][436]=a06;
  if (res[0]!=0) res[0][437]=a06;
  if (res[0]!=0) res[0][438]=a06;
  if (res[0]!=0) res[0][439]=a06;
  if (res[0]!=0) res[0][440]=a06;
  if (res[0]!=0) res[0][441]=a06;
  if (res[0]!=0) res[0][442]=a06;
  if (res[0]!=0) res[0][443]=a06;
  if (res[0]!=0) res[0][444]=a06;
  if (res[0]!=0) res[0][445]=a06;
  if (res[0]!=0) res[0][446]=a06;
  if (res[0]!=0) res[0][447]=a06;
  if (res[0]!=0) res[0][448]=a06;
  if (res[0]!=0) res[0][449]=a00;
  if (res[0]!=0) res[0][450]=a06;
  if (res[0]!=0) res[0][451]=a06;
  if (res[0]!=0) res[0][452]=a06;
  if (res[0]!=0) res[0][453]=a06;
  if (res[0]!=0) res[0][454]=a06;
  if (res[0]!=0) res[0][455]=a06;
  if (res[0]!=0) res[0][456]=a06;
  if (res[0]!=0) res[0][457]=a06;
  if (res[0]!=0) res[0][458]=a06;
  if (res[0]!=0) res[0][459]=a06;
  if (res[0]!=0) res[0][460]=a06;
  if (res[0]!=0) res[0][461]=a06;
  if (res[0]!=0) res[0][462]=a06;
  if (res[0]!=0) res[0][463]=a06;
  if (res[0]!=0) res[0][464]=a06;
  if (res[0]!=0) res[0][465]=a06;
  if (res[0]!=0) res[0][466]=a06;
  if (res[0]!=0) res[0][467]=a06;
  if (res[0]!=0) res[0][468]=a06;
  if (res[0]!=0) res[0][469]=a06;
  if (res[0]!=0) res[0][470]=a06;
  if (res[0]!=0) res[0][471]=a06;
  if (res[0]!=0) res[0][472]=a06;
  if (res[0]!=0) res[0][473]=a06;
  if (res[0]!=0) res[0][474]=a06;
  if (res[0]!=0) res[0][475]=a06;
  if (res[0]!=0) res[0][476]=a06;
  if (res[0]!=0) res[0][477]=a06;
  if (res[0]!=0) res[0][478]=a06;
  if (res[0]!=0) res[0][479]=a00;
  if (res[0]!=0) res[0][480]=a06;
  if (res[0]!=0) res[0][481]=a06;
  if (res[0]!=0) res[0][482]=a06;
  if (res[0]!=0) res[0][483]=a06;
  if (res[0]!=0) res[0][484]=a06;
  if (res[0]!=0) res[0][485]=a06;
  if (res[0]!=0) res[0][486]=a06;
  if (res[0]!=0) res[0][487]=a06;
  if (res[0]!=0) res[0][488]=a06;
  if (res[0]!=0) res[0][489]=a06;
  if (res[0]!=0) res[0][490]=a06;
  if (res[0]!=0) res[0][491]=a06;
  if (res[0]!=0) res[0][492]=a06;
  if (res[0]!=0) res[0][493]=a06;
  if (res[0]!=0) res[0][494]=a06;
  if (res[0]!=0) res[0][495]=a06;
  if (res[0]!=0) res[0][496]=a06;
  if (res[0]!=0) res[0][497]=a06;
  if (res[0]!=0) res[0][498]=a06;
  if (res[0]!=0) res[0][499]=a06;
  if (res[0]!=0) res[0][500]=a06;
  if (res[0]!=0) res[0][501]=a06;
  if (res[0]!=0) res[0][502]=a06;
  if (res[0]!=0) res[0][503]=a06;
  if (res[0]!=0) res[0][504]=a06;
  if (res[0]!=0) res[0][505]=a06;
  if (res[0]!=0) res[0][506]=a06;
  if (res[0]!=0) res[0][507]=a06;
  if (res[0]!=0) res[0][508]=a06;
  if (res[0]!=0) res[0][509]=a00;
  if (res[0]!=0) res[0][510]=a06;
  if (res[0]!=0) res[0][511]=a06;
  if (res[0]!=0) res[0][512]=a06;
  if (res[0]!=0) res[0][513]=a06;
  if (res[0]!=0) res[0][514]=a06;
  if (res[0]!=0) res[0][515]=a06;
  if (res[0]!=0) res[0][516]=a06;
  if (res[0]!=0) res[0][517]=a06;
  if (res[0]!=0) res[0][518]=a06;
  if (res[0]!=0) res[0][519]=a06;
  if (res[0]!=0) res[0][520]=a06;
  if (res[0]!=0) res[0][521]=a06;
  if (res[0]!=0) res[0][522]=a06;
  if (res[0]!=0) res[0][523]=a06;
  if (res[0]!=0) res[0][524]=a06;
  if (res[0]!=0) res[0][525]=a06;
  if (res[0]!=0) res[0][526]=a06;
  if (res[0]!=0) res[0][527]=a06;
  if (res[0]!=0) res[0][528]=a06;
  if (res[0]!=0) res[0][529]=a06;
  if (res[0]!=0) res[0][530]=a06;
  if (res[0]!=0) res[0][531]=a06;
  if (res[0]!=0) res[0][532]=a06;
  if (res[0]!=0) res[0][533]=a06;
  if (res[0]!=0) res[0][534]=a06;
  if (res[0]!=0) res[0][535]=a06;
  if (res[0]!=0) res[0][536]=a06;
  if (res[0]!=0) res[0][537]=a06;
  if (res[0]!=0) res[0][538]=a06;
  if (res[0]!=0) res[0][539]=a00;
  if (res[0]!=0) res[0][540]=a06;
  if (res[0]!=0) res[0][541]=a06;
  if (res[0]!=0) res[0][542]=a06;
  if (res[0]!=0) res[0][543]=a06;
  if (res[0]!=0) res[0][544]=a06;
  if (res[0]!=0) res[0][545]=a06;
  if (res[0]!=0) res[0][546]=a06;
  if (res[0]!=0) res[0][547]=a06;
  if (res[0]!=0) res[0][548]=a06;
  if (res[0]!=0) res[0][549]=a06;
  if (res[0]!=0) res[0][550]=a06;
  if (res[0]!=0) res[0][551]=a06;
  if (res[0]!=0) res[0][552]=a06;
  if (res[0]!=0) res[0][553]=a06;
  if (res[0]!=0) res[0][554]=a06;
  if (res[0]!=0) res[0][555]=a06;
  if (res[0]!=0) res[0][556]=a06;
  if (res[0]!=0) res[0][557]=a06;
  if (res[0]!=0) res[0][558]=a06;
  if (res[0]!=0) res[0][559]=a06;
  if (res[0]!=0) res[0][560]=a06;
  if (res[0]!=0) res[0][561]=a06;
  if (res[0]!=0) res[0][562]=a06;
  if (res[0]!=0) res[0][563]=a06;
  if (res[0]!=0) res[0][564]=a06;
  if (res[0]!=0) res[0][565]=a06;
  if (res[0]!=0) res[0][566]=a06;
  if (res[0]!=0) res[0][567]=a06;
  if (res[0]!=0) res[0][568]=a06;
  if (res[0]!=0) res[0][569]=a00;
  if (res[0]!=0) res[0][570]=a06;
  if (res[0]!=0) res[0][571]=a06;
  if (res[0]!=0) res[0][572]=a06;
  if (res[0]!=0) res[0][573]=a06;
  if (res[0]!=0) res[0][574]=a06;
  if (res[0]!=0) res[0][575]=a06;
  if (res[0]!=0) res[0][576]=a06;
  if (res[0]!=0) res[0][577]=a06;
  if (res[0]!=0) res[0][578]=a06;
  if (res[0]!=0) res[0][579]=a06;
  if (res[0]!=0) res[0][580]=a06;
  if (res[0]!=0) res[0][581]=a06;
  if (res[0]!=0) res[0][582]=a06;
  if (res[0]!=0) res[0][583]=a06;
  if (res[0]!=0) res[0][584]=a06;
  if (res[0]!=0) res[0][585]=a06;
  if (res[0]!=0) res[0][586]=a06;
  if (res[0]!=0) res[0][587]=a06;
  if (res[0]!=0) res[0][588]=a06;
  if (res[0]!=0) res[0][589]=a06;
  if (res[0]!=0) res[0][590]=a06;
  if (res[0]!=0) res[0][591]=a06;
  if (res[0]!=0) res[0][592]=a06;
  if (res[0]!=0) res[0][593]=a06;
  if (res[0]!=0) res[0][594]=a06;
  if (res[0]!=0) res[0][595]=a06;
  if (res[0]!=0) res[0][596]=a06;
  if (res[0]!=0) res[0][597]=a06;
  if (res[0]!=0) res[0][598]=a06;
  if (res[0]!=0) res[0][599]=a00;
  if (res[0]!=0) res[0][600]=a06;
  if (res[0]!=0) res[0][601]=a06;
  if (res[0]!=0) res[0][602]=a06;
  if (res[0]!=0) res[0][603]=a06;
  if (res[0]!=0) res[0][604]=a06;
  if (res[0]!=0) res[0][605]=a06;
  if (res[0]!=0) res[0][606]=a06;
  if (res[0]!=0) res[0][607]=a06;
  if (res[0]!=0) res[0][608]=a06;
  if (res[0]!=0) res[0][609]=a06;
  if (res[0]!=0) res[0][610]=a06;
  if (res[0]!=0) res[0][611]=a06;
  if (res[0]!=0) res[0][612]=a06;
  if (res[0]!=0) res[0][613]=a06;
  if (res[0]!=0) res[0][614]=a06;
  if (res[0]!=0) res[0][615]=a06;
  if (res[0]!=0) res[0][616]=a06;
  if (res[0]!=0) res[0][617]=a06;
  if (res[0]!=0) res[0][618]=a06;
  if (res[0]!=0) res[0][619]=a06;
  if (res[0]!=0) res[0][620]=a06;
  if (res[0]!=0) res[0][621]=a06;
  if (res[0]!=0) res[0][622]=a06;
  if (res[0]!=0) res[0][623]=a06;
  if (res[0]!=0) res[0][624]=a06;
  if (res[0]!=0) res[0][625]=a06;
  if (res[0]!=0) res[0][626]=a06;
  if (res[0]!=0) res[0][627]=a06;
  if (res[0]!=0) res[0][628]=a06;
  if (res[0]!=0) res[0][629]=a00;
  if (res[0]!=0) res[0][630]=a06;
  if (res[0]!=0) res[0][631]=a06;
  if (res[0]!=0) res[0][632]=a06;
  if (res[0]!=0) res[0][633]=a06;
  if (res[0]!=0) res[0][634]=a06;
  if (res[0]!=0) res[0][635]=a06;
  if (res[0]!=0) res[0][636]=a06;
  if (res[0]!=0) res[0][637]=a06;
  if (res[0]!=0) res[0][638]=a06;
  if (res[0]!=0) res[0][639]=a06;
  if (res[0]!=0) res[0][640]=a06;
  if (res[0]!=0) res[0][641]=a06;
  if (res[0]!=0) res[0][642]=a06;
  if (res[0]!=0) res[0][643]=a06;
  if (res[0]!=0) res[0][644]=a06;
  if (res[0]!=0) res[0][645]=a06;
  if (res[0]!=0) res[0][646]=a06;
  if (res[0]!=0) res[0][647]=a06;
  if (res[0]!=0) res[0][648]=a06;
  if (res[0]!=0) res[0][649]=a06;
  if (res[0]!=0) res[0][650]=a06;
  if (res[0]!=0) res[0][651]=a06;
  if (res[0]!=0) res[0][652]=a06;
  if (res[0]!=0) res[0][653]=a06;
  if (res[0]!=0) res[0][654]=a06;
  if (res[0]!=0) res[0][655]=a06;
  if (res[0]!=0) res[0][656]=a06;
  if (res[0]!=0) res[0][657]=a06;
  if (res[0]!=0) res[0][658]=a06;
  if (res[0]!=0) res[0][659]=a00;
  if (res[0]!=0) res[0][660]=a06;
  if (res[0]!=0) res[0][661]=a06;
  if (res[0]!=0) res[0][662]=a06;
  if (res[0]!=0) res[0][663]=a06;
  if (res[0]!=0) res[0][664]=a06;
  if (res[0]!=0) res[0][665]=a06;
  if (res[0]!=0) res[0][666]=a06;
  if (res[0]!=0) res[0][667]=a06;
  if (res[0]!=0) res[0][668]=a06;
  if (res[0]!=0) res[0][669]=a06;
  if (res[0]!=0) res[0][670]=a06;
  if (res[0]!=0) res[0][671]=a06;
  if (res[0]!=0) res[0][672]=a06;
  if (res[0]!=0) res[0][673]=a06;
  if (res[0]!=0) res[0][674]=a06;
  if (res[0]!=0) res[0][675]=a06;
  if (res[0]!=0) res[0][676]=a06;
  if (res[0]!=0) res[0][677]=a06;
  if (res[0]!=0) res[0][678]=a06;
  if (res[0]!=0) res[0][679]=a06;
  if (res[0]!=0) res[0][680]=a06;
  if (res[0]!=0) res[0][681]=a06;
  if (res[0]!=0) res[0][682]=a06;
  if (res[0]!=0) res[0][683]=a06;
  if (res[0]!=0) res[0][684]=a06;
  if (res[0]!=0) res[0][685]=a06;
  if (res[0]!=0) res[0][686]=a06;
  if (res[0]!=0) res[0][687]=a06;
  if (res[0]!=0) res[0][688]=a06;
  if (res[0]!=0) res[0][689]=a00;
  if (res[0]!=0) res[0][690]=a06;
  if (res[0]!=0) res[0][691]=a06;
  if (res[0]!=0) res[0][692]=a06;
  if (res[0]!=0) res[0][693]=a06;
  if (res[0]!=0) res[0][694]=a06;
  if (res[0]!=0) res[0][695]=a06;
  if (res[0]!=0) res[0][696]=a06;
  if (res[0]!=0) res[0][697]=a06;
  if (res[0]!=0) res[0][698]=a06;
  if (res[0]!=0) res[0][699]=a06;
  if (res[0]!=0) res[0][700]=a06;
  if (res[0]!=0) res[0][701]=a06;
  if (res[0]!=0) res[0][702]=a06;
  if (res[0]!=0) res[0][703]=a06;
  if (res[0]!=0) res[0][704]=a06;
  if (res[0]!=0) res[0][705]=a06;
  if (res[0]!=0) res[0][706]=a06;
  if (res[0]!=0) res[0][707]=a06;
  if (res[0]!=0) res[0][708]=a06;
  if (res[0]!=0) res[0][709]=a06;
  if (res[0]!=0) res[0][710]=a06;
  if (res[0]!=0) res[0][711]=a06;
  if (res[0]!=0) res[0][712]=a06;
  if (res[0]!=0) res[0][713]=a06;
  if (res[0]!=0) res[0][714]=a06;
  if (res[0]!=0) res[0][715]=a06;
  if (res[0]!=0) res[0][716]=a06;
  if (res[0]!=0) res[0][717]=a06;
  if (res[0]!=0) res[0][718]=a06;
  if (res[0]!=0) res[0][719]=a00;
  if (res[0]!=0) res[0][720]=a06;
  if (res[0]!=0) res[0][721]=a06;
  if (res[0]!=0) res[0][722]=a06;
  if (res[0]!=0) res[0][723]=a06;
  if (res[0]!=0) res[0][724]=a06;
  if (res[0]!=0) res[0][725]=a06;
  if (res[0]!=0) res[0][726]=a06;
  if (res[0]!=0) res[0][727]=a06;
  if (res[0]!=0) res[0][728]=a06;
  if (res[0]!=0) res[0][729]=a06;
  if (res[0]!=0) res[0][730]=a06;
  if (res[0]!=0) res[0][731]=a06;
  if (res[0]!=0) res[0][732]=a06;
  if (res[0]!=0) res[0][733]=a06;
  if (res[0]!=0) res[0][734]=a06;
  if (res[0]!=0) res[0][735]=a06;
  if (res[0]!=0) res[0][736]=a06;
  if (res[0]!=0) res[0][737]=a06;
  if (res[0]!=0) res[0][738]=a06;
  if (res[0]!=0) res[0][739]=a06;
  if (res[0]!=0) res[0][740]=a06;
  if (res[0]!=0) res[0][741]=a06;
  if (res[0]!=0) res[0][742]=a06;
  if (res[0]!=0) res[0][743]=a06;
  if (res[0]!=0) res[0][744]=a06;
  if (res[0]!=0) res[0][745]=a06;
  if (res[0]!=0) res[0][746]=a06;
  if (res[0]!=0) res[0][747]=a06;
  if (res[0]!=0) res[0][748]=a06;
  if (res[0]!=0) res[0][749]=a00;
  if (res[0]!=0) res[0][750]=a06;
  if (res[0]!=0) res[0][751]=a06;
  if (res[0]!=0) res[0][752]=a06;
  if (res[0]!=0) res[0][753]=a06;
  if (res[0]!=0) res[0][754]=a06;
  if (res[0]!=0) res[0][755]=a06;
  if (res[0]!=0) res[0][756]=a06;
  if (res[0]!=0) res[0][757]=a06;
  if (res[0]!=0) res[0][758]=a06;
  if (res[0]!=0) res[0][759]=a06;
  if (res[0]!=0) res[0][760]=a06;
  if (res[0]!=0) res[0][761]=a06;
  if (res[0]!=0) res[0][762]=a06;
  if (res[0]!=0) res[0][763]=a06;
  if (res[0]!=0) res[0][764]=a06;
  if (res[0]!=0) res[0][765]=a06;
  if (res[0]!=0) res[0][766]=a06;
  if (res[0]!=0) res[0][767]=a06;
  if (res[0]!=0) res[0][768]=a06;
  if (res[0]!=0) res[0][769]=a06;
  if (res[0]!=0) res[0][770]=a06;
  if (res[0]!=0) res[0][771]=a06;
  if (res[0]!=0) res[0][772]=a06;
  if (res[0]!=0) res[0][773]=a06;
  if (res[0]!=0) res[0][774]=a06;
  if (res[0]!=0) res[0][775]=a06;
  if (res[0]!=0) res[0][776]=a06;
  if (res[0]!=0) res[0][777]=a06;
  if (res[0]!=0) res[0][778]=a06;
  if (res[0]!=0) res[0][779]=a00;
  if (res[0]!=0) res[0][780]=a06;
  if (res[0]!=0) res[0][781]=a06;
  if (res[0]!=0) res[0][782]=a06;
  if (res[0]!=0) res[0][783]=a06;
  if (res[0]!=0) res[0][784]=a06;
  if (res[0]!=0) res[0][785]=a06;
  if (res[0]!=0) res[0][786]=a06;
  if (res[0]!=0) res[0][787]=a06;
  if (res[0]!=0) res[0][788]=a06;
  if (res[0]!=0) res[0][789]=a06;
  if (res[0]!=0) res[0][790]=a06;
  if (res[0]!=0) res[0][791]=a06;
  if (res[0]!=0) res[0][792]=a06;
  if (res[0]!=0) res[0][793]=a06;
  if (res[0]!=0) res[0][794]=a06;
  if (res[0]!=0) res[0][795]=a06;
  if (res[0]!=0) res[0][796]=a06;
  if (res[0]!=0) res[0][797]=a06;
  if (res[0]!=0) res[0][798]=a06;
  if (res[0]!=0) res[0][799]=a06;
  if (res[0]!=0) res[0][800]=a06;
  if (res[0]!=0) res[0][801]=a06;
  if (res[0]!=0) res[0][802]=a06;
  if (res[0]!=0) res[0][803]=a06;
  if (res[0]!=0) res[0][804]=a06;
  if (res[0]!=0) res[0][805]=a06;
  if (res[0]!=0) res[0][806]=a06;
  if (res[0]!=0) res[0][807]=a06;
  if (res[0]!=0) res[0][808]=a06;
  if (res[0]!=0) res[0][809]=a00;
  if (res[0]!=0) res[0][810]=a06;
  if (res[0]!=0) res[0][811]=a06;
  if (res[0]!=0) res[0][812]=a06;
  if (res[0]!=0) res[0][813]=a06;
  if (res[0]!=0) res[0][814]=a06;
  if (res[0]!=0) res[0][815]=a06;
  if (res[0]!=0) res[0][816]=a06;
  if (res[0]!=0) res[0][817]=a06;
  if (res[0]!=0) res[0][818]=a06;
  if (res[0]!=0) res[0][819]=a06;
  if (res[0]!=0) res[0][820]=a06;
  if (res[0]!=0) res[0][821]=a06;
  if (res[0]!=0) res[0][822]=a06;
  if (res[0]!=0) res[0][823]=a06;
  if (res[0]!=0) res[0][824]=a06;
  if (res[0]!=0) res[0][825]=a06;
  if (res[0]!=0) res[0][826]=a06;
  if (res[0]!=0) res[0][827]=a06;
  if (res[0]!=0) res[0][828]=a06;
  if (res[0]!=0) res[0][829]=a06;
  if (res[0]!=0) res[0][830]=a06;
  if (res[0]!=0) res[0][831]=a06;
  if (res[0]!=0) res[0][832]=a06;
  if (res[0]!=0) res[0][833]=a06;
  if (res[0]!=0) res[0][834]=a06;
  if (res[0]!=0) res[0][835]=a06;
  if (res[0]!=0) res[0][836]=a06;
  if (res[0]!=0) res[0][837]=a06;
  if (res[0]!=0) res[0][838]=a06;
  if (res[0]!=0) res[0][839]=a00;
  if (res[0]!=0) res[0][840]=a06;
  if (res[0]!=0) res[0][841]=a06;
  if (res[0]!=0) res[0][842]=a06;
  if (res[0]!=0) res[0][843]=a06;
  if (res[0]!=0) res[0][844]=a06;
  if (res[0]!=0) res[0][845]=a06;
  if (res[0]!=0) res[0][846]=a06;
  if (res[0]!=0) res[0][847]=a06;
  if (res[0]!=0) res[0][848]=a06;
  if (res[0]!=0) res[0][849]=a06;
  if (res[0]!=0) res[0][850]=a06;
  if (res[0]!=0) res[0][851]=a06;
  if (res[0]!=0) res[0][852]=a06;
  if (res[0]!=0) res[0][853]=a06;
  if (res[0]!=0) res[0][854]=a06;
  if (res[0]!=0) res[0][855]=a06;
  if (res[0]!=0) res[0][856]=a06;
  if (res[0]!=0) res[0][857]=a06;
  if (res[0]!=0) res[0][858]=a06;
  if (res[0]!=0) res[0][859]=a06;
  if (res[0]!=0) res[0][860]=a06;
  if (res[0]!=0) res[0][861]=a06;
  if (res[0]!=0) res[0][862]=a06;
  if (res[0]!=0) res[0][863]=a06;
  if (res[0]!=0) res[0][864]=a06;
  if (res[0]!=0) res[0][865]=a06;
  if (res[0]!=0) res[0][866]=a06;
  if (res[0]!=0) res[0][867]=a06;
  if (res[0]!=0) res[0][868]=a06;
  if (res[0]!=0) res[0][869]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_release(int mem) {
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_incref(void) {
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int velocity_kinematics_T_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int velocity_kinematics_T_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real velocity_kinematics_T_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* velocity_kinematics_T_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* velocity_kinematics_T_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* velocity_kinematics_T_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* velocity_kinematics_T_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
