/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {43, 1, 1};
static const casadi_int casadi_s1[3] = {21, 1, 1};

/* kinematics:(i0[43])->(o0[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39;
  a00=arg[0]? arg[0][0] : 0;
  a01=3.0300000000000001e-02;
  a02=1.;
  a03=2.;
  a04=arg[0]? arg[0][5] : 0;
  a05=(a03*a04);
  a06=(a05*a04);
  a07=arg[0]? arg[0][6] : 0;
  a08=(a03*a07);
  a07=(a08*a07);
  a09=(a06+a07);
  a09=(a02-a09);
  a10=(a01*a09);
  a11=1.2080000000000000e-01;
  a12=arg[0]? arg[0][4] : 0;
  a13=(a05*a12);
  a14=arg[0]? arg[0][3] : 0;
  a15=(a08*a14);
  a16=(a13-a15);
  a17=(a11*a16);
  a18=4.2990000000000000e-02;
  a19=(a08*a12);
  a05=(a05*a14);
  a20=(a19+a05);
  a21=(a18*a20);
  a17=(a17+a21);
  a10=(a10+a17);
  a10=(a00+a10);
  a17=-4.0000000000000001e-02;
  a21=(a17*a09);
  a22=-3.4000000000000002e-02;
  a23=arg[0]? arg[0][14] : 0;
  a24=cos(a23);
  a25=(a16*a24);
  a23=sin(a23);
  a26=(a20*a23);
  a25=(a25+a26);
  a26=(a22*a25);
  a21=(a21+a26);
  a10=(a10+a21);
  a21=7.4099999999999999e-02;
  a26=(a21*a25);
  a27=-2.2500000000000001e-01;
  a28=arg[0]? arg[0][15] : 0;
  a29=sin(a28);
  a30=(a09*a29);
  a31=(a20*a24);
  a32=(a16*a23);
  a31=(a31-a32);
  a28=cos(a28);
  a32=(a31*a28);
  a30=(a30+a32);
  a32=(a27*a30);
  a26=(a26+a32);
  a10=(a10+a26);
  a26=5.6300000000000003e-02;
  a32=(a26*a25);
  a33=(a09*a28);
  a31=(a31*a29);
  a33=(a33-a31);
  a31=arg[0]? arg[0][16] : 0;
  a34=sin(a31);
  a35=(a33*a34);
  a31=cos(a31);
  a36=(a30*a31);
  a35=(a35+a36);
  a36=(a27*a35);
  a32=(a32+a36);
  a10=(a10+a32);
  if (res[0]!=0) res[0][0]=a10;
  a10=arg[0]? arg[0][1] : 0;
  a13=(a13+a15);
  a15=(a01*a13);
  a03=(a03*a12);
  a12=(a03*a12);
  a07=(a12+a07);
  a07=(a02-a07);
  a32=(a11*a07);
  a08=(a08*a04);
  a03=(a03*a14);
  a14=(a08-a03);
  a04=(a18*a14);
  a32=(a32+a04);
  a15=(a15+a32);
  a15=(a10+a15);
  a32=(a17*a13);
  a04=(a07*a24);
  a36=(a14*a23);
  a04=(a04+a36);
  a36=(a22*a04);
  a32=(a32+a36);
  a15=(a15+a32);
  a32=(a21*a04);
  a36=(a13*a29);
  a37=(a14*a24);
  a38=(a07*a23);
  a37=(a37-a38);
  a38=(a37*a28);
  a36=(a36+a38);
  a38=(a27*a36);
  a32=(a32+a38);
  a15=(a15+a32);
  a32=(a26*a04);
  a38=(a13*a28);
  a37=(a37*a29);
  a38=(a38-a37);
  a37=(a38*a34);
  a39=(a36*a31);
  a37=(a37+a39);
  a39=(a27*a37);
  a32=(a32+a39);
  a15=(a15+a32);
  if (res[0]!=0) res[0][1]=a15;
  a15=arg[0]? arg[0][2] : 0;
  a19=(a19-a05);
  a05=(a01*a19);
  a08=(a08+a03);
  a11=(a11*a08);
  a12=(a12+a06);
  a12=(a02-a12);
  a06=(a18*a12);
  a11=(a11+a06);
  a05=(a05+a11);
  a05=(a15+a05);
  a11=(a17*a19);
  a06=(a08*a24);
  a03=(a12*a23);
  a06=(a06+a03);
  a22=(a22*a06);
  a11=(a11+a22);
  a05=(a05+a11);
  a21=(a21*a06);
  a11=(a19*a29);
  a24=(a12*a24);
  a23=(a08*a23);
  a24=(a24-a23);
  a23=(a24*a28);
  a11=(a11+a23);
  a23=(a27*a11);
  a21=(a21+a23);
  a05=(a05+a21);
  a26=(a26*a06);
  a28=(a19*a28);
  a24=(a24*a29);
  a28=(a28-a24);
  a24=(a28*a34);
  a29=(a11*a31);
  a24=(a24+a29);
  a29=(a27*a24);
  a26=(a26+a29);
  a05=(a05+a26);
  if (res[0]!=0) res[0][2]=a05;
  a33=(a33*a31);
  a30=(a30*a34);
  a33=(a33-a30);
  a30=arg[0]? arg[0][17] : 0;
  a05=cos(a30);
  a26=(a33*a05);
  a30=sin(a30);
  a29=(a35*a30);
  a26=(a26-a29);
  a29=(a02+a26);
  a29=(a29+a04);
  a28=(a28*a31);
  a11=(a11*a34);
  a28=(a28-a11);
  a11=(a28*a30);
  a21=(a24*a05);
  a11=(a11+a21);
  a29=(a29+a11);
  a21=(a02+a26);
  a21=(a21-a04);
  a21=(a21-a11);
  a23=casadi_fmax(a29,a21);
  a22=(a02-a26);
  a22=(a22+a04);
  a22=(a22-a11);
  a26=(a02-a26);
  a26=(a26-a04);
  a26=(a26+a11);
  a11=casadi_fmax(a22,a26);
  a23=casadi_fmax(a23,a11);
  a11=(a29==a23);
  a04=(a11?a29:0);
  a11=(!a11);
  a03=(a21==a23);
  a38=(a38*a31);
  a36=(a36*a34);
  a38=(a38-a36);
  a36=(a38*a30);
  a34=(a37*a05);
  a36=(a36+a34);
  a34=(a06-a36);
  a34=(a03?a34:0);
  a03=(!a03);
  a31=(a22==a23);
  a33=(a33*a30);
  a35=(a35*a05);
  a33=(a33+a35);
  a28=(a28*a05);
  a24=(a24*a30);
  a28=(a28-a24);
  a24=(a33-a28);
  a24=(a31?a24:0);
  a31=(!a31);
  a38=(a38*a05);
  a37=(a37*a30);
  a38=(a38-a37);
  a37=(a38-a25);
  a31=(a31?a37:0);
  a24=(a24+a31);
  a03=(a03?a24:0);
  a34=(a34+a03);
  a11=(a11?a34:0);
  a04=(a04+a11);
  a11=casadi_sq(a04);
  a34=(a29==a23);
  a03=(a06-a36);
  a03=(a34?a03:0);
  a34=(!a34);
  a24=(a21==a23);
  a31=(a24?a21:0);
  a24=(!a24);
  a37=(a22==a23);
  a30=(a38+a25);
  a30=(a37?a30:0);
  a37=(!a37);
  a05=(a33+a28);
  a37=(a37?a05:0);
  a30=(a30+a37);
  a24=(a24?a30:0);
  a31=(a31+a24);
  a34=(a34?a31:0);
  a03=(a03+a34);
  a34=casadi_sq(a03);
  a11=(a11+a34);
  a34=(a29==a23);
  a31=(a33-a28);
  a31=(a34?a31:0);
  a34=(!a34);
  a24=(a21==a23);
  a30=(a38+a25);
  a30=(a24?a30:0);
  a24=(!a24);
  a37=(a22==a23);
  a05=(a37?a22:0);
  a37=(!a37);
  a35=(a06+a36);
  a37=(a37?a35:0);
  a05=(a05+a37);
  a24=(a24?a05:0);
  a30=(a30+a24);
  a34=(a34?a30:0);
  a31=(a31+a34);
  a34=casadi_sq(a31);
  a11=(a11+a34);
  a29=(a29==a23);
  a38=(a38-a25);
  a38=(a29?a38:0);
  a29=(!a29);
  a21=(a21==a23);
  a33=(a33+a28);
  a33=(a21?a33:0);
  a21=(!a21);
  a22=(a22==a23);
  a06=(a06+a36);
  a06=(a22?a06:0);
  a22=(!a22);
  a22=(a22?a26:0);
  a06=(a06+a22);
  a21=(a21?a06:0);
  a33=(a33+a21);
  a29=(a29?a33:0);
  a38=(a38+a29);
  a29=casadi_sq(a38);
  a11=(a11+a29);
  a11=sqrt(a11);
  a04=(a04/a11);
  a29=casadi_sign(a04);
  a04=(a04*a29);
  if (res[0]!=0) res[0][3]=a04;
  a03=(a03/a11);
  a03=(a03*a29);
  if (res[0]!=0) res[0][4]=a03;
  a31=(a31/a11);
  a31=(a31*a29);
  if (res[0]!=0) res[0][5]=a31;
  a38=(a38/a11);
  a38=(a38*a29);
  if (res[0]!=0) res[0][6]=a38;
  a38=(a01*a09);
  a29=-1.2080000000000000e-01;
  a11=(a29*a16);
  a31=(a18*a20);
  a11=(a11+a31);
  a38=(a38+a11);
  a38=(a00+a38);
  a11=(a17*a09);
  a31=3.4000000000000002e-02;
  a03=arg[0]? arg[0][18] : 0;
  a04=cos(a03);
  a33=(a16*a04);
  a03=sin(a03);
  a21=(a20*a03);
  a33=(a33+a21);
  a21=(a31*a33);
  a11=(a11+a21);
  a38=(a38+a11);
  a11=-7.4099999999999999e-02;
  a21=(a11*a33);
  a06=arg[0]? arg[0][19] : 0;
  a22=sin(a06);
  a26=(a09*a22);
  a36=(a20*a04);
  a23=(a16*a03);
  a36=(a36-a23);
  a06=cos(a06);
  a23=(a36*a06);
  a26=(a26+a23);
  a23=(a27*a26);
  a21=(a21+a23);
  a38=(a38+a21);
  a21=-5.6300000000000003e-02;
  a23=(a21*a33);
  a28=(a09*a06);
  a36=(a36*a22);
  a28=(a28-a36);
  a36=arg[0]? arg[0][20] : 0;
  a25=sin(a36);
  a34=(a28*a25);
  a36=cos(a36);
  a30=(a26*a36);
  a34=(a34+a30);
  a30=(a27*a34);
  a23=(a23+a30);
  a38=(a38+a23);
  if (res[0]!=0) res[0][7]=a38;
  a38=(a01*a13);
  a23=(a29*a07);
  a30=(a18*a14);
  a23=(a23+a30);
  a38=(a38+a23);
  a38=(a10+a38);
  a23=(a17*a13);
  a30=(a07*a04);
  a24=(a14*a03);
  a30=(a30+a24);
  a24=(a31*a30);
  a23=(a23+a24);
  a38=(a38+a23);
  a23=(a11*a30);
  a24=(a13*a22);
  a05=(a14*a04);
  a37=(a07*a03);
  a05=(a05-a37);
  a37=(a05*a06);
  a24=(a24+a37);
  a37=(a27*a24);
  a23=(a23+a37);
  a38=(a38+a23);
  a23=(a21*a30);
  a37=(a13*a06);
  a05=(a05*a22);
  a37=(a37-a05);
  a05=(a37*a25);
  a35=(a24*a36);
  a05=(a05+a35);
  a35=(a27*a05);
  a23=(a23+a35);
  a38=(a38+a23);
  if (res[0]!=0) res[0][8]=a38;
  a01=(a01*a19);
  a29=(a29*a08);
  a18=(a18*a12);
  a29=(a29+a18);
  a01=(a01+a29);
  a01=(a15+a01);
  a17=(a17*a19);
  a29=(a08*a04);
  a18=(a12*a03);
  a29=(a29+a18);
  a31=(a31*a29);
  a17=(a17+a31);
  a01=(a01+a17);
  a11=(a11*a29);
  a17=(a19*a22);
  a04=(a12*a04);
  a03=(a08*a03);
  a04=(a04-a03);
  a03=(a04*a06);
  a17=(a17+a03);
  a03=(a27*a17);
  a11=(a11+a03);
  a01=(a01+a11);
  a21=(a21*a29);
  a06=(a19*a06);
  a04=(a04*a22);
  a06=(a06-a04);
  a04=(a06*a25);
  a22=(a17*a36);
  a04=(a04+a22);
  a27=(a27*a04);
  a21=(a21+a27);
  a01=(a01+a21);
  if (res[0]!=0) res[0][9]=a01;
  a28=(a28*a36);
  a26=(a26*a25);
  a28=(a28-a26);
  a26=arg[0]? arg[0][21] : 0;
  a01=cos(a26);
  a21=(a28*a01);
  a26=sin(a26);
  a27=(a34*a26);
  a21=(a21-a27);
  a27=(a02+a21);
  a27=(a27+a30);
  a06=(a06*a36);
  a17=(a17*a25);
  a06=(a06-a17);
  a17=(a06*a26);
  a22=(a04*a01);
  a17=(a17+a22);
  a27=(a27+a17);
  a22=(a02+a21);
  a22=(a22-a30);
  a22=(a22-a17);
  a11=casadi_fmax(a27,a22);
  a03=(a02-a21);
  a03=(a03+a30);
  a03=(a03-a17);
  a21=(a02-a21);
  a21=(a21-a30);
  a21=(a21+a17);
  a17=casadi_fmax(a03,a21);
  a11=casadi_fmax(a11,a17);
  a17=(a27==a11);
  a30=(a17?a27:0);
  a17=(!a17);
  a31=(a22==a11);
  a37=(a37*a36);
  a24=(a24*a25);
  a37=(a37-a24);
  a24=(a37*a26);
  a25=(a05*a01);
  a24=(a24+a25);
  a25=(a29-a24);
  a25=(a31?a25:0);
  a31=(!a31);
  a36=(a03==a11);
  a28=(a28*a26);
  a34=(a34*a01);
  a28=(a28+a34);
  a06=(a06*a01);
  a04=(a04*a26);
  a06=(a06-a04);
  a04=(a28-a06);
  a04=(a36?a04:0);
  a36=(!a36);
  a37=(a37*a01);
  a05=(a05*a26);
  a37=(a37-a05);
  a05=(a37-a33);
  a36=(a36?a05:0);
  a04=(a04+a36);
  a31=(a31?a04:0);
  a25=(a25+a31);
  a17=(a17?a25:0);
  a30=(a30+a17);
  a17=casadi_sq(a30);
  a25=(a27==a11);
  a31=(a29-a24);
  a31=(a25?a31:0);
  a25=(!a25);
  a04=(a22==a11);
  a36=(a04?a22:0);
  a04=(!a04);
  a05=(a03==a11);
  a26=(a37+a33);
  a26=(a05?a26:0);
  a05=(!a05);
  a01=(a28+a06);
  a05=(a05?a01:0);
  a26=(a26+a05);
  a04=(a04?a26:0);
  a36=(a36+a04);
  a25=(a25?a36:0);
  a31=(a31+a25);
  a25=casadi_sq(a31);
  a17=(a17+a25);
  a25=(a27==a11);
  a36=(a28-a06);
  a36=(a25?a36:0);
  a25=(!a25);
  a04=(a22==a11);
  a26=(a37+a33);
  a26=(a04?a26:0);
  a04=(!a04);
  a05=(a03==a11);
  a01=(a05?a03:0);
  a05=(!a05);
  a34=(a29+a24);
  a05=(a05?a34:0);
  a01=(a01+a05);
  a04=(a04?a01:0);
  a26=(a26+a04);
  a25=(a25?a26:0);
  a36=(a36+a25);
  a25=casadi_sq(a36);
  a17=(a17+a25);
  a27=(a27==a11);
  a37=(a37-a33);
  a37=(a27?a37:0);
  a27=(!a27);
  a22=(a22==a11);
  a28=(a28+a06);
  a28=(a22?a28:0);
  a22=(!a22);
  a03=(a03==a11);
  a29=(a29+a24);
  a29=(a03?a29:0);
  a03=(!a03);
  a03=(a03?a21:0);
  a29=(a29+a03);
  a22=(a22?a29:0);
  a28=(a28+a22);
  a27=(a27?a28:0);
  a37=(a37+a27);
  a27=casadi_sq(a37);
  a17=(a17+a27);
  a17=sqrt(a17);
  a30=(a30/a17);
  a27=casadi_sign(a30);
  a30=(a30*a27);
  if (res[0]!=0) res[0][10]=a30;
  a31=(a31/a17);
  a31=(a31*a27);
  if (res[0]!=0) res[0][11]=a31;
  a36=(a36/a17);
  a36=(a36*a27);
  if (res[0]!=0) res[0][12]=a36;
  a37=(a37/a17);
  a37=(a37*a27);
  if (res[0]!=0) res[0][13]=a37;
  a37=9.5065000000000004e-04;
  a27=(a37*a09);
  a17=-3.4599000000000001e-04;
  a36=(a17*a16);
  a31=1.9273536999999999e-01;
  a30=(a31*a20);
  a36=(a36+a30);
  a27=(a27+a36);
  a00=(a00+a27);
  a27=3.9199999999999999e-02;
  a36=arg[0]? arg[0][7] : 0;
  a30=cos(a36);
  a28=(a09*a30);
  a36=sin(a36);
  a22=(a16*a36);
  a28=(a28+a22);
  a22=(a27*a28);
  a29=-3.5499999999999997e-02;
  a16=(a16*a30);
  a09=(a09*a36);
  a16=(a16-a09);
  a09=(a29*a16);
  a03=5.1999999999999998e-02;
  a21=(a03*a20);
  a09=(a09+a21);
  a22=(a22+a09);
  a00=(a00+a22);
  a22=-2.9999999999999999e-01;
  a09=arg[0]? arg[0][8] : 0;
  a21=cos(a09);
  a24=(a28*a21);
  a09=sin(a09);
  a11=(a20*a09);
  a24=(a24-a11);
  a11=(a22*a24);
  a06=7.0819999999999994e-02;
  a33=(a06*a16);
  a11=(a11+a33);
  a00=(a00+a11);
  a11=2.6979999999999998e-01;
  a33=arg[0]? arg[0][9] : 0;
  a25=cos(a33);
  a26=(a24*a25);
  a28=(a28*a09);
  a20=(a20*a21);
  a28=(a28+a20);
  a33=sin(a33);
  a20=(a28*a33);
  a26=(a26-a20);
  a20=(a11*a26);
  a04=-2.9499999999999999e-03;
  a01=(a04*a16);
  a05=7.4999999999999997e-02;
  a24=(a24*a33);
  a28=(a28*a25);
  a24=(a24+a28);
  a28=(a05*a24);
  a01=(a01+a28);
  a20=(a20+a01);
  a00=(a00+a20);
  a20=8.0000000000000002e-02;
  a01=arg[0]? arg[0][10] : 0;
  a28=cos(a01);
  a34=(a26*a28);
  a01=sin(a01);
  a18=(a24*a01);
  a34=(a34-a18);
  a18=(a20*a34);
  a38=-3.2800000000000003e-02;
  a23=(a38*a16);
  a35=4.0750000000000001e-02;
  a26=(a26*a01);
  a24=(a24*a28);
  a26=(a26+a24);
  a24=(a35*a26);
  a23=(a23+a24);
  a18=(a18+a23);
  a00=(a00+a18);
  if (res[0]!=0) res[0][14]=a00;
  a00=(a37*a13);
  a18=(a17*a07);
  a23=(a31*a14);
  a18=(a18+a23);
  a00=(a00+a18);
  a10=(a10+a00);
  a00=(a13*a30);
  a18=(a07*a36);
  a00=(a00+a18);
  a18=(a27*a00);
  a07=(a07*a30);
  a13=(a13*a36);
  a07=(a07-a13);
  a13=(a29*a07);
  a23=(a03*a14);
  a13=(a13+a23);
  a18=(a18+a13);
  a10=(a10+a18);
  a18=(a00*a21);
  a13=(a14*a09);
  a18=(a18-a13);
  a13=(a22*a18);
  a23=(a06*a07);
  a13=(a13+a23);
  a10=(a10+a13);
  a13=(a18*a25);
  a00=(a00*a09);
  a14=(a14*a21);
  a00=(a00+a14);
  a14=(a00*a33);
  a13=(a13-a14);
  a14=(a11*a13);
  a23=(a04*a07);
  a18=(a18*a33);
  a00=(a00*a25);
  a18=(a18+a00);
  a00=(a05*a18);
  a23=(a23+a00);
  a14=(a14+a23);
  a10=(a10+a14);
  a14=(a13*a28);
  a23=(a18*a01);
  a14=(a14-a23);
  a23=(a20*a14);
  a00=(a38*a07);
  a13=(a13*a01);
  a18=(a18*a28);
  a13=(a13+a18);
  a18=(a35*a13);
  a00=(a00+a18);
  a23=(a23+a00);
  a10=(a10+a23);
  if (res[0]!=0) res[0][15]=a10;
  a37=(a37*a19);
  a17=(a17*a08);
  a31=(a31*a12);
  a17=(a17+a31);
  a37=(a37+a17);
  a15=(a15+a37);
  a37=(a19*a30);
  a17=(a08*a36);
  a37=(a37+a17);
  a27=(a27*a37);
  a08=(a08*a30);
  a19=(a19*a36);
  a08=(a08-a19);
  a29=(a29*a08);
  a03=(a03*a12);
  a29=(a29+a03);
  a27=(a27+a29);
  a15=(a15+a27);
  a27=(a37*a21);
  a29=(a12*a09);
  a27=(a27-a29);
  a22=(a22*a27);
  a06=(a06*a08);
  a22=(a22+a06);
  a15=(a15+a22);
  a22=(a27*a25);
  a37=(a37*a09);
  a12=(a12*a21);
  a37=(a37+a12);
  a12=(a37*a33);
  a22=(a22-a12);
  a11=(a11*a22);
  a04=(a04*a08);
  a27=(a27*a33);
  a37=(a37*a25);
  a27=(a27+a37);
  a05=(a05*a27);
  a04=(a04+a05);
  a11=(a11+a04);
  a15=(a15+a11);
  a11=(a22*a28);
  a04=(a27*a01);
  a11=(a11-a04);
  a20=(a20*a11);
  a38=(a38*a08);
  a22=(a22*a01);
  a27=(a27*a28);
  a22=(a22+a27);
  a35=(a35*a22);
  a38=(a38+a35);
  a20=(a20+a38);
  a15=(a15+a20);
  if (res[0]!=0) res[0][16]=a15;
  a15=arg[0]? arg[0][11] : 0;
  a20=cos(a15);
  a38=(a34*a20);
  a15=sin(a15);
  a35=(a16*a15);
  a38=(a38+a35);
  a35=(a02+a38);
  a27=(a07*a20);
  a28=(a14*a15);
  a27=(a27-a28);
  a35=(a35+a27);
  a35=(a35+a22);
  a28=(a02+a38);
  a28=(a28-a27);
  a28=(a28-a22);
  a01=casadi_fmax(a35,a28);
  a04=(a02-a38);
  a04=(a04+a27);
  a04=(a04-a22);
  a02=(a02-a38);
  a02=(a02-a27);
  a02=(a02+a22);
  a22=casadi_fmax(a04,a02);
  a01=casadi_fmax(a01,a22);
  a22=(a35==a01);
  a27=(a22?a35:0);
  a22=(!a22);
  a38=(a28==a01);
  a05=(a08*a20);
  a37=(a11*a15);
  a05=(a05-a37);
  a37=(a05-a13);
  a37=(a38?a37:0);
  a38=(!a38);
  a25=(a04==a01);
  a11=(a11*a20);
  a08=(a08*a15);
  a11=(a11+a08);
  a08=(a26-a11);
  a08=(a25?a08:0);
  a25=(!a25);
  a14=(a14*a20);
  a07=(a07*a15);
  a14=(a14+a07);
  a16=(a16*a20);
  a34=(a34*a15);
  a16=(a16-a34);
  a34=(a14-a16);
  a25=(a25?a34:0);
  a08=(a08+a25);
  a38=(a38?a08:0);
  a37=(a37+a38);
  a22=(a22?a37:0);
  a27=(a27+a22);
  a22=casadi_sq(a27);
  a37=(a35==a01);
  a38=(a05-a13);
  a38=(a37?a38:0);
  a37=(!a37);
  a08=(a28==a01);
  a25=(a08?a28:0);
  a08=(!a08);
  a34=(a04==a01);
  a15=(a14+a16);
  a15=(a34?a15:0);
  a34=(!a34);
  a20=(a26+a11);
  a34=(a34?a20:0);
  a15=(a15+a34);
  a08=(a08?a15:0);
  a25=(a25+a08);
  a37=(a37?a25:0);
  a38=(a38+a37);
  a37=casadi_sq(a38);
  a22=(a22+a37);
  a37=(a35==a01);
  a25=(a26-a11);
  a25=(a37?a25:0);
  a37=(!a37);
  a08=(a28==a01);
  a15=(a14+a16);
  a15=(a08?a15:0);
  a08=(!a08);
  a34=(a04==a01);
  a20=(a34?a04:0);
  a34=(!a34);
  a07=(a05+a13);
  a34=(a34?a07:0);
  a20=(a20+a34);
  a08=(a08?a20:0);
  a15=(a15+a08);
  a37=(a37?a15:0);
  a25=(a25+a37);
  a37=casadi_sq(a25);
  a22=(a22+a37);
  a35=(a35==a01);
  a14=(a14-a16);
  a14=(a35?a14:0);
  a35=(!a35);
  a28=(a28==a01);
  a26=(a26+a11);
  a26=(a28?a26:0);
  a28=(!a28);
  a04=(a04==a01);
  a05=(a05+a13);
  a05=(a04?a05:0);
  a04=(!a04);
  a04=(a04?a02:0);
  a05=(a05+a04);
  a28=(a28?a05:0);
  a26=(a26+a28);
  a35=(a35?a26:0);
  a14=(a14+a35);
  a35=casadi_sq(a14);
  a22=(a22+a35);
  a22=sqrt(a22);
  a27=(a27/a22);
  a35=casadi_sign(a27);
  a27=(a27*a35);
  if (res[0]!=0) res[0][17]=a27;
  a38=(a38/a22);
  a38=(a38*a35);
  if (res[0]!=0) res[0][18]=a38;
  a25=(a25/a22);
  a25=(a25*a35);
  if (res[0]!=0) res[0][19]=a25;
  a14=(a14/a22);
  a14=(a14*a35);
  if (res[0]!=0) res[0][20]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
