/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) velocity_kinematics_T_jvp_deriv_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {43, 1, 1};
static const casadi_int casadi_s1[3] = {22, 1, 1};
static const casadi_int casadi_s2[3] = {21, 43, 1};

/* velocity_kinematics_T_jvp_deriv:(i0[43],i1[22])->(o0[21x43]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  if (res[0]!=0) res[0][3]=a00;
  if (res[0]!=0) res[0][4]=a00;
  if (res[0]!=0) res[0][5]=a00;
  if (res[0]!=0) res[0][6]=a00;
  if (res[0]!=0) res[0][7]=a00;
  if (res[0]!=0) res[0][8]=a00;
  if (res[0]!=0) res[0][9]=a00;
  if (res[0]!=0) res[0][10]=a00;
  if (res[0]!=0) res[0][11]=a00;
  if (res[0]!=0) res[0][12]=a00;
  if (res[0]!=0) res[0][13]=a00;
  if (res[0]!=0) res[0][14]=a00;
  if (res[0]!=0) res[0][15]=a00;
  if (res[0]!=0) res[0][16]=a00;
  if (res[0]!=0) res[0][17]=a00;
  if (res[0]!=0) res[0][18]=a00;
  if (res[0]!=0) res[0][19]=a00;
  if (res[0]!=0) res[0][20]=a00;
  if (res[0]!=0) res[0][21]=a00;
  if (res[0]!=0) res[0][22]=a00;
  if (res[0]!=0) res[0][23]=a00;
  if (res[0]!=0) res[0][24]=a00;
  if (res[0]!=0) res[0][25]=a00;
  if (res[0]!=0) res[0][26]=a00;
  if (res[0]!=0) res[0][27]=a00;
  if (res[0]!=0) res[0][28]=a00;
  if (res[0]!=0) res[0][29]=a00;
  if (res[0]!=0) res[0][30]=a00;
  if (res[0]!=0) res[0][31]=a00;
  if (res[0]!=0) res[0][32]=a00;
  if (res[0]!=0) res[0][33]=a00;
  if (res[0]!=0) res[0][34]=a00;
  if (res[0]!=0) res[0][35]=a00;
  if (res[0]!=0) res[0][36]=a00;
  if (res[0]!=0) res[0][37]=a00;
  if (res[0]!=0) res[0][38]=a00;
  if (res[0]!=0) res[0][39]=a00;
  if (res[0]!=0) res[0][40]=a00;
  if (res[0]!=0) res[0][41]=a00;
  if (res[0]!=0) res[0][42]=a00;
  if (res[0]!=0) res[0][43]=a00;
  if (res[0]!=0) res[0][44]=a00;
  if (res[0]!=0) res[0][45]=a00;
  if (res[0]!=0) res[0][46]=a00;
  if (res[0]!=0) res[0][47]=a00;
  if (res[0]!=0) res[0][48]=a00;
  if (res[0]!=0) res[0][49]=a00;
  if (res[0]!=0) res[0][50]=a00;
  if (res[0]!=0) res[0][51]=a00;
  if (res[0]!=0) res[0][52]=a00;
  if (res[0]!=0) res[0][53]=a00;
  if (res[0]!=0) res[0][54]=a00;
  if (res[0]!=0) res[0][55]=a00;
  if (res[0]!=0) res[0][56]=a00;
  if (res[0]!=0) res[0][57]=a00;
  if (res[0]!=0) res[0][58]=a00;
  if (res[0]!=0) res[0][59]=a00;
  if (res[0]!=0) res[0][60]=a00;
  if (res[0]!=0) res[0][61]=a00;
  if (res[0]!=0) res[0][62]=a00;
  a01=arg[1]? arg[1][1] : 0;
  a02=2.;
  a03=arg[0]? arg[0][6] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a05=arg[1]? arg[1][2] : 0;
  a06=arg[0]? arg[0][5] : 0;
  a07=(a02*a06);
  a07=(a05*a07);
  a04=(a04-a07);
  if (res[0]!=0) res[0][63]=a04;
  a04=arg[0]? arg[0][4] : 0;
  a07=(a02*a04);
  a07=(a05*a07);
  a08=arg[1]? arg[1][0] : 0;
  a09=(a02*a03);
  a09=(a08*a09);
  a07=(a07-a09);
  if (res[0]!=0) res[0][64]=a07;
  a07=(a02*a06);
  a07=(a08*a07);
  a09=(a02*a04);
  a09=(a01*a09);
  a07=(a07-a09);
  if (res[0]!=0) res[0][65]=a07;
  a07=arg[1]? arg[1][4] : 0;
  a09=(a02*a07);
  if (res[0]!=0) res[0][66]=a09;
  a09=arg[1]? arg[1][5] : 0;
  a10=(a02*a09);
  if (res[0]!=0) res[0][67]=a10;
  a10=arg[1]? arg[1][6] : 0;
  a11=(a02*a10);
  if (res[0]!=0) res[0][68]=a11;
  if (res[0]!=0) res[0][69]=a00;
  if (res[0]!=0) res[0][70]=a00;
  if (res[0]!=0) res[0][71]=a00;
  if (res[0]!=0) res[0][72]=a00;
  if (res[0]!=0) res[0][73]=a00;
  if (res[0]!=0) res[0][74]=a00;
  if (res[0]!=0) res[0][75]=a00;
  if (res[0]!=0) res[0][76]=a00;
  if (res[0]!=0) res[0][77]=a00;
  if (res[0]!=0) res[0][78]=a00;
  if (res[0]!=0) res[0][79]=a00;
  if (res[0]!=0) res[0][80]=a00;
  if (res[0]!=0) res[0][81]=a00;
  if (res[0]!=0) res[0][82]=a00;
  if (res[0]!=0) res[0][83]=a00;
  a11=(a02*a06);
  a11=(a01*a11);
  a12=(a02*a03);
  a12=(a05*a12);
  a11=(a11+a12);
  if (res[0]!=0) res[0][84]=a11;
  a11=(a02*a06);
  a12=(a08*a11);
  a13=(a02*a04);
  a14=(a02*a04);
  a13=(a13+a14);
  a13=(a01*a13);
  a12=(a12-a13);
  a13=arg[0]? arg[0][3] : 0;
  a13=(a02*a13);
  a15=(a05*a13);
  a12=(a12+a15);
  if (res[0]!=0) res[0][85]=a12;
  a12=(a02*a03);
  a15=(a08*a12);
  a16=(a01*a13);
  a15=(a15-a16);
  a16=(a02*a04);
  a17=(a02*a04);
  a16=(a16+a17);
  a16=(a05*a16);
  a15=(a15-a16);
  if (res[0]!=0) res[0][86]=a15;
  a15=arg[1]? arg[1][3] : 0;
  a16=(a02*a15);
  a16=(-a16);
  if (res[0]!=0) res[0][87]=a16;
  a16=(a02*a10);
  if (res[0]!=0) res[0][88]=a16;
  a16=(a02*a09);
  a16=(-a16);
  if (res[0]!=0) res[0][89]=a16;
  if (res[0]!=0) res[0][90]=a00;
  if (res[0]!=0) res[0][91]=a00;
  if (res[0]!=0) res[0][92]=a00;
  if (res[0]!=0) res[0][93]=a00;
  if (res[0]!=0) res[0][94]=a00;
  if (res[0]!=0) res[0][95]=a00;
  if (res[0]!=0) res[0][96]=a00;
  if (res[0]!=0) res[0][97]=a00;
  if (res[0]!=0) res[0][98]=a00;
  if (res[0]!=0) res[0][99]=a00;
  if (res[0]!=0) res[0][100]=a00;
  if (res[0]!=0) res[0][101]=a00;
  if (res[0]!=0) res[0][102]=a00;
  if (res[0]!=0) res[0][103]=a00;
  if (res[0]!=0) res[0][104]=a00;
  a14=(a01*a14);
  a16=(a02*a06);
  a16=(a16+a11);
  a16=(a08*a16);
  a14=(a14-a16);
  a16=(a05*a13);
  a14=(a14-a16);
  if (res[0]!=0) res[0][105]=a14;
  a14=(a02*a04);
  a14=(a08*a14);
  a16=(a02*a03);
  a16=(a05*a16);
  a14=(a14+a16);
  if (res[0]!=0) res[0][106]=a14;
  a14=(a08*a13);
  a16=(a02*a03);
  a11=(a01*a16);
  a14=(a14+a11);
  a11=(a02*a06);
  a18=(a02*a06);
  a11=(a11+a18);
  a11=(a05*a11);
  a14=(a14-a11);
  if (res[0]!=0) res[0][107]=a14;
  a10=(a02*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][108]=a10;
  a10=(a02*a15);
  a10=(-a10);
  if (res[0]!=0) res[0][109]=a10;
  a10=(a02*a07);
  if (res[0]!=0) res[0][110]=a10;
  if (res[0]!=0) res[0][111]=a00;
  if (res[0]!=0) res[0][112]=a00;
  if (res[0]!=0) res[0][113]=a00;
  if (res[0]!=0) res[0][114]=a00;
  if (res[0]!=0) res[0][115]=a00;
  if (res[0]!=0) res[0][116]=a00;
  if (res[0]!=0) res[0][117]=a00;
  if (res[0]!=0) res[0][118]=a00;
  if (res[0]!=0) res[0][119]=a00;
  if (res[0]!=0) res[0][120]=a00;
  if (res[0]!=0) res[0][121]=a00;
  if (res[0]!=0) res[0][122]=a00;
  if (res[0]!=0) res[0][123]=a00;
  if (res[0]!=0) res[0][124]=a00;
  if (res[0]!=0) res[0][125]=a00;
  a10=(a01*a13);
  a14=(a02*a03);
  a14=(a14+a12);
  a14=(a08*a14);
  a10=(a10-a14);
  a17=(a05*a17);
  a10=(a10+a17);
  if (res[0]!=0) res[0][126]=a10;
  a05=(a05*a18);
  a13=(a08*a13);
  a03=(a02*a03);
  a03=(a03+a16);
  a03=(a01*a03);
  a13=(a13+a03);
  a05=(a05-a13);
  if (res[0]!=0) res[0][127]=a05;
  a04=(a02*a04);
  a08=(a08*a04);
  a06=(a02*a06);
  a01=(a01*a06);
  a08=(a08+a01);
  if (res[0]!=0) res[0][128]=a08;
  a09=(a02*a09);
  if (res[0]!=0) res[0][129]=a09;
  a07=(a02*a07);
  a07=(-a07);
  if (res[0]!=0) res[0][130]=a07;
  a02=(a02*a15);
  a02=(-a02);
  if (res[0]!=0) res[0][131]=a02;
  if (res[0]!=0) res[0][132]=a00;
  if (res[0]!=0) res[0][133]=a00;
  if (res[0]!=0) res[0][134]=a00;
  if (res[0]!=0) res[0][135]=a00;
  if (res[0]!=0) res[0][136]=a00;
  if (res[0]!=0) res[0][137]=a00;
  if (res[0]!=0) res[0][138]=a00;
  if (res[0]!=0) res[0][139]=a00;
  if (res[0]!=0) res[0][140]=a00;
  if (res[0]!=0) res[0][141]=a00;
  if (res[0]!=0) res[0][142]=a00;
  if (res[0]!=0) res[0][143]=a00;
  if (res[0]!=0) res[0][144]=a00;
  if (res[0]!=0) res[0][145]=a00;
  if (res[0]!=0) res[0][146]=a00;
  if (res[0]!=0) res[0][147]=a00;
  if (res[0]!=0) res[0][148]=a00;
  if (res[0]!=0) res[0][149]=a00;
  if (res[0]!=0) res[0][150]=a00;
  if (res[0]!=0) res[0][151]=a00;
  if (res[0]!=0) res[0][152]=a00;
  if (res[0]!=0) res[0][153]=a00;
  if (res[0]!=0) res[0][154]=a00;
  if (res[0]!=0) res[0][155]=a00;
  if (res[0]!=0) res[0][156]=a00;
  if (res[0]!=0) res[0][157]=a00;
  if (res[0]!=0) res[0][158]=a00;
  if (res[0]!=0) res[0][159]=a00;
  if (res[0]!=0) res[0][160]=a00;
  if (res[0]!=0) res[0][161]=a00;
  if (res[0]!=0) res[0][162]=a00;
  if (res[0]!=0) res[0][163]=a00;
  if (res[0]!=0) res[0][164]=a00;
  if (res[0]!=0) res[0][165]=a00;
  if (res[0]!=0) res[0][166]=a00;
  if (res[0]!=0) res[0][167]=a00;
  if (res[0]!=0) res[0][168]=a00;
  if (res[0]!=0) res[0][169]=a00;
  if (res[0]!=0) res[0][170]=a00;
  if (res[0]!=0) res[0][171]=a00;
  if (res[0]!=0) res[0][172]=a00;
  if (res[0]!=0) res[0][173]=a00;
  if (res[0]!=0) res[0][174]=a00;
  if (res[0]!=0) res[0][175]=a00;
  if (res[0]!=0) res[0][176]=a00;
  if (res[0]!=0) res[0][177]=a00;
  if (res[0]!=0) res[0][178]=a00;
  if (res[0]!=0) res[0][179]=a00;
  if (res[0]!=0) res[0][180]=a00;
  if (res[0]!=0) res[0][181]=a00;
  if (res[0]!=0) res[0][182]=a00;
  if (res[0]!=0) res[0][183]=a00;
  if (res[0]!=0) res[0][184]=a00;
  if (res[0]!=0) res[0][185]=a00;
  if (res[0]!=0) res[0][186]=a00;
  if (res[0]!=0) res[0][187]=a00;
  if (res[0]!=0) res[0][188]=a00;
  if (res[0]!=0) res[0][189]=a00;
  if (res[0]!=0) res[0][190]=a00;
  if (res[0]!=0) res[0][191]=a00;
  if (res[0]!=0) res[0][192]=a00;
  if (res[0]!=0) res[0][193]=a00;
  if (res[0]!=0) res[0][194]=a00;
  if (res[0]!=0) res[0][195]=a00;
  if (res[0]!=0) res[0][196]=a00;
  if (res[0]!=0) res[0][197]=a00;
  if (res[0]!=0) res[0][198]=a00;
  if (res[0]!=0) res[0][199]=a00;
  if (res[0]!=0) res[0][200]=a00;
  if (res[0]!=0) res[0][201]=a00;
  if (res[0]!=0) res[0][202]=a00;
  if (res[0]!=0) res[0][203]=a00;
  if (res[0]!=0) res[0][204]=a00;
  if (res[0]!=0) res[0][205]=a00;
  if (res[0]!=0) res[0][206]=a00;
  if (res[0]!=0) res[0][207]=a00;
  if (res[0]!=0) res[0][208]=a00;
  if (res[0]!=0) res[0][209]=a00;
  if (res[0]!=0) res[0][210]=a00;
  if (res[0]!=0) res[0][211]=a00;
  if (res[0]!=0) res[0][212]=a00;
  if (res[0]!=0) res[0][213]=a00;
  if (res[0]!=0) res[0][214]=a00;
  if (res[0]!=0) res[0][215]=a00;
  if (res[0]!=0) res[0][216]=a00;
  if (res[0]!=0) res[0][217]=a00;
  if (res[0]!=0) res[0][218]=a00;
  if (res[0]!=0) res[0][219]=a00;
  if (res[0]!=0) res[0][220]=a00;
  if (res[0]!=0) res[0][221]=a00;
  if (res[0]!=0) res[0][222]=a00;
  if (res[0]!=0) res[0][223]=a00;
  if (res[0]!=0) res[0][224]=a00;
  if (res[0]!=0) res[0][225]=a00;
  if (res[0]!=0) res[0][226]=a00;
  if (res[0]!=0) res[0][227]=a00;
  if (res[0]!=0) res[0][228]=a00;
  if (res[0]!=0) res[0][229]=a00;
  if (res[0]!=0) res[0][230]=a00;
  if (res[0]!=0) res[0][231]=a00;
  if (res[0]!=0) res[0][232]=a00;
  if (res[0]!=0) res[0][233]=a00;
  if (res[0]!=0) res[0][234]=a00;
  if (res[0]!=0) res[0][235]=a00;
  if (res[0]!=0) res[0][236]=a00;
  if (res[0]!=0) res[0][237]=a00;
  if (res[0]!=0) res[0][238]=a00;
  if (res[0]!=0) res[0][239]=a00;
  if (res[0]!=0) res[0][240]=a00;
  if (res[0]!=0) res[0][241]=a00;
  if (res[0]!=0) res[0][242]=a00;
  if (res[0]!=0) res[0][243]=a00;
  if (res[0]!=0) res[0][244]=a00;
  if (res[0]!=0) res[0][245]=a00;
  if (res[0]!=0) res[0][246]=a00;
  if (res[0]!=0) res[0][247]=a00;
  if (res[0]!=0) res[0][248]=a00;
  if (res[0]!=0) res[0][249]=a00;
  if (res[0]!=0) res[0][250]=a00;
  if (res[0]!=0) res[0][251]=a00;
  if (res[0]!=0) res[0][252]=a00;
  if (res[0]!=0) res[0][253]=a00;
  if (res[0]!=0) res[0][254]=a00;
  if (res[0]!=0) res[0][255]=a00;
  if (res[0]!=0) res[0][256]=a00;
  if (res[0]!=0) res[0][257]=a00;
  if (res[0]!=0) res[0][258]=a00;
  if (res[0]!=0) res[0][259]=a00;
  if (res[0]!=0) res[0][260]=a00;
  if (res[0]!=0) res[0][261]=a00;
  if (res[0]!=0) res[0][262]=a00;
  if (res[0]!=0) res[0][263]=a00;
  if (res[0]!=0) res[0][264]=a00;
  if (res[0]!=0) res[0][265]=a00;
  if (res[0]!=0) res[0][266]=a00;
  if (res[0]!=0) res[0][267]=a00;
  if (res[0]!=0) res[0][268]=a00;
  if (res[0]!=0) res[0][269]=a00;
  if (res[0]!=0) res[0][270]=a00;
  if (res[0]!=0) res[0][271]=a00;
  if (res[0]!=0) res[0][272]=a00;
  if (res[0]!=0) res[0][273]=a00;
  if (res[0]!=0) res[0][274]=a00;
  if (res[0]!=0) res[0][275]=a00;
  if (res[0]!=0) res[0][276]=a00;
  if (res[0]!=0) res[0][277]=a00;
  if (res[0]!=0) res[0][278]=a00;
  if (res[0]!=0) res[0][279]=a00;
  if (res[0]!=0) res[0][280]=a00;
  if (res[0]!=0) res[0][281]=a00;
  if (res[0]!=0) res[0][282]=a00;
  if (res[0]!=0) res[0][283]=a00;
  if (res[0]!=0) res[0][284]=a00;
  if (res[0]!=0) res[0][285]=a00;
  if (res[0]!=0) res[0][286]=a00;
  if (res[0]!=0) res[0][287]=a00;
  if (res[0]!=0) res[0][288]=a00;
  if (res[0]!=0) res[0][289]=a00;
  if (res[0]!=0) res[0][290]=a00;
  if (res[0]!=0) res[0][291]=a00;
  if (res[0]!=0) res[0][292]=a00;
  if (res[0]!=0) res[0][293]=a00;
  if (res[0]!=0) res[0][294]=a00;
  if (res[0]!=0) res[0][295]=a00;
  if (res[0]!=0) res[0][296]=a00;
  if (res[0]!=0) res[0][297]=a00;
  if (res[0]!=0) res[0][298]=a00;
  if (res[0]!=0) res[0][299]=a00;
  if (res[0]!=0) res[0][300]=a00;
  if (res[0]!=0) res[0][301]=a00;
  if (res[0]!=0) res[0][302]=a00;
  if (res[0]!=0) res[0][303]=a00;
  if (res[0]!=0) res[0][304]=a00;
  if (res[0]!=0) res[0][305]=a00;
  if (res[0]!=0) res[0][306]=a00;
  if (res[0]!=0) res[0][307]=a00;
  if (res[0]!=0) res[0][308]=a00;
  if (res[0]!=0) res[0][309]=a00;
  if (res[0]!=0) res[0][310]=a00;
  if (res[0]!=0) res[0][311]=a00;
  if (res[0]!=0) res[0][312]=a00;
  if (res[0]!=0) res[0][313]=a00;
  if (res[0]!=0) res[0][314]=a00;
  if (res[0]!=0) res[0][315]=a00;
  if (res[0]!=0) res[0][316]=a00;
  if (res[0]!=0) res[0][317]=a00;
  if (res[0]!=0) res[0][318]=a00;
  if (res[0]!=0) res[0][319]=a00;
  if (res[0]!=0) res[0][320]=a00;
  if (res[0]!=0) res[0][321]=a00;
  if (res[0]!=0) res[0][322]=a00;
  if (res[0]!=0) res[0][323]=a00;
  if (res[0]!=0) res[0][324]=a00;
  if (res[0]!=0) res[0][325]=a00;
  if (res[0]!=0) res[0][326]=a00;
  if (res[0]!=0) res[0][327]=a00;
  if (res[0]!=0) res[0][328]=a00;
  if (res[0]!=0) res[0][329]=a00;
  if (res[0]!=0) res[0][330]=a00;
  if (res[0]!=0) res[0][331]=a00;
  if (res[0]!=0) res[0][332]=a00;
  if (res[0]!=0) res[0][333]=a00;
  if (res[0]!=0) res[0][334]=a00;
  if (res[0]!=0) res[0][335]=a00;
  if (res[0]!=0) res[0][336]=a00;
  if (res[0]!=0) res[0][337]=a00;
  if (res[0]!=0) res[0][338]=a00;
  if (res[0]!=0) res[0][339]=a00;
  if (res[0]!=0) res[0][340]=a00;
  if (res[0]!=0) res[0][341]=a00;
  if (res[0]!=0) res[0][342]=a00;
  if (res[0]!=0) res[0][343]=a00;
  if (res[0]!=0) res[0][344]=a00;
  if (res[0]!=0) res[0][345]=a00;
  if (res[0]!=0) res[0][346]=a00;
  if (res[0]!=0) res[0][347]=a00;
  if (res[0]!=0) res[0][348]=a00;
  if (res[0]!=0) res[0][349]=a00;
  if (res[0]!=0) res[0][350]=a00;
  if (res[0]!=0) res[0][351]=a00;
  if (res[0]!=0) res[0][352]=a00;
  if (res[0]!=0) res[0][353]=a00;
  if (res[0]!=0) res[0][354]=a00;
  if (res[0]!=0) res[0][355]=a00;
  if (res[0]!=0) res[0][356]=a00;
  if (res[0]!=0) res[0][357]=a00;
  if (res[0]!=0) res[0][358]=a00;
  if (res[0]!=0) res[0][359]=a00;
  if (res[0]!=0) res[0][360]=a00;
  if (res[0]!=0) res[0][361]=a00;
  if (res[0]!=0) res[0][362]=a00;
  if (res[0]!=0) res[0][363]=a00;
  if (res[0]!=0) res[0][364]=a00;
  if (res[0]!=0) res[0][365]=a00;
  if (res[0]!=0) res[0][366]=a00;
  if (res[0]!=0) res[0][367]=a00;
  if (res[0]!=0) res[0][368]=a00;
  if (res[0]!=0) res[0][369]=a00;
  if (res[0]!=0) res[0][370]=a00;
  if (res[0]!=0) res[0][371]=a00;
  if (res[0]!=0) res[0][372]=a00;
  if (res[0]!=0) res[0][373]=a00;
  if (res[0]!=0) res[0][374]=a00;
  if (res[0]!=0) res[0][375]=a00;
  if (res[0]!=0) res[0][376]=a00;
  if (res[0]!=0) res[0][377]=a00;
  if (res[0]!=0) res[0][378]=a00;
  if (res[0]!=0) res[0][379]=a00;
  if (res[0]!=0) res[0][380]=a00;
  if (res[0]!=0) res[0][381]=a00;
  if (res[0]!=0) res[0][382]=a00;
  if (res[0]!=0) res[0][383]=a00;
  if (res[0]!=0) res[0][384]=a00;
  if (res[0]!=0) res[0][385]=a00;
  if (res[0]!=0) res[0][386]=a00;
  if (res[0]!=0) res[0][387]=a00;
  if (res[0]!=0) res[0][388]=a00;
  if (res[0]!=0) res[0][389]=a00;
  if (res[0]!=0) res[0][390]=a00;
  if (res[0]!=0) res[0][391]=a00;
  if (res[0]!=0) res[0][392]=a00;
  if (res[0]!=0) res[0][393]=a00;
  if (res[0]!=0) res[0][394]=a00;
  if (res[0]!=0) res[0][395]=a00;
  if (res[0]!=0) res[0][396]=a00;
  if (res[0]!=0) res[0][397]=a00;
  if (res[0]!=0) res[0][398]=a00;
  if (res[0]!=0) res[0][399]=a00;
  if (res[0]!=0) res[0][400]=a00;
  if (res[0]!=0) res[0][401]=a00;
  if (res[0]!=0) res[0][402]=a00;
  if (res[0]!=0) res[0][403]=a00;
  if (res[0]!=0) res[0][404]=a00;
  if (res[0]!=0) res[0][405]=a00;
  if (res[0]!=0) res[0][406]=a00;
  if (res[0]!=0) res[0][407]=a00;
  if (res[0]!=0) res[0][408]=a00;
  if (res[0]!=0) res[0][409]=a00;
  if (res[0]!=0) res[0][410]=a00;
  if (res[0]!=0) res[0][411]=a00;
  if (res[0]!=0) res[0][412]=a00;
  if (res[0]!=0) res[0][413]=a00;
  if (res[0]!=0) res[0][414]=a00;
  if (res[0]!=0) res[0][415]=a00;
  if (res[0]!=0) res[0][416]=a00;
  if (res[0]!=0) res[0][417]=a00;
  if (res[0]!=0) res[0][418]=a00;
  if (res[0]!=0) res[0][419]=a00;
  if (res[0]!=0) res[0][420]=a00;
  if (res[0]!=0) res[0][421]=a00;
  if (res[0]!=0) res[0][422]=a00;
  if (res[0]!=0) res[0][423]=a00;
  if (res[0]!=0) res[0][424]=a00;
  if (res[0]!=0) res[0][425]=a00;
  if (res[0]!=0) res[0][426]=a00;
  if (res[0]!=0) res[0][427]=a00;
  if (res[0]!=0) res[0][428]=a00;
  if (res[0]!=0) res[0][429]=a00;
  if (res[0]!=0) res[0][430]=a00;
  if (res[0]!=0) res[0][431]=a00;
  if (res[0]!=0) res[0][432]=a00;
  if (res[0]!=0) res[0][433]=a00;
  if (res[0]!=0) res[0][434]=a00;
  if (res[0]!=0) res[0][435]=a00;
  if (res[0]!=0) res[0][436]=a00;
  if (res[0]!=0) res[0][437]=a00;
  if (res[0]!=0) res[0][438]=a00;
  if (res[0]!=0) res[0][439]=a00;
  if (res[0]!=0) res[0][440]=a00;
  if (res[0]!=0) res[0][441]=a00;
  if (res[0]!=0) res[0][442]=a00;
  if (res[0]!=0) res[0][443]=a00;
  if (res[0]!=0) res[0][444]=a00;
  if (res[0]!=0) res[0][445]=a00;
  if (res[0]!=0) res[0][446]=a00;
  if (res[0]!=0) res[0][447]=a00;
  if (res[0]!=0) res[0][448]=a00;
  if (res[0]!=0) res[0][449]=a00;
  if (res[0]!=0) res[0][450]=a00;
  if (res[0]!=0) res[0][451]=a00;
  if (res[0]!=0) res[0][452]=a00;
  if (res[0]!=0) res[0][453]=a00;
  if (res[0]!=0) res[0][454]=a00;
  if (res[0]!=0) res[0][455]=a00;
  if (res[0]!=0) res[0][456]=a00;
  if (res[0]!=0) res[0][457]=a00;
  if (res[0]!=0) res[0][458]=a00;
  if (res[0]!=0) res[0][459]=a00;
  if (res[0]!=0) res[0][460]=a00;
  if (res[0]!=0) res[0][461]=a00;
  if (res[0]!=0) res[0][462]=a00;
  if (res[0]!=0) res[0][463]=a00;
  if (res[0]!=0) res[0][464]=a00;
  if (res[0]!=0) res[0][465]=a00;
  if (res[0]!=0) res[0][466]=a00;
  if (res[0]!=0) res[0][467]=a00;
  if (res[0]!=0) res[0][468]=a00;
  if (res[0]!=0) res[0][469]=a00;
  if (res[0]!=0) res[0][470]=a00;
  if (res[0]!=0) res[0][471]=a00;
  if (res[0]!=0) res[0][472]=a00;
  if (res[0]!=0) res[0][473]=a00;
  if (res[0]!=0) res[0][474]=a00;
  if (res[0]!=0) res[0][475]=a00;
  if (res[0]!=0) res[0][476]=a00;
  if (res[0]!=0) res[0][477]=a00;
  if (res[0]!=0) res[0][478]=a00;
  if (res[0]!=0) res[0][479]=a00;
  if (res[0]!=0) res[0][480]=a00;
  if (res[0]!=0) res[0][481]=a00;
  if (res[0]!=0) res[0][482]=a00;
  if (res[0]!=0) res[0][483]=a00;
  if (res[0]!=0) res[0][484]=a00;
  if (res[0]!=0) res[0][485]=a00;
  if (res[0]!=0) res[0][486]=a00;
  if (res[0]!=0) res[0][487]=a00;
  if (res[0]!=0) res[0][488]=a00;
  if (res[0]!=0) res[0][489]=a00;
  if (res[0]!=0) res[0][490]=a00;
  if (res[0]!=0) res[0][491]=a00;
  if (res[0]!=0) res[0][492]=a00;
  if (res[0]!=0) res[0][493]=a00;
  if (res[0]!=0) res[0][494]=a00;
  if (res[0]!=0) res[0][495]=a00;
  if (res[0]!=0) res[0][496]=a00;
  if (res[0]!=0) res[0][497]=a00;
  if (res[0]!=0) res[0][498]=a00;
  if (res[0]!=0) res[0][499]=a00;
  if (res[0]!=0) res[0][500]=a00;
  if (res[0]!=0) res[0][501]=a00;
  if (res[0]!=0) res[0][502]=a00;
  if (res[0]!=0) res[0][503]=a00;
  if (res[0]!=0) res[0][504]=a00;
  if (res[0]!=0) res[0][505]=a00;
  if (res[0]!=0) res[0][506]=a00;
  if (res[0]!=0) res[0][507]=a00;
  if (res[0]!=0) res[0][508]=a00;
  if (res[0]!=0) res[0][509]=a00;
  if (res[0]!=0) res[0][510]=a00;
  if (res[0]!=0) res[0][511]=a00;
  if (res[0]!=0) res[0][512]=a00;
  if (res[0]!=0) res[0][513]=a00;
  if (res[0]!=0) res[0][514]=a00;
  if (res[0]!=0) res[0][515]=a00;
  if (res[0]!=0) res[0][516]=a00;
  if (res[0]!=0) res[0][517]=a00;
  if (res[0]!=0) res[0][518]=a00;
  if (res[0]!=0) res[0][519]=a00;
  if (res[0]!=0) res[0][520]=a00;
  if (res[0]!=0) res[0][521]=a00;
  if (res[0]!=0) res[0][522]=a00;
  if (res[0]!=0) res[0][523]=a00;
  if (res[0]!=0) res[0][524]=a00;
  if (res[0]!=0) res[0][525]=a00;
  if (res[0]!=0) res[0][526]=a00;
  if (res[0]!=0) res[0][527]=a00;
  if (res[0]!=0) res[0][528]=a00;
  if (res[0]!=0) res[0][529]=a00;
  if (res[0]!=0) res[0][530]=a00;
  if (res[0]!=0) res[0][531]=a00;
  if (res[0]!=0) res[0][532]=a00;
  if (res[0]!=0) res[0][533]=a00;
  if (res[0]!=0) res[0][534]=a00;
  if (res[0]!=0) res[0][535]=a00;
  if (res[0]!=0) res[0][536]=a00;
  if (res[0]!=0) res[0][537]=a00;
  if (res[0]!=0) res[0][538]=a00;
  if (res[0]!=0) res[0][539]=a00;
  if (res[0]!=0) res[0][540]=a00;
  if (res[0]!=0) res[0][541]=a00;
  if (res[0]!=0) res[0][542]=a00;
  if (res[0]!=0) res[0][543]=a00;
  if (res[0]!=0) res[0][544]=a00;
  if (res[0]!=0) res[0][545]=a00;
  if (res[0]!=0) res[0][546]=a00;
  if (res[0]!=0) res[0][547]=a00;
  if (res[0]!=0) res[0][548]=a00;
  if (res[0]!=0) res[0][549]=a00;
  if (res[0]!=0) res[0][550]=a00;
  if (res[0]!=0) res[0][551]=a00;
  if (res[0]!=0) res[0][552]=a00;
  if (res[0]!=0) res[0][553]=a00;
  if (res[0]!=0) res[0][554]=a00;
  if (res[0]!=0) res[0][555]=a00;
  if (res[0]!=0) res[0][556]=a00;
  if (res[0]!=0) res[0][557]=a00;
  if (res[0]!=0) res[0][558]=a00;
  if (res[0]!=0) res[0][559]=a00;
  if (res[0]!=0) res[0][560]=a00;
  if (res[0]!=0) res[0][561]=a00;
  if (res[0]!=0) res[0][562]=a00;
  if (res[0]!=0) res[0][563]=a00;
  if (res[0]!=0) res[0][564]=a00;
  if (res[0]!=0) res[0][565]=a00;
  if (res[0]!=0) res[0][566]=a00;
  if (res[0]!=0) res[0][567]=a00;
  if (res[0]!=0) res[0][568]=a00;
  if (res[0]!=0) res[0][569]=a00;
  if (res[0]!=0) res[0][570]=a00;
  if (res[0]!=0) res[0][571]=a00;
  if (res[0]!=0) res[0][572]=a00;
  if (res[0]!=0) res[0][573]=a00;
  if (res[0]!=0) res[0][574]=a00;
  if (res[0]!=0) res[0][575]=a00;
  if (res[0]!=0) res[0][576]=a00;
  if (res[0]!=0) res[0][577]=a00;
  if (res[0]!=0) res[0][578]=a00;
  if (res[0]!=0) res[0][579]=a00;
  if (res[0]!=0) res[0][580]=a00;
  if (res[0]!=0) res[0][581]=a00;
  if (res[0]!=0) res[0][582]=a00;
  if (res[0]!=0) res[0][583]=a00;
  if (res[0]!=0) res[0][584]=a00;
  if (res[0]!=0) res[0][585]=a00;
  if (res[0]!=0) res[0][586]=a00;
  if (res[0]!=0) res[0][587]=a00;
  if (res[0]!=0) res[0][588]=a00;
  if (res[0]!=0) res[0][589]=a00;
  if (res[0]!=0) res[0][590]=a00;
  if (res[0]!=0) res[0][591]=a00;
  if (res[0]!=0) res[0][592]=a00;
  if (res[0]!=0) res[0][593]=a00;
  if (res[0]!=0) res[0][594]=a00;
  if (res[0]!=0) res[0][595]=a00;
  if (res[0]!=0) res[0][596]=a00;
  if (res[0]!=0) res[0][597]=a00;
  if (res[0]!=0) res[0][598]=a00;
  if (res[0]!=0) res[0][599]=a00;
  if (res[0]!=0) res[0][600]=a00;
  if (res[0]!=0) res[0][601]=a00;
  if (res[0]!=0) res[0][602]=a00;
  if (res[0]!=0) res[0][603]=a00;
  if (res[0]!=0) res[0][604]=a00;
  if (res[0]!=0) res[0][605]=a00;
  if (res[0]!=0) res[0][606]=a00;
  if (res[0]!=0) res[0][607]=a00;
  if (res[0]!=0) res[0][608]=a00;
  if (res[0]!=0) res[0][609]=a00;
  if (res[0]!=0) res[0][610]=a00;
  if (res[0]!=0) res[0][611]=a00;
  if (res[0]!=0) res[0][612]=a00;
  if (res[0]!=0) res[0][613]=a00;
  if (res[0]!=0) res[0][614]=a00;
  if (res[0]!=0) res[0][615]=a00;
  if (res[0]!=0) res[0][616]=a00;
  if (res[0]!=0) res[0][617]=a00;
  if (res[0]!=0) res[0][618]=a00;
  if (res[0]!=0) res[0][619]=a00;
  if (res[0]!=0) res[0][620]=a00;
  if (res[0]!=0) res[0][621]=a00;
  if (res[0]!=0) res[0][622]=a00;
  if (res[0]!=0) res[0][623]=a00;
  if (res[0]!=0) res[0][624]=a00;
  if (res[0]!=0) res[0][625]=a00;
  if (res[0]!=0) res[0][626]=a00;
  if (res[0]!=0) res[0][627]=a00;
  if (res[0]!=0) res[0][628]=a00;
  if (res[0]!=0) res[0][629]=a00;
  if (res[0]!=0) res[0][630]=a00;
  if (res[0]!=0) res[0][631]=a00;
  if (res[0]!=0) res[0][632]=a00;
  if (res[0]!=0) res[0][633]=a00;
  if (res[0]!=0) res[0][634]=a00;
  if (res[0]!=0) res[0][635]=a00;
  if (res[0]!=0) res[0][636]=a00;
  if (res[0]!=0) res[0][637]=a00;
  if (res[0]!=0) res[0][638]=a00;
  if (res[0]!=0) res[0][639]=a00;
  if (res[0]!=0) res[0][640]=a00;
  if (res[0]!=0) res[0][641]=a00;
  if (res[0]!=0) res[0][642]=a00;
  if (res[0]!=0) res[0][643]=a00;
  if (res[0]!=0) res[0][644]=a00;
  if (res[0]!=0) res[0][645]=a00;
  if (res[0]!=0) res[0][646]=a00;
  if (res[0]!=0) res[0][647]=a00;
  if (res[0]!=0) res[0][648]=a00;
  if (res[0]!=0) res[0][649]=a00;
  if (res[0]!=0) res[0][650]=a00;
  if (res[0]!=0) res[0][651]=a00;
  if (res[0]!=0) res[0][652]=a00;
  if (res[0]!=0) res[0][653]=a00;
  if (res[0]!=0) res[0][654]=a00;
  if (res[0]!=0) res[0][655]=a00;
  if (res[0]!=0) res[0][656]=a00;
  if (res[0]!=0) res[0][657]=a00;
  if (res[0]!=0) res[0][658]=a00;
  if (res[0]!=0) res[0][659]=a00;
  if (res[0]!=0) res[0][660]=a00;
  if (res[0]!=0) res[0][661]=a00;
  if (res[0]!=0) res[0][662]=a00;
  if (res[0]!=0) res[0][663]=a00;
  if (res[0]!=0) res[0][664]=a00;
  if (res[0]!=0) res[0][665]=a00;
  if (res[0]!=0) res[0][666]=a00;
  if (res[0]!=0) res[0][667]=a00;
  if (res[0]!=0) res[0][668]=a00;
  if (res[0]!=0) res[0][669]=a00;
  if (res[0]!=0) res[0][670]=a00;
  if (res[0]!=0) res[0][671]=a00;
  if (res[0]!=0) res[0][672]=a00;
  if (res[0]!=0) res[0][673]=a00;
  if (res[0]!=0) res[0][674]=a00;
  if (res[0]!=0) res[0][675]=a00;
  if (res[0]!=0) res[0][676]=a00;
  if (res[0]!=0) res[0][677]=a00;
  if (res[0]!=0) res[0][678]=a00;
  if (res[0]!=0) res[0][679]=a00;
  if (res[0]!=0) res[0][680]=a00;
  if (res[0]!=0) res[0][681]=a00;
  if (res[0]!=0) res[0][682]=a00;
  if (res[0]!=0) res[0][683]=a00;
  if (res[0]!=0) res[0][684]=a00;
  if (res[0]!=0) res[0][685]=a00;
  if (res[0]!=0) res[0][686]=a00;
  if (res[0]!=0) res[0][687]=a00;
  if (res[0]!=0) res[0][688]=a00;
  if (res[0]!=0) res[0][689]=a00;
  if (res[0]!=0) res[0][690]=a00;
  if (res[0]!=0) res[0][691]=a00;
  if (res[0]!=0) res[0][692]=a00;
  if (res[0]!=0) res[0][693]=a00;
  if (res[0]!=0) res[0][694]=a00;
  if (res[0]!=0) res[0][695]=a00;
  if (res[0]!=0) res[0][696]=a00;
  if (res[0]!=0) res[0][697]=a00;
  if (res[0]!=0) res[0][698]=a00;
  if (res[0]!=0) res[0][699]=a00;
  if (res[0]!=0) res[0][700]=a00;
  if (res[0]!=0) res[0][701]=a00;
  if (res[0]!=0) res[0][702]=a00;
  if (res[0]!=0) res[0][703]=a00;
  if (res[0]!=0) res[0][704]=a00;
  if (res[0]!=0) res[0][705]=a00;
  if (res[0]!=0) res[0][706]=a00;
  if (res[0]!=0) res[0][707]=a00;
  if (res[0]!=0) res[0][708]=a00;
  if (res[0]!=0) res[0][709]=a00;
  if (res[0]!=0) res[0][710]=a00;
  if (res[0]!=0) res[0][711]=a00;
  if (res[0]!=0) res[0][712]=a00;
  if (res[0]!=0) res[0][713]=a00;
  if (res[0]!=0) res[0][714]=a00;
  if (res[0]!=0) res[0][715]=a00;
  if (res[0]!=0) res[0][716]=a00;
  if (res[0]!=0) res[0][717]=a00;
  if (res[0]!=0) res[0][718]=a00;
  if (res[0]!=0) res[0][719]=a00;
  if (res[0]!=0) res[0][720]=a00;
  if (res[0]!=0) res[0][721]=a00;
  if (res[0]!=0) res[0][722]=a00;
  if (res[0]!=0) res[0][723]=a00;
  if (res[0]!=0) res[0][724]=a00;
  if (res[0]!=0) res[0][725]=a00;
  if (res[0]!=0) res[0][726]=a00;
  if (res[0]!=0) res[0][727]=a00;
  if (res[0]!=0) res[0][728]=a00;
  if (res[0]!=0) res[0][729]=a00;
  if (res[0]!=0) res[0][730]=a00;
  if (res[0]!=0) res[0][731]=a00;
  if (res[0]!=0) res[0][732]=a00;
  if (res[0]!=0) res[0][733]=a00;
  if (res[0]!=0) res[0][734]=a00;
  if (res[0]!=0) res[0][735]=a00;
  if (res[0]!=0) res[0][736]=a00;
  if (res[0]!=0) res[0][737]=a00;
  if (res[0]!=0) res[0][738]=a00;
  if (res[0]!=0) res[0][739]=a00;
  if (res[0]!=0) res[0][740]=a00;
  if (res[0]!=0) res[0][741]=a00;
  if (res[0]!=0) res[0][742]=a00;
  if (res[0]!=0) res[0][743]=a00;
  if (res[0]!=0) res[0][744]=a00;
  if (res[0]!=0) res[0][745]=a00;
  if (res[0]!=0) res[0][746]=a00;
  if (res[0]!=0) res[0][747]=a00;
  if (res[0]!=0) res[0][748]=a00;
  if (res[0]!=0) res[0][749]=a00;
  if (res[0]!=0) res[0][750]=a00;
  if (res[0]!=0) res[0][751]=a00;
  if (res[0]!=0) res[0][752]=a00;
  if (res[0]!=0) res[0][753]=a00;
  if (res[0]!=0) res[0][754]=a00;
  if (res[0]!=0) res[0][755]=a00;
  if (res[0]!=0) res[0][756]=a00;
  if (res[0]!=0) res[0][757]=a00;
  if (res[0]!=0) res[0][758]=a00;
  if (res[0]!=0) res[0][759]=a00;
  if (res[0]!=0) res[0][760]=a00;
  if (res[0]!=0) res[0][761]=a00;
  if (res[0]!=0) res[0][762]=a00;
  if (res[0]!=0) res[0][763]=a00;
  if (res[0]!=0) res[0][764]=a00;
  if (res[0]!=0) res[0][765]=a00;
  if (res[0]!=0) res[0][766]=a00;
  if (res[0]!=0) res[0][767]=a00;
  if (res[0]!=0) res[0][768]=a00;
  if (res[0]!=0) res[0][769]=a00;
  if (res[0]!=0) res[0][770]=a00;
  if (res[0]!=0) res[0][771]=a00;
  if (res[0]!=0) res[0][772]=a00;
  if (res[0]!=0) res[0][773]=a00;
  if (res[0]!=0) res[0][774]=a00;
  if (res[0]!=0) res[0][775]=a00;
  if (res[0]!=0) res[0][776]=a00;
  if (res[0]!=0) res[0][777]=a00;
  if (res[0]!=0) res[0][778]=a00;
  if (res[0]!=0) res[0][779]=a00;
  if (res[0]!=0) res[0][780]=a00;
  if (res[0]!=0) res[0][781]=a00;
  if (res[0]!=0) res[0][782]=a00;
  if (res[0]!=0) res[0][783]=a00;
  if (res[0]!=0) res[0][784]=a00;
  if (res[0]!=0) res[0][785]=a00;
  if (res[0]!=0) res[0][786]=a00;
  if (res[0]!=0) res[0][787]=a00;
  if (res[0]!=0) res[0][788]=a00;
  if (res[0]!=0) res[0][789]=a00;
  if (res[0]!=0) res[0][790]=a00;
  if (res[0]!=0) res[0][791]=a00;
  if (res[0]!=0) res[0][792]=a00;
  if (res[0]!=0) res[0][793]=a00;
  if (res[0]!=0) res[0][794]=a00;
  if (res[0]!=0) res[0][795]=a00;
  if (res[0]!=0) res[0][796]=a00;
  if (res[0]!=0) res[0][797]=a00;
  if (res[0]!=0) res[0][798]=a00;
  if (res[0]!=0) res[0][799]=a00;
  if (res[0]!=0) res[0][800]=a00;
  if (res[0]!=0) res[0][801]=a00;
  if (res[0]!=0) res[0][802]=a00;
  if (res[0]!=0) res[0][803]=a00;
  if (res[0]!=0) res[0][804]=a00;
  if (res[0]!=0) res[0][805]=a00;
  if (res[0]!=0) res[0][806]=a00;
  if (res[0]!=0) res[0][807]=a00;
  if (res[0]!=0) res[0][808]=a00;
  if (res[0]!=0) res[0][809]=a00;
  if (res[0]!=0) res[0][810]=a00;
  if (res[0]!=0) res[0][811]=a00;
  if (res[0]!=0) res[0][812]=a00;
  if (res[0]!=0) res[0][813]=a00;
  if (res[0]!=0) res[0][814]=a00;
  if (res[0]!=0) res[0][815]=a00;
  if (res[0]!=0) res[0][816]=a00;
  if (res[0]!=0) res[0][817]=a00;
  if (res[0]!=0) res[0][818]=a00;
  if (res[0]!=0) res[0][819]=a00;
  if (res[0]!=0) res[0][820]=a00;
  if (res[0]!=0) res[0][821]=a00;
  if (res[0]!=0) res[0][822]=a00;
  if (res[0]!=0) res[0][823]=a00;
  if (res[0]!=0) res[0][824]=a00;
  if (res[0]!=0) res[0][825]=a00;
  if (res[0]!=0) res[0][826]=a00;
  if (res[0]!=0) res[0][827]=a00;
  if (res[0]!=0) res[0][828]=a00;
  if (res[0]!=0) res[0][829]=a00;
  if (res[0]!=0) res[0][830]=a00;
  if (res[0]!=0) res[0][831]=a00;
  if (res[0]!=0) res[0][832]=a00;
  if (res[0]!=0) res[0][833]=a00;
  if (res[0]!=0) res[0][834]=a00;
  if (res[0]!=0) res[0][835]=a00;
  if (res[0]!=0) res[0][836]=a00;
  if (res[0]!=0) res[0][837]=a00;
  if (res[0]!=0) res[0][838]=a00;
  if (res[0]!=0) res[0][839]=a00;
  if (res[0]!=0) res[0][840]=a00;
  if (res[0]!=0) res[0][841]=a00;
  if (res[0]!=0) res[0][842]=a00;
  if (res[0]!=0) res[0][843]=a00;
  if (res[0]!=0) res[0][844]=a00;
  if (res[0]!=0) res[0][845]=a00;
  if (res[0]!=0) res[0][846]=a00;
  if (res[0]!=0) res[0][847]=a00;
  if (res[0]!=0) res[0][848]=a00;
  if (res[0]!=0) res[0][849]=a00;
  if (res[0]!=0) res[0][850]=a00;
  if (res[0]!=0) res[0][851]=a00;
  if (res[0]!=0) res[0][852]=a00;
  if (res[0]!=0) res[0][853]=a00;
  if (res[0]!=0) res[0][854]=a00;
  if (res[0]!=0) res[0][855]=a00;
  if (res[0]!=0) res[0][856]=a00;
  if (res[0]!=0) res[0][857]=a00;
  if (res[0]!=0) res[0][858]=a00;
  if (res[0]!=0) res[0][859]=a00;
  if (res[0]!=0) res[0][860]=a00;
  if (res[0]!=0) res[0][861]=a00;
  if (res[0]!=0) res[0][862]=a00;
  if (res[0]!=0) res[0][863]=a00;
  if (res[0]!=0) res[0][864]=a00;
  if (res[0]!=0) res[0][865]=a00;
  if (res[0]!=0) res[0][866]=a00;
  if (res[0]!=0) res[0][867]=a00;
  if (res[0]!=0) res[0][868]=a00;
  if (res[0]!=0) res[0][869]=a00;
  if (res[0]!=0) res[0][870]=a00;
  if (res[0]!=0) res[0][871]=a00;
  if (res[0]!=0) res[0][872]=a00;
  if (res[0]!=0) res[0][873]=a00;
  if (res[0]!=0) res[0][874]=a00;
  if (res[0]!=0) res[0][875]=a00;
  if (res[0]!=0) res[0][876]=a00;
  if (res[0]!=0) res[0][877]=a00;
  if (res[0]!=0) res[0][878]=a00;
  if (res[0]!=0) res[0][879]=a00;
  if (res[0]!=0) res[0][880]=a00;
  if (res[0]!=0) res[0][881]=a00;
  if (res[0]!=0) res[0][882]=a00;
  if (res[0]!=0) res[0][883]=a00;
  if (res[0]!=0) res[0][884]=a00;
  if (res[0]!=0) res[0][885]=a00;
  if (res[0]!=0) res[0][886]=a00;
  if (res[0]!=0) res[0][887]=a00;
  if (res[0]!=0) res[0][888]=a00;
  if (res[0]!=0) res[0][889]=a00;
  if (res[0]!=0) res[0][890]=a00;
  if (res[0]!=0) res[0][891]=a00;
  if (res[0]!=0) res[0][892]=a00;
  if (res[0]!=0) res[0][893]=a00;
  if (res[0]!=0) res[0][894]=a00;
  if (res[0]!=0) res[0][895]=a00;
  if (res[0]!=0) res[0][896]=a00;
  if (res[0]!=0) res[0][897]=a00;
  if (res[0]!=0) res[0][898]=a00;
  if (res[0]!=0) res[0][899]=a00;
  if (res[0]!=0) res[0][900]=a00;
  if (res[0]!=0) res[0][901]=a00;
  if (res[0]!=0) res[0][902]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_jvp_deriv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_jvp_deriv_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_jvp_deriv_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_jvp_deriv_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_jvp_deriv_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_jvp_deriv_release(int mem) {
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_jvp_deriv_incref(void) {
}

CASADI_SYMBOL_EXPORT void velocity_kinematics_T_jvp_deriv_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int velocity_kinematics_T_jvp_deriv_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int velocity_kinematics_T_jvp_deriv_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real velocity_kinematics_T_jvp_deriv_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* velocity_kinematics_T_jvp_deriv_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* velocity_kinematics_T_jvp_deriv_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* velocity_kinematics_T_jvp_deriv_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* velocity_kinematics_T_jvp_deriv_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_jvp_deriv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int velocity_kinematics_T_jvp_deriv_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
