/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[41] = {37, 1, 0, 37, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36};
static const casadi_int casadi_s1[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* kinematics:(i0[37])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=1.9339999999999999e-01;
  a2=1.;
  a3=2.;
  a4=arg[0]? arg[0][4] : 0;
  a5=(a3*a4);
  a6=(a5*a4);
  a7=arg[0]? arg[0][5] : 0;
  a8=(a3*a7);
  a7=(a8*a7);
  a9=(a6+a7);
  a9=(a2-a9);
  a10=(a1*a9);
  a11=4.6500000000000000e-02;
  a12=arg[0]? arg[0][3] : 0;
  a13=(a5*a12);
  a14=arg[0]? arg[0][6] : 0;
  a15=(a8*a14);
  a16=(a13-a15);
  a17=(a11*a16);
  a10=(a10+a17);
  a10=(a0+a10);
  a17=9.5500000000000002e-02;
  a18=arg[0]? arg[0][7] : 0;
  a19=cos(a18);
  a20=(a16*a19);
  a21=(a8*a12);
  a5=(a5*a14);
  a22=(a21+a5);
  a18=sin(a18);
  a23=(a22*a18);
  a20=(a20+a23);
  a20=(a17*a20);
  a10=(a10+a20);
  a20=-2.1299999999999999e-01;
  a23=arg[0]? arg[0][8] : 0;
  a24=sin(a23);
  a25=(a9*a24);
  a26=(a22*a19);
  a27=(a16*a18);
  a26=(a26-a27);
  a23=cos(a23);
  a27=(a26*a23);
  a25=(a25+a27);
  a27=(a20*a25);
  a10=(a10+a27);
  a27=(a9*a23);
  a26=(a26*a24);
  a27=(a27-a26);
  a26=arg[0]? arg[0][9] : 0;
  a28=sin(a26);
  a27=(a27*a28);
  a26=cos(a26);
  a25=(a25*a26);
  a27=(a27+a25);
  a27=(a20*a27);
  a10=(a10+a27);
  if (res[0]!=0) res[0][0]=a10;
  a10=arg[0]? arg[0][1] : 0;
  a13=(a13+a15);
  a15=(a1*a13);
  a3=(a3*a12);
  a12=(a3*a12);
  a7=(a12+a7);
  a7=(a2-a7);
  a27=(a11*a7);
  a15=(a15+a27);
  a15=(a10+a15);
  a27=(a7*a19);
  a8=(a8*a4);
  a3=(a3*a14);
  a14=(a8-a3);
  a4=(a14*a18);
  a27=(a27+a4);
  a27=(a17*a27);
  a15=(a15+a27);
  a27=(a13*a24);
  a4=(a14*a19);
  a25=(a7*a18);
  a4=(a4-a25);
  a25=(a4*a23);
  a27=(a27+a25);
  a25=(a20*a27);
  a15=(a15+a25);
  a25=(a13*a23);
  a4=(a4*a24);
  a25=(a25-a4);
  a25=(a25*a28);
  a27=(a27*a26);
  a25=(a25+a27);
  a25=(a20*a25);
  a15=(a15+a25);
  if (res[0]!=0) res[0][1]=a15;
  a15=arg[0]? arg[0][2] : 0;
  a21=(a21-a5);
  a5=(a1*a21);
  a8=(a8+a3);
  a3=(a11*a8);
  a5=(a5+a3);
  a5=(a15+a5);
  a3=(a8*a19);
  a12=(a12+a6);
  a2=(a2-a12);
  a12=(a2*a18);
  a3=(a3+a12);
  a3=(a17*a3);
  a5=(a5+a3);
  a3=(a21*a24);
  a19=(a2*a19);
  a18=(a8*a18);
  a19=(a19-a18);
  a18=(a19*a23);
  a3=(a3+a18);
  a18=(a20*a3);
  a5=(a5+a18);
  a23=(a21*a23);
  a19=(a19*a24);
  a23=(a23-a19);
  a23=(a23*a28);
  a3=(a3*a26);
  a23=(a23+a3);
  a23=(a20*a23);
  a5=(a5+a23);
  if (res[0]!=0) res[0][2]=a5;
  a5=(a1*a9);
  a23=-4.6500000000000000e-02;
  a3=(a23*a16);
  a5=(a5+a3);
  a5=(a0+a5);
  a3=-9.5500000000000002e-02;
  a26=arg[0]? arg[0][10] : 0;
  a28=cos(a26);
  a19=(a16*a28);
  a26=sin(a26);
  a24=(a22*a26);
  a19=(a19+a24);
  a19=(a3*a19);
  a5=(a5+a19);
  a19=arg[0]? arg[0][11] : 0;
  a24=sin(a19);
  a18=(a9*a24);
  a12=(a22*a28);
  a6=(a16*a26);
  a12=(a12-a6);
  a19=cos(a19);
  a6=(a12*a19);
  a18=(a18+a6);
  a6=(a20*a18);
  a5=(a5+a6);
  a6=(a9*a19);
  a12=(a12*a24);
  a6=(a6-a12);
  a12=arg[0]? arg[0][12] : 0;
  a25=sin(a12);
  a6=(a6*a25);
  a12=cos(a12);
  a18=(a18*a12);
  a6=(a6+a18);
  a6=(a20*a6);
  a5=(a5+a6);
  if (res[0]!=0) res[0][3]=a5;
  a5=(a1*a13);
  a6=(a23*a7);
  a5=(a5+a6);
  a5=(a10+a5);
  a6=(a7*a28);
  a18=(a14*a26);
  a6=(a6+a18);
  a6=(a3*a6);
  a5=(a5+a6);
  a6=(a13*a24);
  a18=(a14*a28);
  a27=(a7*a26);
  a18=(a18-a27);
  a27=(a18*a19);
  a6=(a6+a27);
  a27=(a20*a6);
  a5=(a5+a27);
  a27=(a13*a19);
  a18=(a18*a24);
  a27=(a27-a18);
  a27=(a27*a25);
  a6=(a6*a12);
  a27=(a27+a6);
  a27=(a20*a27);
  a5=(a5+a27);
  if (res[0]!=0) res[0][4]=a5;
  a1=(a1*a21);
  a5=(a23*a8);
  a1=(a1+a5);
  a1=(a15+a1);
  a5=(a8*a28);
  a27=(a2*a26);
  a5=(a5+a27);
  a5=(a3*a5);
  a1=(a1+a5);
  a5=(a21*a24);
  a28=(a2*a28);
  a26=(a8*a26);
  a28=(a28-a26);
  a26=(a28*a19);
  a5=(a5+a26);
  a26=(a20*a5);
  a1=(a1+a26);
  a19=(a21*a19);
  a28=(a28*a24);
  a19=(a19-a28);
  a19=(a19*a25);
  a5=(a5*a12);
  a19=(a19+a5);
  a19=(a20*a19);
  a1=(a1+a19);
  if (res[0]!=0) res[0][5]=a1;
  a1=-1.9339999999999999e-01;
  a19=(a1*a9);
  a5=(a11*a16);
  a19=(a19+a5);
  a19=(a0+a19);
  a5=arg[0]? arg[0][13] : 0;
  a12=cos(a5);
  a25=(a16*a12);
  a5=sin(a5);
  a28=(a22*a5);
  a25=(a25+a28);
  a25=(a17*a25);
  a19=(a19+a25);
  a25=arg[0]? arg[0][14] : 0;
  a28=sin(a25);
  a24=(a9*a28);
  a26=(a22*a12);
  a27=(a16*a5);
  a26=(a26-a27);
  a25=cos(a25);
  a27=(a26*a25);
  a24=(a24+a27);
  a27=(a20*a24);
  a19=(a19+a27);
  a27=(a9*a25);
  a26=(a26*a28);
  a27=(a27-a26);
  a26=arg[0]? arg[0][15] : 0;
  a6=sin(a26);
  a27=(a27*a6);
  a26=cos(a26);
  a24=(a24*a26);
  a27=(a27+a24);
  a27=(a20*a27);
  a19=(a19+a27);
  if (res[0]!=0) res[0][6]=a19;
  a19=(a1*a13);
  a27=(a11*a7);
  a19=(a19+a27);
  a19=(a10+a19);
  a27=(a7*a12);
  a24=(a14*a5);
  a27=(a27+a24);
  a27=(a17*a27);
  a19=(a19+a27);
  a27=(a13*a28);
  a24=(a14*a12);
  a18=(a7*a5);
  a24=(a24-a18);
  a18=(a24*a25);
  a27=(a27+a18);
  a18=(a20*a27);
  a19=(a19+a18);
  a18=(a13*a25);
  a24=(a24*a28);
  a18=(a18-a24);
  a18=(a18*a6);
  a27=(a27*a26);
  a18=(a18+a27);
  a18=(a20*a18);
  a19=(a19+a18);
  if (res[0]!=0) res[0][7]=a19;
  a19=(a1*a21);
  a11=(a11*a8);
  a19=(a19+a11);
  a19=(a15+a19);
  a11=(a8*a12);
  a18=(a2*a5);
  a11=(a11+a18);
  a17=(a17*a11);
  a19=(a19+a17);
  a17=(a21*a28);
  a12=(a2*a12);
  a5=(a8*a5);
  a12=(a12-a5);
  a5=(a12*a25);
  a17=(a17+a5);
  a5=(a20*a17);
  a19=(a19+a5);
  a25=(a21*a25);
  a12=(a12*a28);
  a25=(a25-a12);
  a25=(a25*a6);
  a17=(a17*a26);
  a25=(a25+a17);
  a25=(a20*a25);
  a19=(a19+a25);
  if (res[0]!=0) res[0][8]=a19;
  a19=(a1*a9);
  a25=(a23*a16);
  a19=(a19+a25);
  a0=(a0+a19);
  a19=arg[0]? arg[0][16] : 0;
  a25=cos(a19);
  a17=(a16*a25);
  a19=sin(a19);
  a26=(a22*a19);
  a17=(a17+a26);
  a17=(a3*a17);
  a0=(a0+a17);
  a17=arg[0]? arg[0][17] : 0;
  a26=sin(a17);
  a6=(a9*a26);
  a22=(a22*a25);
  a16=(a16*a19);
  a22=(a22-a16);
  a17=cos(a17);
  a16=(a22*a17);
  a6=(a6+a16);
  a16=(a20*a6);
  a0=(a0+a16);
  a9=(a9*a17);
  a22=(a22*a26);
  a9=(a9-a22);
  a22=arg[0]? arg[0][18] : 0;
  a16=sin(a22);
  a9=(a9*a16);
  a22=cos(a22);
  a6=(a6*a22);
  a9=(a9+a6);
  a9=(a20*a9);
  a0=(a0+a9);
  if (res[0]!=0) res[0][9]=a0;
  a0=(a1*a13);
  a9=(a23*a7);
  a0=(a0+a9);
  a10=(a10+a0);
  a0=(a7*a25);
  a9=(a14*a19);
  a0=(a0+a9);
  a0=(a3*a0);
  a10=(a10+a0);
  a0=(a13*a26);
  a14=(a14*a25);
  a7=(a7*a19);
  a14=(a14-a7);
  a7=(a14*a17);
  a0=(a0+a7);
  a7=(a20*a0);
  a10=(a10+a7);
  a13=(a13*a17);
  a14=(a14*a26);
  a13=(a13-a14);
  a13=(a13*a16);
  a0=(a0*a22);
  a13=(a13+a0);
  a13=(a20*a13);
  a10=(a10+a13);
  if (res[0]!=0) res[0][10]=a10;
  a1=(a1*a21);
  a23=(a23*a8);
  a1=(a1+a23);
  a15=(a15+a1);
  a1=(a8*a25);
  a23=(a2*a19);
  a1=(a1+a23);
  a3=(a3*a1);
  a15=(a15+a3);
  a3=(a21*a26);
  a2=(a2*a25);
  a8=(a8*a19);
  a2=(a2-a8);
  a8=(a2*a17);
  a3=(a3+a8);
  a8=(a20*a3);
  a15=(a15+a8);
  a21=(a21*a17);
  a2=(a2*a26);
  a21=(a21-a2);
  a21=(a21*a16);
  a3=(a3*a22);
  a21=(a21+a3);
  a20=(a20*a21);
  a15=(a15+a20);
  if (res[0]!=0) res[0][11]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
