/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {29, 1, 1};
static const casadi_int casadi_s1[3] = {14, 1, 1};

/* kinematics:(i0[29])->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42;
  a00=arg[0]? arg[0][0] : 0;
  a01=4.7159000000000000e-02;
  a02=1.;
  a03=2.;
  a04=arg[0]? arg[0][5] : 0;
  a05=(a03*a04);
  a06=(a05*a04);
  a07=arg[0]? arg[0][6] : 0;
  a08=(a03*a07);
  a09=(a08*a07);
  a10=(a06+a09);
  a10=(a02-a10);
  a11=(a01*a10);
  a12=6.1249999999999999e-02;
  a13=arg[0]? arg[0][4] : 0;
  a14=(a05*a13);
  a15=arg[0]? arg[0][3] : 0;
  a16=(a08*a15);
  a17=(a14-a16);
  a18=(a12*a17);
  a19=6.6001000000000004e-02;
  a20=(a08*a13);
  a05=(a05*a15);
  a21=(a20+a05);
  a22=(a19*a21);
  a18=(a18+a22);
  a11=(a11+a18);
  a11=(a00+a11);
  a18=-5.6750000000000002e-02;
  a22=(a18*a10);
  a23=1.9949999999999999e-02;
  a24=arg[0]? arg[0][7] : 0;
  a25=cos(a24);
  a26=(a17*a25);
  a27=sin(a24);
  a28=(a21*a27);
  a26=(a26+a28);
  a28=(a23*a26);
  a22=(a22+a28);
  a11=(a11+a22);
  a22=3.8300000000000001e-02;
  a28=(a22*a26);
  a29=-1.6500000000000001e-01;
  a30=arg[0]? arg[0][8] : 0;
  a31=sin(a30);
  a32=(a10*a31);
  a33=(a21*a25);
  a34=(a17*a27);
  a33=(a33-a34);
  a34=cos(a30);
  a35=(a33*a34);
  a32=(a32+a35);
  a35=(a29*a32);
  a28=(a28+a35);
  a11=(a11+a28);
  a28=2.7050000000000001e-02;
  a26=(a28*a26);
  a35=(a10*a34);
  a33=(a33*a31);
  a35=(a35-a33);
  a33=arg[0]? arg[0][9] : 0;
  a36=sin(a33);
  a35=(a35*a36);
  a37=cos(a33);
  a32=(a32*a37);
  a35=(a35+a32);
  a35=(a29*a35);
  a26=(a26+a35);
  a11=(a11+a26);
  if (res[0]!=0) res[0][0]=a11;
  a11=arg[0]? arg[0][1] : 0;
  a14=(a14+a16);
  a16=(a01*a14);
  a26=(a03*a13);
  a35=(a26*a13);
  a09=(a35+a09);
  a09=(a02-a09);
  a32=(a12*a09);
  a08=(a08*a04);
  a26=(a26*a15);
  a38=(a08-a26);
  a39=(a19*a38);
  a32=(a32+a39);
  a16=(a16+a32);
  a16=(a11+a16);
  a32=(a18*a14);
  a39=(a09*a25);
  a40=(a38*a27);
  a39=(a39+a40);
  a40=(a23*a39);
  a32=(a32+a40);
  a16=(a16+a32);
  a32=(a22*a39);
  a40=(a14*a31);
  a41=(a38*a25);
  a42=(a09*a27);
  a41=(a41-a42);
  a42=(a41*a34);
  a40=(a40+a42);
  a42=(a29*a40);
  a32=(a32+a42);
  a16=(a16+a32);
  a39=(a28*a39);
  a32=(a14*a34);
  a41=(a41*a31);
  a32=(a32-a41);
  a32=(a32*a36);
  a40=(a40*a37);
  a32=(a32+a40);
  a32=(a29*a32);
  a39=(a39+a32);
  a16=(a16+a39);
  if (res[0]!=0) res[0][1]=a16;
  a16=arg[0]? arg[0][2] : 0;
  a20=(a20-a05);
  a05=(a01*a20);
  a08=(a08+a26);
  a12=(a12*a08);
  a35=(a35+a06);
  a02=(a02-a35);
  a35=(a19*a02);
  a12=(a12+a35);
  a05=(a05+a12);
  a05=(a16+a05);
  a12=(a18*a20);
  a35=(a08*a25);
  a06=(a02*a27);
  a35=(a35+a06);
  a23=(a23*a35);
  a12=(a12+a23);
  a05=(a05+a12);
  a22=(a22*a35);
  a12=(a20*a31);
  a25=(a02*a25);
  a27=(a08*a27);
  a25=(a25-a27);
  a27=(a25*a34);
  a12=(a12+a27);
  a27=(a29*a12);
  a22=(a22+a27);
  a05=(a05+a22);
  a28=(a28*a35);
  a34=(a20*a34);
  a25=(a25*a31);
  a34=(a34-a25);
  a34=(a34*a36);
  a12=(a12*a37);
  a34=(a34+a12);
  a34=(a29*a34);
  a28=(a28+a34);
  a05=(a05+a28);
  if (res[0]!=0) res[0][2]=a05;
  a05=casadi_sq(a15);
  a28=casadi_sq(a13);
  a05=(a05+a28);
  a28=casadi_sq(a04);
  a05=(a05+a28);
  a28=casadi_sq(a07);
  a05=(a05+a28);
  a28=9.9999999999999992e-25;
  a05=(a05+a28);
  a05=sqrt(a05);
  a15=(a15/a05);
  a34=casadi_sq(a24);
  a34=(a34+a28);
  a34=sqrt(a34);
  a12=(a34/a03);
  a37=cos(a12);
  a36=(a15*a37);
  a13=(a13/a05);
  a12=sin(a12);
  a12=(a12/a34);
  a24=(a24*a12);
  a12=(a13*a24);
  a36=(a36-a12);
  a12=casadi_sq(a30);
  a12=(a12+a28);
  a12=sqrt(a12);
  a34=(a12/a03);
  a25=cos(a34);
  a31=(a36*a25);
  a04=(a04/a05);
  a35=(a04*a37);
  a07=(a07/a05);
  a05=(a07*a24);
  a35=(a35+a05);
  a34=sin(a34);
  a34=(a34/a12);
  a30=(a30*a34);
  a34=(a35*a30);
  a31=(a31-a34);
  a34=casadi_sq(a33);
  a34=(a34+a28);
  a34=sqrt(a34);
  a12=(a34/a03);
  a05=cos(a12);
  a22=(a31*a05);
  a36=(a36*a30);
  a35=(a35*a25);
  a36=(a36+a35);
  a12=sin(a12);
  a12=(a12/a34);
  a33=(a33*a12);
  a12=(a36*a33);
  a22=(a22-a12);
  a12=arg[0]? arg[0][10] : 0;
  a34=casadi_sq(a12);
  a34=(a34+a28);
  a34=sqrt(a34);
  a35=(a34/a03);
  a27=cos(a35);
  a23=(a22*a27);
  a31=(a31*a33);
  a36=(a36*a05);
  a31=(a31+a36);
  a35=sin(a35);
  a35=(a35/a34);
  a12=(a12*a35);
  a35=(a31*a12);
  a23=(a23-a35);
  if (res[0]!=0) res[0][3]=a23;
  a23=(a15*a24);
  a35=(a13*a37);
  a23=(a23+a35);
  a35=(a23*a25);
  a37=(a07*a37);
  a24=(a04*a24);
  a37=(a37-a24);
  a24=(a37*a30);
  a35=(a35-a24);
  a24=(a35*a05);
  a23=(a23*a30);
  a37=(a37*a25);
  a23=(a23+a37);
  a37=(a23*a33);
  a24=(a24-a37);
  a37=(a24*a27);
  a35=(a35*a33);
  a23=(a23*a05);
  a35=(a35+a23);
  a23=(a35*a12);
  a37=(a37-a23);
  if (res[0]!=0) res[0][4]=a37;
  a22=(a22*a12);
  a31=(a31*a27);
  a22=(a22+a31);
  if (res[0]!=0) res[0][5]=a22;
  a24=(a24*a12);
  a35=(a35*a27);
  a24=(a24+a35);
  if (res[0]!=0) res[0][6]=a24;
  a24=(a01*a10);
  a35=-6.1249999999999999e-02;
  a27=(a35*a17);
  a12=(a19*a21);
  a27=(a27+a12);
  a24=(a24+a27);
  a00=(a00+a24);
  a24=(a18*a10);
  a27=-1.9949999999999999e-02;
  a12=arg[0]? arg[0][11] : 0;
  a22=cos(a12);
  a31=(a17*a22);
  a37=sin(a12);
  a23=(a21*a37);
  a31=(a31+a23);
  a23=(a27*a31);
  a24=(a24+a23);
  a00=(a00+a24);
  a24=-3.8300000000000001e-02;
  a23=(a24*a31);
  a05=arg[0]? arg[0][12] : 0;
  a33=sin(a05);
  a25=(a10*a33);
  a21=(a21*a22);
  a17=(a17*a37);
  a21=(a21-a17);
  a17=cos(a05);
  a30=(a21*a17);
  a25=(a25+a30);
  a30=(a29*a25);
  a23=(a23+a30);
  a00=(a00+a23);
  a23=-2.7050000000000001e-02;
  a31=(a23*a31);
  a10=(a10*a17);
  a21=(a21*a33);
  a10=(a10-a21);
  a21=arg[0]? arg[0][13] : 0;
  a30=sin(a21);
  a10=(a10*a30);
  a34=cos(a21);
  a25=(a25*a34);
  a10=(a10+a25);
  a10=(a29*a10);
  a31=(a31+a10);
  a00=(a00+a31);
  if (res[0]!=0) res[0][7]=a00;
  a00=(a01*a14);
  a31=(a35*a09);
  a10=(a19*a38);
  a31=(a31+a10);
  a00=(a00+a31);
  a11=(a11+a00);
  a00=(a18*a14);
  a31=(a09*a22);
  a10=(a38*a37);
  a31=(a31+a10);
  a10=(a27*a31);
  a00=(a00+a10);
  a11=(a11+a00);
  a00=(a24*a31);
  a10=(a14*a33);
  a38=(a38*a22);
  a09=(a09*a37);
  a38=(a38-a09);
  a09=(a38*a17);
  a10=(a10+a09);
  a09=(a29*a10);
  a00=(a00+a09);
  a11=(a11+a00);
  a31=(a23*a31);
  a14=(a14*a17);
  a38=(a38*a33);
  a14=(a14-a38);
  a14=(a14*a30);
  a10=(a10*a34);
  a14=(a14+a10);
  a14=(a29*a14);
  a31=(a31+a14);
  a11=(a11+a31);
  if (res[0]!=0) res[0][8]=a11;
  a01=(a01*a20);
  a35=(a35*a08);
  a19=(a19*a02);
  a35=(a35+a19);
  a01=(a01+a35);
  a16=(a16+a01);
  a18=(a18*a20);
  a01=(a08*a22);
  a35=(a02*a37);
  a01=(a01+a35);
  a27=(a27*a01);
  a18=(a18+a27);
  a16=(a16+a18);
  a24=(a24*a01);
  a18=(a20*a33);
  a02=(a02*a22);
  a08=(a08*a37);
  a02=(a02-a08);
  a08=(a02*a17);
  a18=(a18+a08);
  a08=(a29*a18);
  a24=(a24+a08);
  a16=(a16+a24);
  a23=(a23*a01);
  a20=(a20*a17);
  a02=(a02*a33);
  a20=(a20-a02);
  a20=(a20*a30);
  a18=(a18*a34);
  a20=(a20+a18);
  a29=(a29*a20);
  a23=(a23+a29);
  a16=(a16+a23);
  if (res[0]!=0) res[0][9]=a16;
  a16=casadi_sq(a12);
  a16=(a16+a28);
  a16=sqrt(a16);
  a23=(a16/a03);
  a29=cos(a23);
  a20=(a15*a29);
  a23=sin(a23);
  a23=(a23/a16);
  a12=(a12*a23);
  a23=(a13*a12);
  a20=(a20-a23);
  a23=casadi_sq(a05);
  a23=(a23+a28);
  a23=sqrt(a23);
  a16=(a23/a03);
  a18=cos(a16);
  a34=(a20*a18);
  a30=(a04*a29);
  a02=(a07*a12);
  a30=(a30+a02);
  a16=sin(a16);
  a16=(a16/a23);
  a05=(a05*a16);
  a16=(a30*a05);
  a34=(a34-a16);
  a16=casadi_sq(a21);
  a16=(a16+a28);
  a16=sqrt(a16);
  a23=(a16/a03);
  a02=cos(a23);
  a33=(a34*a02);
  a20=(a20*a05);
  a30=(a30*a18);
  a20=(a20+a30);
  a23=sin(a23);
  a23=(a23/a16);
  a21=(a21*a23);
  a23=(a20*a21);
  a33=(a33-a23);
  a23=arg[0]? arg[0][14] : 0;
  a16=casadi_sq(a23);
  a16=(a16+a28);
  a16=sqrt(a16);
  a03=(a16/a03);
  a28=cos(a03);
  a30=(a33*a28);
  a34=(a34*a21);
  a20=(a20*a02);
  a34=(a34+a20);
  a03=sin(a03);
  a03=(a03/a16);
  a23=(a23*a03);
  a03=(a34*a23);
  a30=(a30-a03);
  if (res[0]!=0) res[0][10]=a30;
  a15=(a15*a12);
  a13=(a13*a29);
  a15=(a15+a13);
  a13=(a15*a18);
  a07=(a07*a29);
  a04=(a04*a12);
  a07=(a07-a04);
  a04=(a07*a05);
  a13=(a13-a04);
  a04=(a13*a02);
  a15=(a15*a05);
  a07=(a07*a18);
  a15=(a15+a07);
  a07=(a15*a21);
  a04=(a04-a07);
  a07=(a04*a28);
  a13=(a13*a21);
  a15=(a15*a02);
  a13=(a13+a15);
  a15=(a13*a23);
  a07=(a07-a15);
  if (res[0]!=0) res[0][11]=a07;
  a33=(a33*a23);
  a34=(a34*a28);
  a33=(a33+a34);
  if (res[0]!=0) res[0][12]=a33;
  a04=(a04*a23);
  a13=(a13*a28);
  a04=(a04+a13);
  if (res[0]!=0) res[0][13]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
