/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};

/* kinematics:(i0[13])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=-9.9999394454554758e-01;
  a01=1.;
  a02=2.;
  a03=arg[0]? arg[0][4] : 0;
  a04=(a02*a03);
  a05=(a04*a03);
  a06=arg[0]? arg[0][6] : 0;
  a07=(a02*a06);
  a06=(a07*a06);
  a05=(a05+a06);
  a05=(a01-a05);
  a08=arg[0]? arg[0][5] : 0;
  a09=(a02*a08);
  a10=(a09*a03);
  a11=arg[0]? arg[0][3] : 0;
  a12=(a07*a11);
  a13=(a10-a12);
  a14=casadi_sq(a13);
  a15=casadi_sq(a05);
  a16=(a07*a08);
  a04=(a04*a11);
  a16=(a16+a04);
  a04=casadi_sq(a16);
  a15=(a15+a04);
  a14=(a14+a15);
  a14=sqrt(a14);
  a05=(a05/a14);
  a08=(a09*a08);
  a08=(a08+a06);
  a08=(a01-a08);
  a06=casadi_sq(a08);
  a10=(a10+a12);
  a12=casadi_sq(a10);
  a07=(a07*a03);
  a09=(a09*a11);
  a07=(a07-a09);
  a09=casadi_sq(a07);
  a12=(a12+a09);
  a06=(a06+a12);
  a06=sqrt(a06);
  a08=(a08/a06);
  a12=(a08*a05);
  a10=(a10/a06);
  a13=(a13/a14);
  a09=(a10*a13);
  a12=(a12-a09);
  a09=(a05*a12);
  a16=(a16/a14);
  a07=(a07/a06);
  a06=(a07*a13);
  a08=(a08*a16);
  a06=(a06-a08);
  a08=(a16*a06);
  a09=(a09-a08);
  a08=(a05+a12);
  a08=(a09+a08);
  a14=(a08-a01);
  a14=(a14/a02);
  a11=(a00<=a14);
  a03=6.0554544523933429e-06;
  a15=2.9999939445455475e+00;
  a15=(a08<=a15);
  a04=(a00<=a08);
  a17=acos(a14);
  a17=(a04?a17:0);
  a04=(!a04);
  a18=3.1415926535897931e+00;
  a19=(a01-a14);
  a19=(a02*a19);
  a20=4.9303806576313238e-32;
  a19=(a19+a20);
  a19=sqrt(a19);
  a18=(a18-a19);
  a04=(a04?a18:0);
  a17=(a17+a04);
  a17=(a15?a17:0);
  a15=(!a15);
  a15=(a15?a19:0);
  a17=(a17+a15);
  a03=(a03<=a17);
  a15=sin(a17);
  a17=(a17/a15);
  a17=(a03?a17:0);
  a03=(!a03);
  a15=5.0000000000000000e-01;
  a19=(a16-a06);
  a19=(a15*a19);
  a04=casadi_sq(a19);
  a10=(a10*a16);
  a07=(a07*a05);
  a10=(a10-a07);
  a07=(a13*a06);
  a18=(a05*a10);
  a07=(a07-a18);
  a18=(a10-a07);
  a18=(a15*a18);
  a21=casadi_sq(a18);
  a22=(a16*a10);
  a23=(a13*a12);
  a22=(a22-a23);
  a23=(a22-a13);
  a15=(a15*a23);
  a23=casadi_sq(a15);
  a21=(a21+a23);
  a04=(a04+a21);
  a21=6.;
  a21=(a04/a21);
  a21=(a01+a21);
  a23=3.;
  a04=casadi_sq(a04);
  a23=(a23*a04);
  a04=40.;
  a23=(a23/a04);
  a21=(a21+a23);
  a03=(a03?a21:0);
  a17=(a17+a03);
  a19=(a17*a19);
  a19=(a11?a19:0);
  a11=(!a11);
  a05=(a02*a05);
  a05=(a05-a08);
  a05=(a05+a01);
  a09=(a02*a09);
  a09=(a09-a08);
  a09=(a09+a01);
  a03=(a05<=a09);
  a12=(a02*a12);
  a12=(a12-a08);
  a12=(a12+a01);
  a08=(a12<=a09);
  a21=2.2204460492503131e-16;
  a23=(a09+a21);
  a23=(a23+a20);
  a23=sqrt(a23);
  a04=(a06<=a16);
  a24=(a04?a01:0);
  a04=(!a04);
  a25=-1.;
  a04=(a04?a25:0);
  a24=(a24+a04);
  a23=(a23*a24);
  a24=(a23/a02);
  a04=casadi_sq(a24);
  a26=(a22+a13);
  a27=(a02*a23);
  a26=(a26/a27);
  a27=casadi_sq(a26);
  a28=(a07+a10);
  a29=(a02*a23);
  a28=(a28/a29);
  a29=casadi_sq(a28);
  a27=(a27+a29);
  a04=(a04+a27);
  a04=sqrt(a04);
  a27=(a16-a06);
  a23=(a02*a23);
  a27=(a27/a23);
  a27=atan2(a04,a27);
  a27=(a02*a27);
  a27=(a08?a27:0);
  a08=(!a08);
  a23=(a10+a07);
  a29=(a12+a21);
  a29=(a29+a20);
  a29=sqrt(a29);
  a30=(a13<=a22);
  a31=(a30?a01:0);
  a30=(!a30);
  a30=(a30?a25:0);
  a31=(a31+a30);
  a29=(a29*a31);
  a31=(a02*a29);
  a23=(a23/a31);
  a31=casadi_sq(a23);
  a30=(a06+a16);
  a32=(a02*a29);
  a30=(a30/a32);
  a32=casadi_sq(a30);
  a33=(a29/a02);
  a34=casadi_sq(a33);
  a32=(a32+a34);
  a31=(a31+a32);
  a31=sqrt(a31);
  a32=(a22-a13);
  a29=(a02*a29);
  a32=(a32/a29);
  a32=atan2(a31,a32);
  a32=(a02*a32);
  a08=(a08?a32:0);
  a27=(a27+a08);
  a27=(a03?a27:0);
  a03=(!a03);
  a08=(a12<=a05);
  a13=(a13+a22);
  a21=(a05+a21);
  a21=(a21+a20);
  a21=sqrt(a21);
  a20=(a07<=a10);
  a01=(a20?a01:0);
  a20=(!a20);
  a20=(a20?a25:0);
  a01=(a01+a20);
  a21=(a21*a01);
  a01=(a02*a21);
  a13=(a13/a01);
  a01=casadi_sq(a13);
  a20=(a21/a02);
  a25=casadi_sq(a20);
  a16=(a16+a06);
  a06=(a02*a21);
  a16=(a16/a06);
  a06=casadi_sq(a16);
  a25=(a25+a06);
  a01=(a01+a25);
  a01=sqrt(a01);
  a10=(a10-a07);
  a21=(a02*a21);
  a10=(a10/a21);
  a10=atan2(a01,a10);
  a02=(a02*a10);
  a02=(a08?a02:0);
  a08=(!a08);
  a08=(a08?a32:0);
  a02=(a02+a08);
  a03=(a03?a02:0);
  a27=(a27+a03);
  a03=(a05<=a09);
  a02=(a12<=a09);
  a24=(a24/a04);
  a24=(a02?a24:0);
  a02=(!a02);
  a23=(a23/a31);
  a02=(a02?a23:0);
  a24=(a24+a02);
  a24=(a03?a24:0);
  a03=(!a03);
  a02=(a12<=a05);
  a13=(a13/a01);
  a13=(a02?a13:0);
  a02=(!a02);
  a02=(a02?a23:0);
  a13=(a13+a02);
  a03=(a03?a13:0);
  a24=(a24+a03);
  a24=(a27*a24);
  a11=(a11?a24:0);
  a19=(a19+a11);
  if (res[0]!=0) res[0][3]=a19;
  a19=(a00<=a14);
  a18=(a17*a18);
  a18=(a19?a18:0);
  a19=(!a19);
  a11=(a05<=a09);
  a24=(a12<=a09);
  a26=(a26/a04);
  a26=(a24?a26:0);
  a24=(!a24);
  a30=(a30/a31);
  a24=(a24?a30:0);
  a26=(a26+a24);
  a26=(a11?a26:0);
  a11=(!a11);
  a24=(a12<=a05);
  a20=(a20/a01);
  a20=(a24?a20:0);
  a24=(!a24);
  a24=(a24?a30:0);
  a20=(a20+a24);
  a11=(a11?a20:0);
  a26=(a26+a11);
  a26=(a27*a26);
  a19=(a19?a26:0);
  a18=(a18+a19);
  if (res[0]!=0) res[0][4]=a18;
  a00=(a00<=a14);
  a17=(a17*a15);
  a17=(a00?a17:0);
  a00=(!a00);
  a15=(a05<=a09);
  a09=(a12<=a09);
  a28=(a28/a04);
  a28=(a09?a28:0);
  a09=(!a09);
  a33=(a33/a31);
  a09=(a09?a33:0);
  a28=(a28+a09);
  a28=(a15?a28:0);
  a15=(!a15);
  a12=(a12<=a05);
  a16=(a16/a01);
  a16=(a12?a16:0);
  a12=(!a12);
  a12=(a12?a33:0);
  a16=(a16+a12);
  a15=(a15?a16:0);
  a28=(a28+a15);
  a27=(a27*a28);
  a00=(a00?a27:0);
  a17=(a17+a00);
  if (res[0]!=0) res[0][5]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
