/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_velocity_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* kinematics_velocity:(i0[13])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a8, a9;
  a0=1.;
  a1=2.;
  a2=arg[0]? arg[0][6] : 0;
  a3=(a1*a2);
  a4=(a3*a2);
  a5=arg[0]? arg[0][5] : 0;
  a6=(a1*a5);
  a7=(a6*a5);
  a4=(a4+a7);
  a4=(a0-a4);
  a7=arg[0]? arg[0][7] : 0;
  a4=(a4*a7);
  a8=arg[0]? arg[0][4] : 0;
  a6=(a6*a8);
  a9=arg[0]? arg[0][3] : 0;
  a10=(a1*a9);
  a11=(a10*a2);
  a6=(a6-a11);
  a11=arg[0]? arg[0][8] : 0;
  a6=(a6*a11);
  a4=(a4+a6);
  a6=(a10*a5);
  a3=(a3*a8);
  a6=(a6+a3);
  a3=arg[0]? arg[0][9] : 0;
  a6=(a6*a3);
  a4=(a4+a6);
  if (res[0]!=0) res[0][0]=a4;
  a4=(a10*a2);
  a6=(a1*a8);
  a12=(a6*a5);
  a4=(a4+a12);
  a4=(a4*a7);
  a12=(a1*a2);
  a13=(a12*a2);
  a6=(a6*a8);
  a13=(a13+a6);
  a13=(a0-a13);
  a13=(a13*a11);
  a4=(a4+a13);
  a12=(a12*a5);
  a13=(a10*a8);
  a12=(a12-a13);
  a12=(a12*a3);
  a4=(a4+a12);
  if (res[0]!=0) res[0][1]=a4;
  a4=(a1*a8);
  a12=(a4*a2);
  a13=(a10*a5);
  a12=(a12-a13);
  a12=(a12*a7);
  a10=(a10*a8);
  a7=(a1*a5);
  a13=(a7*a2);
  a10=(a10+a13);
  a10=(a10*a11);
  a12=(a12+a10);
  a7=(a7*a5);
  a4=(a4*a8);
  a7=(a7+a4);
  a7=(a0-a7);
  a7=(a7*a3);
  a12=(a12+a7);
  if (res[0]!=0) res[0][2]=a12;
  a12=-9.9999394454554758e-01;
  a7=(a1*a8);
  a3=(a7*a8);
  a4=(a1*a2);
  a10=(a4*a2);
  a3=(a3+a10);
  a3=(a0-a3);
  a11=(a1*a5);
  a13=(a11*a8);
  a6=(a4*a9);
  a14=(a13-a6);
  a15=casadi_sq(a14);
  a16=casadi_sq(a3);
  a17=(a4*a5);
  a18=(a7*a9);
  a17=(a17+a18);
  a18=casadi_sq(a17);
  a16=(a16+a18);
  a15=(a15+a16);
  a15=sqrt(a15);
  a16=(a3/a15);
  a18=(a11*a5);
  a18=(a18+a10);
  a18=(a0-a18);
  a10=casadi_sq(a18);
  a13=(a13+a6);
  a6=casadi_sq(a13);
  a19=(a4*a8);
  a20=(a11*a9);
  a19=(a19-a20);
  a20=casadi_sq(a19);
  a6=(a6+a20);
  a10=(a10+a6);
  a10=sqrt(a10);
  a6=(a18/a10);
  a20=(a6*a16);
  a21=(a13/a10);
  a22=(a14/a15);
  a23=(a21*a22);
  a20=(a20-a23);
  a23=(a16*a20);
  a24=(a17/a15);
  a25=(a19/a10);
  a26=(a25*a22);
  a27=(a6*a24);
  a26=(a26-a27);
  a27=(a24*a26);
  a23=(a23-a27);
  a27=(a16+a20);
  a27=(a23+a27);
  a28=(a27-a0);
  a28=(a28/a1);
  a29=(a12<=a28);
  a30=5.0000000000000000e-01;
  a31=(a24-a26);
  a32=(a30*a31);
  a33=6.0554544523933429e-06;
  a34=2.9999939445455475e+00;
  a34=(a27<=a34);
  a35=(a12<=a27);
  a36=acos(a28);
  a36=(a35?a36:0);
  a37=(!a35);
  a38=3.1415926535897931e+00;
  a39=(a0-a28);
  a39=(a1*a39);
  a40=4.9303806576313238e-32;
  a39=(a39+a40);
  a39=sqrt(a39);
  a38=(a38-a39);
  a38=(a37?a38:0);
  a36=(a36+a38);
  a36=(a34?a36:0);
  a38=(!a34);
  a41=(a38?a39:0);
  a36=(a36+a41);
  a33=(a33<=a36);
  a41=-1.;
  a42=casadi_sq(a28);
  a42=(a0-a42);
  a42=sqrt(a42);
  a42=(a41/a42);
  a43=(a30*a9);
  a44=arg[0]? arg[0][10] : 0;
  a43=(a43*a44);
  a45=(a30*a2);
  a46=arg[0]? arg[0][11] : 0;
  a45=(a45*a46);
  a43=(a43-a45);
  a45=(a30*a5);
  a47=arg[0]? arg[0][12] : 0;
  a45=(a45*a47);
  a43=(a43+a45);
  a45=(a1*a43);
  a48=(a8*a45);
  a49=(a7*a43);
  a48=(a48+a49);
  a49=(a30*a8);
  a49=(a49*a46);
  a50=(a30*a5);
  a50=(a50*a44);
  a49=(a49-a50);
  a50=(a30*a9);
  a50=(a50*a47);
  a49=(a49+a50);
  a50=(a1*a49);
  a51=(a2*a50);
  a49=(a4*a49);
  a51=(a51+a49);
  a48=(a48+a51);
  a49=(a48/a15);
  a52=(a16/a15);
  a14=(a14+a14);
  a53=(a30*a2);
  a53=(a53*a44);
  a54=(a30*a9);
  a54=(a54*a46);
  a53=(a53+a54);
  a54=(a30*a8);
  a54=(a54*a47);
  a53=(a53-a54);
  a54=(a1*a53);
  a55=(a8*a54);
  a56=(a11*a43);
  a55=(a55+a56);
  a56=(a9*a50);
  a57=(a30*a8);
  a57=(a57*a44);
  a44=(a30*a5);
  a44=(a44*a46);
  a57=(a57+a44);
  a2=(a30*a2);
  a2=(a2*a47);
  a57=(a57+a2);
  a2=(a4*a57);
  a56=(a56-a2);
  a2=(a55-a56);
  a14=(a14*a2);
  a17=(a17+a17);
  a47=(a5*a50);
  a44=(a4*a53);
  a47=(a47+a44);
  a45=(a9*a45);
  a7=(a7*a57);
  a45=(a45-a7);
  a47=(a47+a45);
  a17=(a17*a47);
  a3=(a3+a3);
  a3=(a3*a48);
  a17=(a17-a3);
  a14=(a14+a17);
  a17=(a15+a15);
  a14=(a14/a17);
  a52=(a52*a14);
  a49=(a49+a52);
  a52=(a20*a49);
  a5=(a5*a54);
  a53=(a11*a53);
  a5=(a5+a53);
  a5=(a5+a51);
  a51=(a5/a10);
  a53=(a6/a10);
  a13=(a13+a13);
  a55=(a55+a56);
  a13=(a13*a55);
  a19=(a19+a19);
  a8=(a8*a50);
  a4=(a4*a43);
  a8=(a8+a4);
  a9=(a9*a54);
  a11=(a11*a57);
  a9=(a9-a11);
  a8=(a8-a9);
  a19=(a19*a8);
  a13=(a13+a19);
  a18=(a18+a18);
  a18=(a18*a5);
  a13=(a13-a18);
  a18=(a10+a10);
  a13=(a13/a18);
  a53=(a53*a13);
  a51=(a51+a53);
  a53=(a16*a51);
  a18=(a6*a49);
  a53=(a53+a18);
  a55=(a55/a10);
  a18=(a21/a10);
  a18=(a18*a13);
  a55=(a55-a18);
  a18=(a22*a55);
  a2=(a2/a15);
  a5=(a22/a15);
  a5=(a5*a14);
  a2=(a2-a5);
  a5=(a21*a2);
  a18=(a18+a5);
  a53=(a53+a18);
  a18=(a16*a53);
  a52=(a52+a18);
  a47=(a47/a15);
  a15=(a24/a15);
  a15=(a15*a14);
  a47=(a47-a15);
  a15=(a26*a47);
  a8=(a8/a10);
  a10=(a25/a10);
  a10=(a10*a13);
  a8=(a8-a10);
  a10=(a22*a8);
  a13=(a25*a2);
  a10=(a10+a13);
  a6=(a6*a47);
  a51=(a24*a51);
  a6=(a6-a51);
  a10=(a10-a6);
  a6=(a24*a10);
  a15=(a15+a6);
  a52=(a52+a15);
  a15=(a49+a53);
  a15=(a52+a15);
  a6=(a30*a15);
  a42=(a42*a6);
  a42=(-a42);
  a35=(a35?a42:0);
  a39=(a39+a39);
  a39=(a15/a39);
  a42=(-a39);
  a37=(a37?a42:0);
  a35=(a35+a37);
  a34=(a34?a35:0);
  a38=(a38?a39:0);
  a34=(a34+a38);
  a38=sin(a36);
  a39=(a34/a38);
  a35=(a36/a38);
  a38=(a35/a38);
  a36=cos(a36);
  a36=(a36*a34);
  a38=(a38*a36);
  a39=(a39-a38);
  a39=(a33?a39:0);
  a38=(!a33);
  a36=1.6666666666666666e-01;
  a34=(a47-a10);
  a34=(a30*a34);
  a31=(a31*a34);
  a37=(a21*a24);
  a42=(a25*a16);
  a37=(a37-a42);
  a42=(a22*a26);
  a6=(a16*a37);
  a42=(a42-a6);
  a6=(a37-a42);
  a55=(a24*a55);
  a21=(a21*a47);
  a55=(a55+a21);
  a8=(a16*a8);
  a25=(a25*a49);
  a8=(a8-a25);
  a55=(a55-a8);
  a8=(a26*a2);
  a25=(a22*a10);
  a8=(a8+a25);
  a25=(a16*a55);
  a21=(a37*a49);
  a25=(a25-a21);
  a8=(a8-a25);
  a25=(a55-a8);
  a25=(a30*a25);
  a21=(a6*a25);
  a51=(a24*a37);
  a13=(a22*a20);
  a51=(a51-a13);
  a13=(a51-a22);
  a14=(a37*a47);
  a18=(a24*a55);
  a14=(a14+a18);
  a18=(a20*a2);
  a5=(a22*a53);
  a18=(a18-a5);
  a14=(a14-a18);
  a18=(a14-a2);
  a18=(a30*a18);
  a5=(a13*a18);
  a21=(a21+a5);
  a31=(a31+a21);
  a36=(a36*a31);
  a21=2.5000000000000001e-02;
  a5=3.;
  a19=casadi_sq(a32);
  a6=(a30*a6);
  a9=casadi_sq(a6);
  a13=(a30*a13);
  a11=casadi_sq(a13);
  a9=(a9+a11);
  a19=(a19+a9);
  a9=(a19+a19);
  a9=(a9*a31);
  a9=(a5*a9);
  a21=(a21*a9);
  a36=(a36+a21);
  a36=(a38?a36:0);
  a39=(a39+a36);
  a32=(a32*a39);
  a33=(a33?a35:0);
  a35=6.;
  a35=(a19/a35);
  a35=(a0+a35);
  a19=casadi_sq(a19);
  a5=(a5*a19);
  a19=40.;
  a5=(a5/a19);
  a35=(a35+a5);
  a38=(a38?a35:0);
  a33=(a33+a38);
  a34=(a33*a34);
  a32=(a32+a34);
  a32=(a29?a32:0);
  a29=(!a29);
  a16=(a1*a16);
  a16=(a16-a27);
  a16=(a16+a0);
  a23=(a1*a23);
  a23=(a23-a27);
  a23=(a23+a0);
  a34=(a16<=a23);
  a20=(a1*a20);
  a20=(a20-a27);
  a20=(a20+a0);
  a27=(a20<=a23);
  a38=2.2204460492503131e-16;
  a35=(a23+a38);
  a35=(a35+a40);
  a35=sqrt(a35);
  a5=(a26<=a24);
  a19=(a5?a0:0);
  a5=(!a5);
  a5=(a5?a41:0);
  a19=(a19+a5);
  a5=(a35*a19);
  a36=(a5/a1);
  a21=casadi_sq(a36);
  a9=(a51+a22);
  a31=(a1*a5);
  a9=(a9/a31);
  a11=casadi_sq(a9);
  a57=(a42+a37);
  a54=(a1*a5);
  a57=(a57/a54);
  a4=casadi_sq(a57);
  a11=(a11+a4);
  a21=(a21+a11);
  a11=sqrt(a21);
  a36=(a36/a11);
  a4=(a27?a36:0);
  a43=(!a27);
  a50=(a37+a42);
  a56=(a20+a38);
  a56=(a56+a40);
  a56=sqrt(a56);
  a17=(a22<=a51);
  a3=(a17?a0:0);
  a17=(!a17);
  a17=(a17?a41:0);
  a3=(a3+a17);
  a17=(a56*a3);
  a48=(a1*a17);
  a50=(a50/a48);
  a45=casadi_sq(a50);
  a7=(a26+a24);
  a44=(a1*a17);
  a7=(a7/a44);
  a46=casadi_sq(a7);
  a58=(a17/a1);
  a59=casadi_sq(a58);
  a46=(a46+a59);
  a45=(a45+a46);
  a46=sqrt(a45);
  a59=(a50/a46);
  a60=(a43?a59:0);
  a4=(a4+a60);
  a4=(a34?a4:0);
  a60=(!a34);
  a61=(a20<=a16);
  a62=(a22+a51);
  a38=(a16+a38);
  a38=(a38+a40);
  a38=sqrt(a38);
  a40=(a42<=a37);
  a0=(a40?a0:0);
  a40=(!a40);
  a40=(a40?a41:0);
  a0=(a0+a40);
  a40=(a38*a0);
  a41=(a1*a40);
  a62=(a62/a41);
  a63=casadi_sq(a62);
  a64=(a40/a1);
  a65=casadi_sq(a64);
  a66=(a24+a26);
  a67=(a1*a40);
  a66=(a66/a67);
  a68=casadi_sq(a66);
  a65=(a65+a68);
  a63=(a63+a65);
  a65=sqrt(a63);
  a68=(a62/a65);
  a69=(a61?a68:0);
  a70=(!a61);
  a71=(a70?a59:0);
  a69=(a69+a71);
  a69=(a60?a69:0);
  a4=(a4+a69);
  a69=(a16<=a23);
  a71=(a20<=a23);
  a24=(a24-a26);
  a26=(a1*a5);
  a24=(a24/a26);
  a72=casadi_sq(a24);
  a21=(a21+a72);
  a72=(a24/a21);
  a52=(a1*a52);
  a52=(a15-a52);
  a35=(a35+a35);
  a52=(a52/a35);
  a19=(a19*a52);
  a52=(a30*a19);
  a5=(a5*a52);
  a35=(a9+a9);
  a73=(a14+a2);
  a73=(a73/a31);
  a31=(a9/a31);
  a74=(a1*a19);
  a31=(a31*a74);
  a73=(a73-a31);
  a35=(a35*a73);
  a31=(a57+a57);
  a74=(a8+a55);
  a74=(a74/a54);
  a54=(a57/a54);
  a75=(a1*a19);
  a54=(a54*a75);
  a74=(a74-a54);
  a31=(a31*a74);
  a35=(a35+a31);
  a5=(a5+a35);
  a35=(a11+a11);
  a5=(a5/a35);
  a72=(a72*a5);
  a21=(a11/a21);
  a35=(a47-a10);
  a35=(a35/a26);
  a26=(a24/a26);
  a19=(a1*a19);
  a26=(a26*a19);
  a35=(a35-a26);
  a21=(a21*a35);
  a72=(a72-a21);
  a72=(a1*a72);
  a72=(a71?a72:0);
  a21=(!a71);
  a51=(a51-a22);
  a22=(a1*a17);
  a51=(a51/a22);
  a35=casadi_sq(a51);
  a45=(a45+a35);
  a35=(a51/a45);
  a26=(a50+a50);
  a19=(a55+a8);
  a19=(a19/a48);
  a50=(a50/a48);
  a53=(a1*a53);
  a53=(a15-a53);
  a56=(a56+a56);
  a53=(a53/a56);
  a3=(a3*a53);
  a53=(a1*a3);
  a50=(a50*a53);
  a19=(a19-a50);
  a26=(a26*a19);
  a50=(a7+a7);
  a53=(a10+a47);
  a53=(a53/a44);
  a44=(a7/a44);
  a56=(a1*a3);
  a44=(a44*a56);
  a53=(a53-a44);
  a50=(a50*a53);
  a44=(a30*a3);
  a17=(a17*a44);
  a50=(a50+a17);
  a26=(a26+a50);
  a50=(a46+a46);
  a26=(a26/a50);
  a35=(a35*a26);
  a45=(a46/a45);
  a50=(a14-a2);
  a50=(a50/a22);
  a22=(a51/a22);
  a3=(a1*a3);
  a22=(a22*a3);
  a50=(a50-a22);
  a45=(a45*a50);
  a35=(a35-a45);
  a35=(a1*a35);
  a45=(a21?a35:0);
  a72=(a72+a45);
  a72=(a69?a72:0);
  a45=(!a69);
  a50=(a20<=a16);
  a37=(a37-a42);
  a42=(a1*a40);
  a37=(a37/a42);
  a22=casadi_sq(a37);
  a63=(a63+a22);
  a22=(a37/a63);
  a3=(a62+a62);
  a2=(a2+a14);
  a2=(a2/a41);
  a62=(a62/a41);
  a49=(a1*a49);
  a15=(a15-a49);
  a38=(a38+a38);
  a15=(a15/a38);
  a0=(a0*a15);
  a15=(a1*a0);
  a62=(a62*a15);
  a2=(a2-a62);
  a3=(a3*a2);
  a30=(a30*a0);
  a40=(a40*a30);
  a62=(a66+a66);
  a47=(a47+a10);
  a47=(a47/a67);
  a67=(a66/a67);
  a10=(a1*a0);
  a67=(a67*a10);
  a47=(a47-a67);
  a62=(a62*a47);
  a40=(a40+a62);
  a3=(a3+a40);
  a40=(a65+a65);
  a3=(a3/a40);
  a22=(a22*a3);
  a63=(a65/a63);
  a55=(a55-a8);
  a55=(a55/a42);
  a42=(a37/a42);
  a0=(a1*a0);
  a42=(a42*a0);
  a55=(a55-a42);
  a63=(a63*a55);
  a22=(a22-a63);
  a22=(a1*a22);
  a22=(a50?a22:0);
  a63=(!a50);
  a35=(a63?a35:0);
  a22=(a22+a35);
  a22=(a45?a22:0);
  a72=(a72+a22);
  a4=(a4*a72);
  a24=atan2(a11,a24);
  a24=(a1*a24);
  a71=(a71?a24:0);
  a51=atan2(a46,a51);
  a51=(a1*a51);
  a21=(a21?a51:0);
  a71=(a71+a21);
  a69=(a69?a71:0);
  a37=atan2(a65,a37);
  a1=(a1*a37);
  a50=(a50?a1:0);
  a63=(a63?a51:0);
  a50=(a50+a63);
  a45=(a45?a50:0);
  a69=(a69+a45);
  a52=(a52/a11);
  a36=(a36/a11);
  a36=(a36*a5);
  a52=(a52-a36);
  a27=(a27?a52:0);
  a19=(a19/a46);
  a59=(a59/a46);
  a59=(a59*a26);
  a19=(a19-a59);
  a43=(a43?a19:0);
  a27=(a27+a43);
  a34=(a34?a27:0);
  a2=(a2/a65);
  a68=(a68/a65);
  a68=(a68*a3);
  a2=(a2-a68);
  a61=(a61?a2:0);
  a70=(a70?a19:0);
  a61=(a61+a70);
  a60=(a60?a61:0);
  a34=(a34+a60);
  a34=(a69*a34);
  a4=(a4+a34);
  a29=(a29?a4:0);
  a32=(a32+a29);
  if (res[0]!=0) res[0][3]=a32;
  a32=(a12<=a28);
  a6=(a6*a39);
  a25=(a33*a25);
  a6=(a6+a25);
  a6=(a32?a6:0);
  a32=(!a32);
  a25=(a16<=a23);
  a29=(a20<=a23);
  a9=(a9/a11);
  a4=(a29?a9:0);
  a34=(!a29);
  a7=(a7/a46);
  a60=(a34?a7:0);
  a4=(a4+a60);
  a4=(a25?a4:0);
  a60=(!a25);
  a61=(a20<=a16);
  a64=(a64/a65);
  a70=(a61?a64:0);
  a19=(!a61);
  a2=(a19?a7:0);
  a70=(a70+a2);
  a70=(a60?a70:0);
  a4=(a4+a70);
  a4=(a4*a72);
  a73=(a73/a11);
  a9=(a9/a11);
  a9=(a9*a5);
  a73=(a73-a9);
  a29=(a29?a73:0);
  a53=(a53/a46);
  a7=(a7/a46);
  a7=(a7*a26);
  a53=(a53-a7);
  a34=(a34?a53:0);
  a29=(a29+a34);
  a25=(a25?a29:0);
  a30=(a30/a65);
  a64=(a64/a65);
  a64=(a64*a3);
  a30=(a30-a64);
  a61=(a61?a30:0);
  a19=(a19?a53:0);
  a61=(a61+a19);
  a60=(a60?a61:0);
  a25=(a25+a60);
  a25=(a69*a25);
  a4=(a4+a25);
  a32=(a32?a4:0);
  a6=(a6+a32);
  if (res[0]!=0) res[0][4]=a6;
  a12=(a12<=a28);
  a13=(a13*a39);
  a33=(a33*a18);
  a13=(a13+a33);
  a13=(a12?a13:0);
  a12=(!a12);
  a33=(a16<=a23);
  a23=(a20<=a23);
  a57=(a57/a11);
  a18=(a23?a57:0);
  a39=(!a23);
  a58=(a58/a46);
  a28=(a39?a58:0);
  a18=(a18+a28);
  a18=(a33?a18:0);
  a28=(!a33);
  a20=(a20<=a16);
  a66=(a66/a65);
  a16=(a20?a66:0);
  a6=(!a20);
  a32=(a6?a58:0);
  a16=(a16+a32);
  a16=(a28?a16:0);
  a18=(a18+a16);
  a18=(a18*a72);
  a74=(a74/a11);
  a57=(a57/a11);
  a57=(a57*a5);
  a74=(a74-a57);
  a23=(a23?a74:0);
  a44=(a44/a46);
  a58=(a58/a46);
  a58=(a58*a26);
  a44=(a44-a58);
  a39=(a39?a44:0);
  a23=(a23+a39);
  a33=(a33?a23:0);
  a47=(a47/a65);
  a66=(a66/a65);
  a66=(a66*a3);
  a47=(a47-a66);
  a20=(a20?a47:0);
  a6=(a6?a44:0);
  a20=(a20+a6);
  a28=(a28?a20:0);
  a33=(a33+a28);
  a69=(a69*a33);
  a18=(a18+a69);
  a12=(a12?a18:0);
  a13=(a13+a12);
  if (res[0]!=0) res[0][5]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_velocity(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_velocity_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_velocity_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_velocity_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_velocity_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_velocity_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_velocity_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_velocity_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
