/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_rotation_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {3, 3, 1};

/* kinematics_rotation:(i0[13])->(o0[3x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12;
  a00=1.;
  a01=2.;
  a02=arg[0]? arg[0][5] : 0;
  a03=(a01*a02);
  a04=(a03*a02);
  a05=arg[0]? arg[0][6] : 0;
  a06=(a01*a05);
  a05=(a06*a05);
  a07=(a04+a05);
  a07=(a00-a07);
  if (res[0]!=0) res[0][0]=a07;
  a07=arg[0]? arg[0][4] : 0;
  a08=(a03*a07);
  a09=arg[0]? arg[0][3] : 0;
  a10=(a06*a09);
  a11=(a08+a10);
  if (res[0]!=0) res[0][1]=a11;
  a11=(a06*a07);
  a03=(a03*a09);
  a12=(a11-a03);
  if (res[0]!=0) res[0][2]=a12;
  a08=(a08-a10);
  if (res[0]!=0) res[0][3]=a08;
  a01=(a01*a07);
  a07=(a01*a07);
  a05=(a07+a05);
  a05=(a00-a05);
  if (res[0]!=0) res[0][4]=a05;
  a06=(a06*a02);
  a01=(a01*a09);
  a09=(a06+a01);
  if (res[0]!=0) res[0][5]=a09;
  a11=(a11+a03);
  if (res[0]!=0) res[0][6]=a11;
  a06=(a06-a01);
  if (res[0]!=0) res[0][7]=a06;
  a07=(a07+a04);
  a00=(a00-a07);
  if (res[0]!=0) res[0][8]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_rotation(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_rotation_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_rotation_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_rotation_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_rotation_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_rotation_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_rotation_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_rotation_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_rotation_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_rotation_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_rotation_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_rotation_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_rotation_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_rotation_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_rotation_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_rotation_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_rotation_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
