/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) M_func_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

/* M_func:(i0[13])->(o0[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a5, a6, a7, a8, a9;
  a0=1.;
  a1=2.;
  a2=arg[0]? arg[0][5] : 0;
  a3=(a1*a2);
  a4=(a3*a2);
  a5=arg[0]? arg[0][6] : 0;
  a6=(a1*a5);
  a5=(a6*a5);
  a7=(a4+a5);
  a7=(a0-a7);
  a8=casadi_sq(a7);
  a9=arg[0]? arg[0][4] : 0;
  a10=(a3*a9);
  a11=arg[0]? arg[0][3] : 0;
  a12=(a6*a11);
  a13=(a10+a12);
  a14=casadi_sq(a13);
  a15=(a6*a9);
  a3=(a3*a11);
  a16=(a15-a3);
  a17=casadi_sq(a16);
  a14=(a14+a17);
  a8=(a8+a14);
  if (res[0]!=0) res[0][0]=a8;
  a10=(a10-a12);
  a12=(a7*a10);
  a1=(a1*a9);
  a9=(a1*a9);
  a5=(a9+a5);
  a5=(a0-a5);
  a8=(a13*a5);
  a6=(a6*a2);
  a1=(a1*a11);
  a11=(a6+a1);
  a2=(a16*a11);
  a8=(a8+a2);
  a12=(a12+a8);
  if (res[0]!=0) res[0][1]=a12;
  a15=(a15+a3);
  a3=(a7*a15);
  a6=(a6-a1);
  a1=(a13*a6);
  a9=(a9+a4);
  a0=(a0-a9);
  a9=(a16*a0);
  a1=(a1+a9);
  a3=(a3+a1);
  if (res[0]!=0) res[0][2]=a3;
  a1=arg[0]? arg[0][1] : 0;
  a9=(a1*a16);
  a4=arg[0]? arg[0][2] : 0;
  a8=(a4*a13);
  a9=(a9-a8);
  a8=(a1*a16);
  a2=(a4*a13);
  a8=(a8-a2);
  a8=(a9-a8);
  a2=(a7*a8);
  a14=(a4*a7);
  a17=arg[0]? arg[0][0] : 0;
  a18=(a17*a16);
  a14=(a14-a18);
  a18=(a4*a7);
  a19=(a17*a16);
  a18=(a18-a19);
  a18=(a14-a18);
  a19=(a13*a18);
  a20=(a17*a13);
  a21=(a1*a7);
  a20=(a20-a21);
  a21=(a17*a13);
  a22=(a1*a7);
  a21=(a21-a22);
  a21=(a20-a21);
  a22=(a16*a21);
  a19=(a19+a22);
  a2=(a2+a19);
  if (res[0]!=0) res[0][3]=a2;
  a19=(a1*a11);
  a22=(a4*a5);
  a19=(a19-a22);
  a22=(a1*a11);
  a23=(a4*a5);
  a22=(a22-a23);
  a22=(a19-a22);
  a23=(a7*a22);
  a24=(a4*a10);
  a25=(a17*a11);
  a24=(a24-a25);
  a25=(a4*a10);
  a26=(a17*a11);
  a25=(a25-a26);
  a25=(a24-a25);
  a26=(a13*a25);
  a27=(a17*a5);
  a28=(a1*a10);
  a27=(a27-a28);
  a28=(a17*a5);
  a29=(a1*a10);
  a28=(a28-a29);
  a28=(a27-a28);
  a29=(a16*a28);
  a26=(a26+a29);
  a23=(a23+a26);
  if (res[0]!=0) res[0][4]=a23;
  a26=(a1*a0);
  a29=(a4*a6);
  a26=(a26-a29);
  a29=(a1*a0);
  a30=(a4*a6);
  a29=(a29-a30);
  a29=(a26-a29);
  a30=(a7*a29);
  a31=(a4*a15);
  a32=(a17*a0);
  a31=(a31-a32);
  a32=(a4*a15);
  a33=(a17*a0);
  a32=(a32-a33);
  a32=(a31-a32);
  a33=(a13*a32);
  a34=(a17*a6);
  a35=(a1*a15);
  a34=(a34-a35);
  a35=(a17*a6);
  a36=(a1*a15);
  a35=(a35-a36);
  a35=(a34-a35);
  a36=(a16*a35);
  a33=(a33+a36);
  a30=(a30+a33);
  if (res[0]!=0) res[0][5]=a30;
  if (res[0]!=0) res[0][6]=a12;
  a12=casadi_sq(a10);
  a33=casadi_sq(a5);
  a36=casadi_sq(a11);
  a33=(a33+a36);
  a12=(a12+a33);
  if (res[0]!=0) res[0][7]=a12;
  a12=(a10*a15);
  a33=(a5*a6);
  a36=(a11*a0);
  a33=(a33+a36);
  a12=(a12+a33);
  if (res[0]!=0) res[0][8]=a12;
  a33=(a10*a8);
  a36=(a5*a18);
  a37=(a11*a21);
  a36=(a36+a37);
  a33=(a33+a36);
  if (res[0]!=0) res[0][9]=a33;
  a36=(a10*a22);
  a37=(a5*a25);
  a38=(a11*a28);
  a37=(a37+a38);
  a36=(a36+a37);
  if (res[0]!=0) res[0][10]=a36;
  a37=(a10*a29);
  a38=(a5*a32);
  a39=(a11*a35);
  a38=(a38+a39);
  a37=(a37+a38);
  if (res[0]!=0) res[0][11]=a37;
  if (res[0]!=0) res[0][12]=a3;
  if (res[0]!=0) res[0][13]=a12;
  a12=casadi_sq(a15);
  a3=casadi_sq(a6);
  a38=casadi_sq(a0);
  a3=(a3+a38);
  a12=(a12+a3);
  if (res[0]!=0) res[0][14]=a12;
  a12=(a15*a8);
  a3=(a6*a18);
  a38=(a0*a21);
  a3=(a3+a38);
  a12=(a12+a3);
  if (res[0]!=0) res[0][15]=a12;
  a3=(a15*a22);
  a38=(a6*a25);
  a39=(a0*a28);
  a38=(a38+a39);
  a3=(a3+a38);
  if (res[0]!=0) res[0][16]=a3;
  a38=(a15*a29);
  a39=(a6*a32);
  a40=(a0*a35);
  a39=(a39+a40);
  a38=(a38+a39);
  if (res[0]!=0) res[0][17]=a38;
  if (res[0]!=0) res[0][18]=a2;
  if (res[0]!=0) res[0][19]=a33;
  if (res[0]!=0) res[0][20]=a12;
  a12=(a9*a8);
  a33=(a14*a18);
  a2=(a20*a21);
  a33=(a33+a2);
  a12=(a12+a33);
  a33=-6.8000000000001393e-03;
  a2=-3.4000000000000696e-03;
  a39=(a2*a13);
  a40=(a39*a13);
  a41=(a2*a5);
  a42=(a41*a5);
  a40=(a40+a42);
  a33=(a33-a40);
  a42=(a2*a16);
  a43=(a42*a16);
  a2=(a2*a11);
  a44=(a2*a11);
  a43=(a43+a44);
  a33=(a33-a43);
  a44=1.0080000000000000e+00;
  a33=(a33+a44);
  a45=(a33*a7);
  a39=(a39*a7);
  a41=(a41*a10);
  a39=(a39+a41);
  a41=(a39*a13);
  a45=(a45+a41);
  a41=(a42*a7);
  a46=(a2*a10);
  a41=(a41+a46);
  a46=(a41*a16);
  a45=(a45+a46);
  a46=(a1*a21);
  a47=(a4*a18);
  a46=(a46-a47);
  a45=(a45+a46);
  a45=(a7*a45);
  a46=(a39*a7);
  a40=(a40+a44);
  a47=(a40*a13);
  a46=(a46+a47);
  a42=(a42*a13);
  a2=(a2*a5);
  a42=(a42+a2);
  a2=(a42*a16);
  a46=(a46+a2);
  a2=(a4*a8);
  a21=(a17*a21);
  a2=(a2-a21);
  a46=(a46+a2);
  a46=(a13*a46);
  a2=(a41*a7);
  a21=(a42*a13);
  a2=(a2+a21);
  a43=(a43+a44);
  a44=(a43*a16);
  a2=(a2+a44);
  a18=(a17*a18);
  a8=(a1*a8);
  a18=(a18-a8);
  a2=(a2+a18);
  a2=(a16*a2);
  a46=(a46+a2);
  a45=(a45+a46);
  a12=(a12+a45);
  if (res[0]!=0) res[0][21]=a12;
  a12=(a9*a22);
  a45=(a14*a25);
  a46=(a20*a28);
  a45=(a45+a46);
  a12=(a12+a45);
  a45=(a33*a10);
  a46=(a39*a5);
  a45=(a45+a46);
  a46=(a41*a11);
  a45=(a45+a46);
  a46=(a1*a28);
  a2=(a4*a25);
  a46=(a46-a2);
  a45=(a45+a46);
  a46=(a7*a45);
  a2=(a39*a10);
  a18=(a40*a5);
  a2=(a2+a18);
  a18=(a42*a11);
  a2=(a2+a18);
  a18=(a4*a22);
  a8=(a17*a28);
  a18=(a18-a8);
  a2=(a2+a18);
  a18=(a13*a2);
  a8=(a41*a10);
  a44=(a42*a5);
  a8=(a8+a44);
  a44=(a43*a11);
  a8=(a8+a44);
  a44=(a17*a25);
  a21=(a1*a22);
  a44=(a44-a21);
  a8=(a8+a44);
  a44=(a16*a8);
  a18=(a18+a44);
  a46=(a46+a18);
  a12=(a12+a46);
  if (res[0]!=0) res[0][22]=a12;
  a9=(a9*a29);
  a14=(a14*a32);
  a20=(a20*a35);
  a14=(a14+a20);
  a9=(a9+a14);
  a33=(a33*a15);
  a14=(a39*a6);
  a33=(a33+a14);
  a14=(a41*a0);
  a33=(a33+a14);
  a14=(a1*a35);
  a20=(a4*a32);
  a14=(a14-a20);
  a33=(a33+a14);
  a7=(a7*a33);
  a39=(a39*a15);
  a40=(a40*a6);
  a39=(a39+a40);
  a40=(a42*a0);
  a39=(a39+a40);
  a4=(a4*a29);
  a40=(a17*a35);
  a4=(a4-a40);
  a39=(a39+a4);
  a13=(a13*a39);
  a41=(a41*a15);
  a42=(a42*a6);
  a41=(a41+a42);
  a43=(a43*a0);
  a41=(a41+a43);
  a17=(a17*a32);
  a1=(a1*a29);
  a17=(a17-a1);
  a41=(a41+a17);
  a16=(a16*a41);
  a13=(a13+a16);
  a7=(a7+a13);
  a9=(a9+a7);
  if (res[0]!=0) res[0][23]=a9;
  if (res[0]!=0) res[0][24]=a23;
  if (res[0]!=0) res[0][25]=a36;
  if (res[0]!=0) res[0][26]=a3;
  if (res[0]!=0) res[0][27]=a12;
  a22=(a19*a22);
  a25=(a24*a25);
  a28=(a27*a28);
  a25=(a25+a28);
  a22=(a22+a25);
  a45=(a10*a45);
  a2=(a5*a2);
  a8=(a11*a8);
  a2=(a2+a8);
  a45=(a45+a2);
  a22=(a22+a45);
  if (res[0]!=0) res[0][28]=a22;
  a19=(a19*a29);
  a24=(a24*a32);
  a27=(a27*a35);
  a24=(a24+a27);
  a19=(a19+a24);
  a10=(a10*a33);
  a5=(a5*a39);
  a11=(a11*a41);
  a5=(a5+a11);
  a10=(a10+a5);
  a19=(a19+a10);
  if (res[0]!=0) res[0][29]=a19;
  if (res[0]!=0) res[0][30]=a30;
  if (res[0]!=0) res[0][31]=a37;
  if (res[0]!=0) res[0][32]=a38;
  if (res[0]!=0) res[0][33]=a9;
  if (res[0]!=0) res[0][34]=a19;
  a26=(a26*a29);
  a31=(a31*a32);
  a34=(a34*a35);
  a31=(a31+a34);
  a26=(a26+a31);
  a15=(a15*a33);
  a6=(a6*a39);
  a0=(a0*a41);
  a6=(a6+a0);
  a15=(a15+a6);
  a26=(a26+a15);
  if (res[0]!=0) res[0][35]=a26;
  return 0;
}

CASADI_SYMBOL_EXPORT int M_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int M_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int M_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int M_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void M_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void M_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int M_func_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int M_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real M_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int M_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int M_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
