/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_velocity_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {29, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};

/* kinematics_velocity:(i0[29])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61;
  a00=1.;
  a01=2.;
  a02=arg[0]? arg[0][6] : 0;
  a03=(a01*a02);
  a04=(a03*a02);
  a05=arg[0]? arg[0][5] : 0;
  a06=(a01*a05);
  a07=(a06*a05);
  a04=(a04+a07);
  a04=(a00-a04);
  a07=arg[0]? arg[0][15] : 0;
  a04=(a04*a07);
  a08=arg[0]? arg[0][4] : 0;
  a06=(a06*a08);
  a09=arg[0]? arg[0][3] : 0;
  a10=(a01*a09);
  a11=(a10*a02);
  a06=(a06-a11);
  a11=arg[0]? arg[0][16] : 0;
  a06=(a06*a11);
  a04=(a04+a06);
  a06=(a10*a05);
  a03=(a03*a08);
  a06=(a06+a03);
  a03=arg[0]? arg[0][17] : 0;
  a06=(a06*a03);
  a04=(a04+a06);
  a06=5.0823000000000000e-02;
  a12=5.0000000000000000e-01;
  a13=(a12*a02);
  a14=arg[0]? arg[0][18] : 0;
  a13=(a13*a14);
  a15=(a12*a09);
  a16=arg[0]? arg[0][19] : 0;
  a15=(a15*a16);
  a13=(a13+a15);
  a15=(a12*a08);
  a17=arg[0]? arg[0][20] : 0;
  a15=(a15*a17);
  a13=(a13-a15);
  a15=(a01*a13);
  a18=(a08*a15);
  a19=(a01*a05);
  a20=(a12*a09);
  a20=(a20*a14);
  a21=(a12*a02);
  a21=(a21*a16);
  a20=(a20-a21);
  a21=(a12*a05);
  a21=(a21*a17);
  a20=(a20+a21);
  a21=(a19*a20);
  a18=(a18+a21);
  a21=(a12*a08);
  a21=(a21*a16);
  a22=(a12*a05);
  a22=(a22*a14);
  a21=(a21-a22);
  a22=(a12*a09);
  a22=(a22*a17);
  a21=(a21+a22);
  a22=(a01*a21);
  a23=(a09*a22);
  a24=(a01*a02);
  a25=(a12*a08);
  a25=(a25*a14);
  a14=(a12*a05);
  a14=(a14*a16);
  a25=(a25+a14);
  a12=(a12*a02);
  a12=(a12*a17);
  a25=(a25+a12);
  a12=(a24*a25);
  a23=(a23-a12);
  a12=(a18-a23);
  a17=(a06*a12);
  a14=5.6000000000000001e-02;
  a16=(a08*a22);
  a26=(a24*a20);
  a16=(a16+a26);
  a26=(a09*a15);
  a27=(a19*a25);
  a26=(a26-a27);
  a27=(a16+a26);
  a28=(a14*a27);
  a17=(a17+a28);
  a28=8.6333999999999994e-02;
  a15=(a05*a15);
  a29=(a19*a13);
  a15=(a15+a29);
  a29=(a02*a22);
  a21=(a24*a21);
  a29=(a29+a21);
  a21=(a15+a29);
  a30=(a28*a21);
  a17=(a17-a30);
  a17=(a04+a17);
  a30=6.3176999999999997e-02;
  a31=arg[0]? arg[0][7] : 0;
  a32=cos(a31);
  a33=(a32*a12);
  a34=(a19*a08);
  a35=(a24*a09);
  a36=(a34-a35);
  a37=sin(a31);
  a38=arg[0]? arg[0][21] : 0;
  a37=(a37*a38);
  a39=(a36*a37);
  a33=(a33-a39);
  a39=sin(a31);
  a40=(a39*a27);
  a41=(a24*a08);
  a42=(a19*a09);
  a43=(a41+a42);
  a31=cos(a31);
  a31=(a31*a38);
  a38=(a43*a31);
  a40=(a40+a38);
  a33=(a33+a40);
  a40=(a30*a33);
  a38=-6.6166000000000003e-02;
  a44=(a38*a21);
  a40=(a40-a44);
  a17=(a17+a40);
  a40=(a14*a33);
  a44=-1.9000000000000000e-01;
  a19=(a19*a05);
  a45=(a24*a02);
  a46=(a19+a45);
  a46=(a00-a46);
  a47=arg[0]? arg[0][8] : 0;
  a48=cos(a47);
  a49=arg[0]? arg[0][22] : 0;
  a48=(a48*a49);
  a50=(a46*a48);
  a51=sin(a47);
  a52=(a51*a21);
  a50=(a50-a52);
  a52=cos(a47);
  a53=(a32*a27);
  a54=(a43*a37);
  a53=(a53-a54);
  a54=(a39*a12);
  a55=(a36*a31);
  a54=(a54+a55);
  a53=(a53-a54);
  a54=(a52*a53);
  a55=(a43*a32);
  a56=(a36*a39);
  a55=(a55-a56);
  a47=sin(a47);
  a47=(a47*a49);
  a49=(a55*a47);
  a54=(a54-a49);
  a50=(a50+a54);
  a54=(a44*a50);
  a40=(a40+a54);
  a17=(a17+a40);
  a40=3.5499999999999997e-02;
  a33=(a40*a33);
  a54=(a46*a52);
  a49=(a55*a51);
  a54=(a54-a49);
  a49=arg[0]? arg[0][9] : 0;
  a56=cos(a49);
  a57=arg[0]? arg[0][23] : 0;
  a56=(a56*a57);
  a54=(a54*a56);
  a58=sin(a49);
  a59=(a52*a21);
  a60=(a46*a47);
  a59=(a59+a60);
  a53=(a51*a53);
  a60=(a55*a48);
  a53=(a53+a60);
  a59=(a59+a53);
  a59=(a58*a59);
  a54=(a54-a59);
  a59=cos(a49);
  a50=(a59*a50);
  a53=(a46*a51);
  a55=(a55*a52);
  a53=(a53+a55);
  a49=sin(a49);
  a49=(a49*a57);
  a53=(a53*a49);
  a50=(a50-a53);
  a54=(a54+a50);
  a54=(a44*a54);
  a33=(a33+a54);
  a17=(a17+a33);
  if (res[0]!=0) res[0][0]=a17;
  a17=(a10*a02);
  a33=(a01*a08);
  a54=(a33*a05);
  a17=(a17+a54);
  a17=(a17*a07);
  a54=(a01*a02);
  a50=(a54*a02);
  a33=(a33*a08);
  a50=(a50+a33);
  a50=(a00-a50);
  a50=(a50*a11);
  a17=(a17+a50);
  a54=(a54*a05);
  a50=(a10*a08);
  a54=(a54-a50);
  a54=(a54*a03);
  a17=(a17+a54);
  a18=(a18+a23);
  a23=(a28*a18);
  a22=(a05*a22);
  a13=(a24*a13);
  a22=(a22+a13);
  a13=(a01*a20);
  a54=(a09*a13);
  a50=(a01*a08);
  a25=(a50*a25);
  a54=(a54-a25);
  a25=(a22-a54);
  a33=(a14*a25);
  a13=(a08*a13);
  a20=(a50*a20);
  a13=(a13+a20);
  a29=(a13+a29);
  a20=(a06*a29);
  a33=(a33-a20);
  a23=(a23+a33);
  a23=(a17+a23);
  a33=(a38*a18);
  a20=(a39*a25);
  a24=(a24*a05);
  a09=(a50*a09);
  a53=(a24-a09);
  a57=(a53*a31);
  a20=(a20+a57);
  a57=(a32*a29);
  a50=(a50*a08);
  a45=(a50+a45);
  a45=(a00-a45);
  a55=(a45*a37);
  a57=(a57+a55);
  a20=(a20-a57);
  a57=(a30*a20);
  a33=(a33+a57);
  a23=(a23+a33);
  a33=(a14*a20);
  a57=(a51*a18);
  a34=(a34+a35);
  a35=(a34*a48);
  a57=(a57+a35);
  a35=(a32*a25);
  a55=(a53*a37);
  a35=(a35-a55);
  a55=(a45*a31);
  a60=(a39*a29);
  a55=(a55-a60);
  a35=(a35-a55);
  a55=(a52*a35);
  a60=(a53*a32);
  a61=(a45*a39);
  a60=(a60-a61);
  a61=(a60*a47);
  a55=(a55-a61);
  a57=(a57+a55);
  a55=(a44*a57);
  a33=(a33+a55);
  a23=(a23+a33);
  a20=(a40*a20);
  a33=(a52*a18);
  a55=(a34*a47);
  a33=(a33-a55);
  a35=(a51*a35);
  a55=(a60*a48);
  a35=(a35+a55);
  a33=(a33-a35);
  a33=(a58*a33);
  a35=(a34*a52);
  a55=(a60*a51);
  a35=(a35-a55);
  a35=(a35*a56);
  a33=(a33+a35);
  a57=(a59*a57);
  a35=(a34*a51);
  a60=(a60*a52);
  a35=(a35+a60);
  a35=(a35*a49);
  a57=(a57-a35);
  a33=(a33+a57);
  a33=(a44*a33);
  a20=(a20+a33);
  a23=(a23+a20);
  if (res[0]!=0) res[0][1]=a23;
  a23=(a01*a08);
  a20=(a23*a02);
  a33=(a10*a05);
  a20=(a20-a33);
  a20=(a20*a07);
  a10=(a10*a08);
  a01=(a01*a05);
  a02=(a01*a02);
  a10=(a10+a02);
  a10=(a10*a11);
  a20=(a20+a10);
  a01=(a01*a05);
  a23=(a23*a08);
  a01=(a01+a23);
  a01=(a00-a01);
  a01=(a01*a03);
  a20=(a20+a01);
  a16=(a16-a26);
  a26=(a28*a16);
  a22=(a22+a54);
  a06=(a06*a22);
  a13=(a13+a15);
  a15=(a14*a13);
  a06=(a06-a15);
  a26=(a26+a06);
  a26=(a20+a26);
  a06=(a38*a16);
  a15=(a32*a22);
  a24=(a24+a09);
  a09=(a24*a37);
  a15=(a15-a09);
  a50=(a50+a19);
  a00=(a00-a50);
  a50=(a00*a31);
  a19=(a39*a13);
  a50=(a50-a19);
  a15=(a15+a50);
  a30=(a30*a15);
  a06=(a06+a30);
  a26=(a26+a06);
  a06=(a14*a15);
  a30=(a51*a16);
  a41=(a41-a42);
  a42=(a41*a48);
  a30=(a30+a42);
  a42=(a32*a13);
  a37=(a00*a37);
  a42=(a42+a37);
  a37=(a39*a22);
  a31=(a24*a31);
  a37=(a37+a31);
  a42=(a42+a37);
  a37=(a52*a42);
  a32=(a00*a32);
  a39=(a24*a39);
  a32=(a32-a39);
  a39=(a32*a47);
  a37=(a37+a39);
  a30=(a30-a37);
  a37=(a44*a30);
  a06=(a06+a37);
  a26=(a26+a06);
  a40=(a40*a15);
  a15=(a52*a16);
  a47=(a41*a47);
  a15=(a15-a47);
  a48=(a32*a48);
  a42=(a51*a42);
  a48=(a48-a42);
  a15=(a15-a48);
  a58=(a58*a15);
  a15=(a41*a52);
  a48=(a32*a51);
  a15=(a15-a48);
  a15=(a15*a56);
  a58=(a58+a15);
  a59=(a59*a30);
  a51=(a41*a51);
  a32=(a32*a52);
  a51=(a51+a32);
  a51=(a51*a49);
  a59=(a59-a51);
  a58=(a58+a59);
  a58=(a44*a58);
  a40=(a40+a58);
  a26=(a26+a40);
  if (res[0]!=0) res[0][2]=a26;
  a26=-5.0823000000000000e-02;
  a40=(a26*a12);
  a58=(a14*a27);
  a40=(a40+a58);
  a58=(a28*a21);
  a40=(a40-a58);
  a04=(a04+a40);
  a40=-6.3176999999999997e-02;
  a58=arg[0]? arg[0][11] : 0;
  a59=cos(a58);
  a51=(a59*a12);
  a49=sin(a58);
  a32=arg[0]? arg[0][25] : 0;
  a49=(a49*a32);
  a52=(a36*a49);
  a51=(a51-a52);
  a52=sin(a58);
  a30=(a52*a27);
  a58=cos(a58);
  a58=(a58*a32);
  a32=(a43*a58);
  a30=(a30+a32);
  a51=(a51+a30);
  a30=(a40*a51);
  a32=(a38*a21);
  a30=(a30-a32);
  a04=(a04+a30);
  a30=-5.6000000000000001e-02;
  a32=(a30*a51);
  a15=arg[0]? arg[0][12] : 0;
  a56=cos(a15);
  a48=arg[0]? arg[0][26] : 0;
  a56=(a56*a48);
  a42=(a46*a56);
  a47=sin(a15);
  a06=(a47*a21);
  a42=(a42-a06);
  a06=cos(a15);
  a27=(a59*a27);
  a37=(a43*a49);
  a27=(a27-a37);
  a12=(a52*a12);
  a37=(a36*a58);
  a12=(a12+a37);
  a27=(a27-a12);
  a12=(a06*a27);
  a43=(a43*a59);
  a36=(a36*a52);
  a43=(a43-a36);
  a15=sin(a15);
  a15=(a15*a48);
  a48=(a43*a15);
  a12=(a12-a48);
  a42=(a42+a12);
  a12=(a44*a42);
  a32=(a32+a12);
  a04=(a04+a32);
  a32=-3.5499999999999997e-02;
  a51=(a32*a51);
  a12=(a46*a06);
  a48=(a43*a47);
  a12=(a12-a48);
  a48=arg[0]? arg[0][13] : 0;
  a36=cos(a48);
  a37=arg[0]? arg[0][27] : 0;
  a36=(a36*a37);
  a12=(a12*a36);
  a39=sin(a48);
  a21=(a06*a21);
  a31=(a46*a15);
  a21=(a21+a31);
  a27=(a47*a27);
  a31=(a43*a56);
  a27=(a27+a31);
  a21=(a21+a27);
  a21=(a39*a21);
  a12=(a12-a21);
  a21=cos(a48);
  a42=(a21*a42);
  a46=(a46*a47);
  a43=(a43*a06);
  a46=(a46+a43);
  a48=sin(a48);
  a48=(a48*a37);
  a46=(a46*a48);
  a42=(a42-a46);
  a12=(a12+a42);
  a12=(a44*a12);
  a51=(a51+a12);
  a04=(a04+a51);
  if (res[0]!=0) res[0][3]=a04;
  a04=(a28*a18);
  a51=(a14*a25);
  a12=(a26*a29);
  a51=(a51-a12);
  a04=(a04+a51);
  a17=(a17+a04);
  a04=(a38*a18);
  a51=(a52*a25);
  a12=(a53*a58);
  a51=(a51+a12);
  a12=(a59*a29);
  a42=(a45*a49);
  a12=(a12+a42);
  a51=(a51-a12);
  a12=(a40*a51);
  a04=(a04+a12);
  a17=(a17+a04);
  a04=(a30*a51);
  a12=(a47*a18);
  a42=(a34*a56);
  a12=(a12+a42);
  a25=(a59*a25);
  a42=(a53*a49);
  a25=(a25-a42);
  a42=(a45*a58);
  a29=(a52*a29);
  a42=(a42-a29);
  a25=(a25-a42);
  a42=(a06*a25);
  a53=(a53*a59);
  a45=(a45*a52);
  a53=(a53-a45);
  a45=(a53*a15);
  a42=(a42-a45);
  a12=(a12+a42);
  a42=(a44*a12);
  a04=(a04+a42);
  a17=(a17+a04);
  a51=(a32*a51);
  a18=(a06*a18);
  a04=(a34*a15);
  a18=(a18-a04);
  a25=(a47*a25);
  a04=(a53*a56);
  a25=(a25+a04);
  a18=(a18-a25);
  a18=(a39*a18);
  a25=(a34*a06);
  a04=(a53*a47);
  a25=(a25-a04);
  a25=(a25*a36);
  a18=(a18+a25);
  a12=(a21*a12);
  a34=(a34*a47);
  a53=(a53*a06);
  a34=(a34+a53);
  a34=(a34*a48);
  a12=(a12-a34);
  a18=(a18+a12);
  a18=(a44*a18);
  a51=(a51+a18);
  a17=(a17+a51);
  if (res[0]!=0) res[0][4]=a17;
  a28=(a28*a16);
  a26=(a26*a22);
  a14=(a14*a13);
  a26=(a26-a14);
  a28=(a28+a26);
  a20=(a20+a28);
  a38=(a38*a16);
  a28=(a59*a22);
  a26=(a24*a49);
  a28=(a28-a26);
  a26=(a00*a58);
  a14=(a52*a13);
  a26=(a26-a14);
  a28=(a28+a26);
  a40=(a40*a28);
  a38=(a38+a40);
  a20=(a20+a38);
  a30=(a30*a28);
  a38=(a47*a16);
  a40=(a41*a56);
  a38=(a38+a40);
  a13=(a59*a13);
  a49=(a00*a49);
  a13=(a13+a49);
  a22=(a52*a22);
  a58=(a24*a58);
  a22=(a22+a58);
  a13=(a13+a22);
  a22=(a06*a13);
  a00=(a00*a59);
  a24=(a24*a52);
  a00=(a00-a24);
  a24=(a00*a15);
  a22=(a22+a24);
  a38=(a38-a22);
  a22=(a44*a38);
  a30=(a30+a22);
  a20=(a20+a30);
  a32=(a32*a28);
  a16=(a06*a16);
  a15=(a41*a15);
  a16=(a16-a15);
  a56=(a00*a56);
  a13=(a47*a13);
  a56=(a56-a13);
  a16=(a16-a56);
  a39=(a39*a16);
  a16=(a41*a06);
  a56=(a00*a47);
  a16=(a16-a56);
  a16=(a16*a36);
  a39=(a39+a16);
  a21=(a21*a38);
  a41=(a41*a47);
  a00=(a00*a06);
  a41=(a41+a00);
  a41=(a41*a48);
  a21=(a21-a41);
  a39=(a39+a21);
  a44=(a44*a39);
  a32=(a32+a44);
  a20=(a20+a32);
  if (res[0]!=0) res[0][5]=a20;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_velocity(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_velocity_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_velocity_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_velocity_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_velocity_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_velocity_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_velocity_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_velocity_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_velocity_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_velocity_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
