/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_rotation_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[47] = {43, 1, 0, 43, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42};
static const casadi_int casadi_s1[24] = {6, 3, 0, 6, 12, 18, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

/* kinematics_rotation:(i0[43])->(o0[6x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a4, a5, a6, a7, a8, a9;
  a0=1.;
  a1=2.;
  a2=arg[0]? arg[0][5] : 0;
  a3=(a1*a2);
  a4=(a3*a2);
  a5=arg[0]? arg[0][6] : 0;
  a6=(a1*a5);
  a5=(a6*a5);
  a7=(a4+a5);
  a7=(a0-a7);
  a8=arg[0]? arg[0][7] : 0;
  a9=cos(a8);
  a10=(a7*a9);
  a11=arg[0]? arg[0][4] : 0;
  a12=(a3*a11);
  a13=arg[0]? arg[0][3] : 0;
  a14=(a6*a13);
  a15=(a12-a14);
  a8=sin(a8);
  a16=(a15*a8);
  a10=(a10-a16);
  a16=arg[0]? arg[0][9] : 0;
  a17=cos(a16);
  a18=(a10*a17);
  a19=(a6*a11);
  a3=(a3*a13);
  a20=(a19+a3);
  a21=arg[0]? arg[0][8] : 0;
  a22=cos(a21);
  a23=(a20*a22);
  a24=(a7*a8);
  a25=(a15*a9);
  a24=(a24+a25);
  a21=sin(a21);
  a25=(a24*a21);
  a23=(a23-a25);
  a16=sin(a16);
  a25=(a23*a16);
  a18=(a18-a25);
  a25=arg[0]? arg[0][10] : 0;
  a26=cos(a25);
  a27=(a18*a26);
  a10=(a10*a16);
  a23=(a23*a17);
  a10=(a10+a23);
  a25=sin(a25);
  a23=(a10*a25);
  a27=(a27-a23);
  a23=arg[0]? arg[0][11] : 0;
  a28=cos(a23);
  a29=(a27*a28);
  a18=(a18*a25);
  a10=(a10*a26);
  a18=(a18+a10);
  a23=sin(a23);
  a10=(a18*a23);
  a29=(a29-a10);
  if (res[0]!=0) res[0][0]=a29;
  a12=(a12+a14);
  a14=(a12*a9);
  a1=(a1*a11);
  a11=(a1*a11);
  a5=(a11+a5);
  a5=(a0-a5);
  a29=(a5*a8);
  a14=(a14-a29);
  a29=(a14*a17);
  a6=(a6*a2);
  a1=(a1*a13);
  a13=(a6-a1);
  a2=(a13*a22);
  a10=(a12*a8);
  a30=(a5*a9);
  a10=(a10+a30);
  a30=(a10*a21);
  a2=(a2-a30);
  a30=(a2*a16);
  a29=(a29-a30);
  a30=(a29*a26);
  a14=(a14*a16);
  a2=(a2*a17);
  a14=(a14+a2);
  a2=(a14*a25);
  a30=(a30-a2);
  a2=(a30*a28);
  a29=(a29*a25);
  a14=(a14*a26);
  a29=(a29+a14);
  a14=(a29*a23);
  a2=(a2-a14);
  if (res[0]!=0) res[0][1]=a2;
  a19=(a19-a3);
  a3=(a19*a9);
  a6=(a6+a1);
  a1=(a6*a8);
  a3=(a3-a1);
  a1=(a3*a17);
  a11=(a11+a4);
  a0=(a0-a11);
  a11=(a0*a22);
  a8=(a19*a8);
  a9=(a6*a9);
  a8=(a8+a9);
  a9=(a8*a21);
  a11=(a11-a9);
  a9=(a11*a16);
  a1=(a1-a9);
  a9=(a1*a26);
  a3=(a3*a16);
  a11=(a11*a17);
  a3=(a3+a11);
  a11=(a3*a25);
  a9=(a9-a11);
  a11=(a9*a28);
  a1=(a1*a25);
  a3=(a3*a26);
  a1=(a1+a3);
  a3=(a1*a23);
  a11=(a11-a3);
  if (res[0]!=0) res[0][2]=a11;
  a11=arg[0]? arg[0][13] : 0;
  a3=cos(a11);
  a26=(a7*a3);
  a11=sin(a11);
  a25=(a15*a11);
  a26=(a26-a25);
  a25=arg[0]? arg[0][15] : 0;
  a17=cos(a25);
  a16=(a26*a17);
  a4=arg[0]? arg[0][14] : 0;
  a2=cos(a4);
  a14=(a20*a2);
  a7=(a7*a11);
  a15=(a15*a3);
  a7=(a7+a15);
  a4=sin(a4);
  a15=(a7*a4);
  a14=(a14-a15);
  a25=sin(a25);
  a15=(a14*a25);
  a16=(a16-a15);
  a15=arg[0]? arg[0][16] : 0;
  a31=cos(a15);
  a32=(a16*a31);
  a26=(a26*a25);
  a14=(a14*a17);
  a26=(a26+a14);
  a15=sin(a15);
  a14=(a26*a15);
  a32=(a32-a14);
  a14=arg[0]? arg[0][17] : 0;
  a33=cos(a14);
  a34=(a32*a33);
  a16=(a16*a15);
  a26=(a26*a31);
  a16=(a16+a26);
  a14=sin(a14);
  a26=(a16*a14);
  a34=(a34-a26);
  if (res[0]!=0) res[0][3]=a34;
  a34=(a12*a3);
  a26=(a5*a11);
  a34=(a34-a26);
  a26=(a34*a17);
  a35=(a13*a2);
  a12=(a12*a11);
  a5=(a5*a3);
  a12=(a12+a5);
  a5=(a12*a4);
  a35=(a35-a5);
  a5=(a35*a25);
  a26=(a26-a5);
  a5=(a26*a31);
  a34=(a34*a25);
  a35=(a35*a17);
  a34=(a34+a35);
  a35=(a34*a15);
  a5=(a5-a35);
  a35=(a5*a33);
  a26=(a26*a15);
  a34=(a34*a31);
  a26=(a26+a34);
  a34=(a26*a14);
  a35=(a35-a34);
  if (res[0]!=0) res[0][4]=a35;
  a35=(a19*a3);
  a34=(a6*a11);
  a35=(a35-a34);
  a34=(a35*a17);
  a36=(a0*a2);
  a19=(a19*a11);
  a6=(a6*a3);
  a19=(a19+a6);
  a6=(a19*a4);
  a36=(a36-a6);
  a6=(a36*a25);
  a34=(a34-a6);
  a6=(a34*a31);
  a35=(a35*a25);
  a36=(a36*a17);
  a35=(a35+a36);
  a36=(a35*a15);
  a6=(a6-a36);
  a36=(a6*a33);
  a34=(a34*a15);
  a35=(a35*a31);
  a34=(a34+a35);
  a35=(a34*a14);
  a36=(a36-a35);
  if (res[0]!=0) res[0][5]=a36;
  a24=(a24*a22);
  a36=(a20*a21);
  a24=(a24+a36);
  a36=arg[0]? arg[0][12] : 0;
  a35=cos(a36);
  a31=(a24*a35);
  a27=(a27*a23);
  a18=(a18*a28);
  a27=(a27+a18);
  a36=sin(a36);
  a18=(a27*a36);
  a31=(a31+a18);
  if (res[0]!=0) res[0][6]=a31;
  a10=(a10*a22);
  a31=(a13*a21);
  a10=(a10+a31);
  a31=(a10*a35);
  a30=(a30*a23);
  a29=(a29*a28);
  a30=(a30+a29);
  a29=(a30*a36);
  a31=(a31+a29);
  if (res[0]!=0) res[0][7]=a31;
  a8=(a8*a22);
  a21=(a0*a21);
  a8=(a8+a21);
  a21=(a8*a35);
  a9=(a9*a23);
  a1=(a1*a28);
  a9=(a9+a1);
  a1=(a9*a36);
  a21=(a21+a1);
  if (res[0]!=0) res[0][8]=a21;
  a7=(a7*a2);
  a20=(a20*a4);
  a7=(a7+a20);
  a20=arg[0]? arg[0][18] : 0;
  a21=cos(a20);
  a1=(a7*a21);
  a32=(a32*a14);
  a16=(a16*a33);
  a32=(a32+a16);
  a20=sin(a20);
  a16=(a32*a20);
  a1=(a1+a16);
  if (res[0]!=0) res[0][9]=a1;
  a12=(a12*a2);
  a13=(a13*a4);
  a12=(a12+a13);
  a13=(a12*a21);
  a5=(a5*a14);
  a26=(a26*a33);
  a5=(a5+a26);
  a26=(a5*a20);
  a13=(a13+a26);
  if (res[0]!=0) res[0][10]=a13;
  a19=(a19*a2);
  a0=(a0*a4);
  a19=(a19+a0);
  a0=(a19*a21);
  a6=(a6*a14);
  a34=(a34*a33);
  a6=(a6+a34);
  a34=(a6*a20);
  a0=(a0+a34);
  if (res[0]!=0) res[0][11]=a0;
  a27=(a27*a35);
  a24=(a24*a36);
  a27=(a27-a24);
  if (res[0]!=0) res[0][12]=a27;
  a30=(a30*a35);
  a10=(a10*a36);
  a30=(a30-a10);
  if (res[0]!=0) res[0][13]=a30;
  a9=(a9*a35);
  a8=(a8*a36);
  a9=(a9-a8);
  if (res[0]!=0) res[0][14]=a9;
  a32=(a32*a21);
  a7=(a7*a20);
  a32=(a32-a7);
  if (res[0]!=0) res[0][15]=a32;
  a5=(a5*a21);
  a12=(a12*a20);
  a5=(a5-a12);
  if (res[0]!=0) res[0][16]=a5;
  a6=(a6*a21);
  a19=(a19*a20);
  a6=(a6-a19);
  if (res[0]!=0) res[0][17]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_rotation(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_rotation_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_rotation_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_rotation_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_rotation_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_rotation_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_rotation_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_rotation_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_rotation_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_rotation_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_rotation_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_rotation_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_rotation_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_rotation_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_rotation_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_rotation_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_rotation_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
