/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {29, 1, 1};
static const casadi_int casadi_s1[3] = {14, 1, 1};

/* kinematics:(i0[29])->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46;
  a00=arg[0]? arg[0][0] : 0;
  a01=3.0300000000000001e-02;
  a02=1.;
  a03=2.;
  a04=arg[0]? arg[0][5] : 0;
  a05=(a03*a04);
  a06=(a05*a04);
  a07=arg[0]? arg[0][6] : 0;
  a08=(a03*a07);
  a09=(a08*a07);
  a10=(a06+a09);
  a10=(a02-a10);
  a11=(a01*a10);
  a12=1.2080000000000000e-01;
  a13=arg[0]? arg[0][4] : 0;
  a14=(a05*a13);
  a15=arg[0]? arg[0][3] : 0;
  a16=(a08*a15);
  a17=(a14-a16);
  a18=(a12*a17);
  a19=4.2990000000000000e-02;
  a20=(a08*a13);
  a05=(a05*a15);
  a21=(a20+a05);
  a22=(a19*a21);
  a18=(a18+a22);
  a11=(a11+a18);
  a11=(a00+a11);
  a18=-4.0000000000000001e-02;
  a22=(a18*a10);
  a23=-3.4000000000000002e-02;
  a24=arg[0]? arg[0][7] : 0;
  a25=cos(a24);
  a26=(a17*a25);
  a27=sin(a24);
  a28=(a21*a27);
  a26=(a26+a28);
  a28=(a23*a26);
  a22=(a22+a28);
  a11=(a11+a22);
  a22=7.4099999999999999e-02;
  a28=(a22*a26);
  a29=-2.2500000000000001e-01;
  a30=arg[0]? arg[0][8] : 0;
  a31=sin(a30);
  a32=(a10*a31);
  a33=(a21*a25);
  a34=(a17*a27);
  a33=(a33-a34);
  a34=cos(a30);
  a35=(a33*a34);
  a32=(a32+a35);
  a35=(a29*a32);
  a28=(a28+a35);
  a11=(a11+a28);
  a28=5.6300000000000003e-02;
  a26=(a28*a26);
  a35=(a10*a34);
  a33=(a33*a31);
  a35=(a35-a33);
  a33=arg[0]? arg[0][9] : 0;
  a36=sin(a33);
  a35=(a35*a36);
  a37=cos(a33);
  a32=(a32*a37);
  a35=(a35+a32);
  a35=(a29*a35);
  a26=(a26+a35);
  a11=(a11+a26);
  if (res[0]!=0) res[0][0]=a11;
  a11=arg[0]? arg[0][1] : 0;
  a14=(a14+a16);
  a16=(a01*a14);
  a26=(a03*a13);
  a35=(a26*a13);
  a09=(a35+a09);
  a09=(a02-a09);
  a32=(a12*a09);
  a08=(a08*a04);
  a26=(a26*a15);
  a38=(a08-a26);
  a39=(a19*a38);
  a32=(a32+a39);
  a16=(a16+a32);
  a16=(a11+a16);
  a32=(a18*a14);
  a39=(a09*a25);
  a40=(a38*a27);
  a39=(a39+a40);
  a40=(a23*a39);
  a32=(a32+a40);
  a16=(a16+a32);
  a32=(a22*a39);
  a40=(a14*a31);
  a41=(a38*a25);
  a42=(a09*a27);
  a41=(a41-a42);
  a42=(a41*a34);
  a40=(a40+a42);
  a42=(a29*a40);
  a32=(a32+a42);
  a16=(a16+a32);
  a39=(a28*a39);
  a32=(a14*a34);
  a41=(a41*a31);
  a32=(a32-a41);
  a32=(a32*a36);
  a40=(a40*a37);
  a32=(a32+a40);
  a32=(a29*a32);
  a39=(a39+a32);
  a16=(a16+a39);
  if (res[0]!=0) res[0][1]=a16;
  a16=arg[0]? arg[0][2] : 0;
  a20=(a20-a05);
  a05=(a01*a20);
  a08=(a08+a26);
  a12=(a12*a08);
  a35=(a35+a06);
  a35=(a02-a35);
  a06=(a19*a35);
  a12=(a12+a06);
  a05=(a05+a12);
  a05=(a16+a05);
  a12=(a18*a20);
  a06=(a08*a25);
  a26=(a35*a27);
  a06=(a06+a26);
  a23=(a23*a06);
  a12=(a12+a23);
  a05=(a05+a12);
  a22=(a22*a06);
  a12=(a20*a31);
  a25=(a35*a25);
  a27=(a08*a27);
  a25=(a25-a27);
  a27=(a25*a34);
  a12=(a12+a27);
  a27=(a29*a12);
  a22=(a22+a27);
  a05=(a05+a22);
  a28=(a28*a06);
  a34=(a20*a34);
  a25=(a25*a31);
  a34=(a34-a25);
  a34=(a34*a36);
  a12=(a12*a37);
  a34=(a34+a12);
  a34=(a29*a34);
  a28=(a28+a34);
  a05=(a05+a28);
  if (res[0]!=0) res[0][2]=a05;
  a05=casadi_sq(a15);
  a28=casadi_sq(a13);
  a05=(a05+a28);
  a28=casadi_sq(a04);
  a05=(a05+a28);
  a28=casadi_sq(a07);
  a05=(a05+a28);
  a28=9.9999999999999992e-25;
  a05=(a05+a28);
  a05=sqrt(a05);
  a15=(a15/a05);
  a28=1.0000000000000000e-08;
  a34=casadi_sq(a24);
  a12=(a28<a34);
  a37=(a28<a34);
  a36=(a37?a34:0);
  a37=(!a37);
  a37=(a37?a28:0);
  a36=(a36+a37);
  a36=sqrt(a36);
  a37=(a36/a03);
  a25=cos(a37);
  a25=(a12?a25:0);
  a12=(!a12);
  a31=8.;
  a06=(a34/a31);
  a06=(a02-a06);
  a22=casadi_sq(a34);
  a27=384.;
  a22=(a22/a27);
  a06=(a06+a22);
  a22=casadi_sq(a34);
  a22=(a34*a22);
  a23=46080.;
  a22=(a22/a23);
  a06=(a06-a22);
  a12=(a12?a06:0);
  a25=(a25+a12);
  a12=(a15*a25);
  a13=(a13/a05);
  a06=(a28<a34);
  a37=sin(a37);
  a37=(a37/a36);
  a37=(a24*a37);
  a37=(a06?a37:0);
  a06=(!a06);
  a36=5.0000000000000000e-01;
  a22=48.;
  a26=(a34/a22);
  a26=(a36-a26);
  a39=casadi_sq(a34);
  a32=3840.;
  a39=(a39/a32);
  a26=(a26+a39);
  a39=casadi_sq(a34);
  a34=(a34*a39);
  a39=645120.;
  a34=(a34/a39);
  a26=(a26-a34);
  a24=(a24*a26);
  a06=(a06?a24:0);
  a37=(a37+a06);
  a06=(a13*a37);
  a12=(a12-a06);
  a06=casadi_sq(a30);
  a24=(a28<a06);
  a26=(a28<a06);
  a34=(a26?a06:0);
  a26=(!a26);
  a26=(a26?a28:0);
  a34=(a34+a26);
  a34=sqrt(a34);
  a26=(a34/a03);
  a40=cos(a26);
  a40=(a24?a40:0);
  a24=(!a24);
  a41=(a06/a31);
  a41=(a02-a41);
  a42=casadi_sq(a06);
  a42=(a42/a27);
  a41=(a41+a42);
  a42=casadi_sq(a06);
  a42=(a06*a42);
  a42=(a42/a23);
  a41=(a41-a42);
  a24=(a24?a41:0);
  a40=(a40+a24);
  a24=(a12*a40);
  a04=(a04/a05);
  a41=(a04*a25);
  a07=(a07/a05);
  a05=(a07*a37);
  a41=(a41+a05);
  a05=(a28<a06);
  a26=sin(a26);
  a26=(a26/a34);
  a26=(a30*a26);
  a26=(a05?a26:0);
  a05=(!a05);
  a34=(a06/a22);
  a34=(a36-a34);
  a42=casadi_sq(a06);
  a42=(a42/a32);
  a34=(a34+a42);
  a42=casadi_sq(a06);
  a06=(a06*a42);
  a06=(a06/a39);
  a34=(a34-a06);
  a30=(a30*a34);
  a05=(a05?a30:0);
  a26=(a26+a05);
  a05=(a41*a26);
  a24=(a24-a05);
  a05=casadi_sq(a33);
  a30=(a28<a05);
  a34=(a28<a05);
  a06=(a34?a05:0);
  a34=(!a34);
  a34=(a34?a28:0);
  a06=(a06+a34);
  a06=sqrt(a06);
  a34=(a06/a03);
  a42=cos(a34);
  a42=(a30?a42:0);
  a30=(!a30);
  a43=(a05/a31);
  a43=(a02-a43);
  a44=casadi_sq(a05);
  a44=(a44/a27);
  a43=(a43+a44);
  a44=casadi_sq(a05);
  a44=(a05*a44);
  a44=(a44/a23);
  a43=(a43-a44);
  a30=(a30?a43:0);
  a42=(a42+a30);
  a30=(a24*a42);
  a12=(a12*a26);
  a41=(a41*a40);
  a12=(a12+a41);
  a41=(a28<a05);
  a34=sin(a34);
  a34=(a34/a06);
  a34=(a33*a34);
  a34=(a41?a34:0);
  a41=(!a41);
  a06=(a05/a22);
  a06=(a36-a06);
  a43=casadi_sq(a05);
  a43=(a43/a32);
  a06=(a06+a43);
  a43=casadi_sq(a05);
  a05=(a05*a43);
  a05=(a05/a39);
  a06=(a06-a05);
  a33=(a33*a06);
  a41=(a41?a33:0);
  a34=(a34+a41);
  a41=(a12*a34);
  a30=(a30-a41);
  a41=arg[0]? arg[0][10] : 0;
  a33=casadi_sq(a41);
  a06=(a28<a33);
  a05=(a28<a33);
  a43=(a05?a33:0);
  a05=(!a05);
  a05=(a05?a28:0);
  a43=(a43+a05);
  a43=sqrt(a43);
  a05=(a43/a03);
  a44=cos(a05);
  a44=(a06?a44:0);
  a06=(!a06);
  a45=(a33/a31);
  a45=(a02-a45);
  a46=casadi_sq(a33);
  a46=(a46/a27);
  a45=(a45+a46);
  a46=casadi_sq(a33);
  a46=(a33*a46);
  a46=(a46/a23);
  a45=(a45-a46);
  a06=(a06?a45:0);
  a44=(a44+a06);
  a06=(a30*a44);
  a24=(a24*a34);
  a12=(a12*a42);
  a24=(a24+a12);
  a12=(a28<a33);
  a05=sin(a05);
  a05=(a05/a43);
  a05=(a41*a05);
  a05=(a12?a05:0);
  a12=(!a12);
  a43=(a33/a22);
  a43=(a36-a43);
  a45=casadi_sq(a33);
  a45=(a45/a32);
  a43=(a43+a45);
  a45=casadi_sq(a33);
  a33=(a33*a45);
  a33=(a33/a39);
  a43=(a43-a33);
  a41=(a41*a43);
  a12=(a12?a41:0);
  a05=(a05+a12);
  a12=(a24*a05);
  a06=(a06-a12);
  if (res[0]!=0) res[0][3]=a06;
  a06=(a15*a37);
  a12=(a13*a25);
  a06=(a06+a12);
  a12=(a06*a40);
  a25=(a07*a25);
  a37=(a04*a37);
  a25=(a25-a37);
  a37=(a25*a26);
  a12=(a12-a37);
  a37=(a12*a42);
  a06=(a06*a26);
  a25=(a25*a40);
  a06=(a06+a25);
  a25=(a06*a34);
  a37=(a37-a25);
  a25=(a37*a44);
  a12=(a12*a34);
  a06=(a06*a42);
  a12=(a12+a06);
  a06=(a12*a05);
  a25=(a25-a06);
  if (res[0]!=0) res[0][4]=a25;
  a30=(a30*a05);
  a24=(a24*a44);
  a30=(a30+a24);
  if (res[0]!=0) res[0][5]=a30;
  a37=(a37*a05);
  a12=(a12*a44);
  a37=(a37+a12);
  if (res[0]!=0) res[0][6]=a37;
  a37=(a01*a10);
  a12=-1.2080000000000000e-01;
  a44=(a12*a17);
  a05=(a19*a21);
  a44=(a44+a05);
  a37=(a37+a44);
  a00=(a00+a37);
  a37=(a18*a10);
  a44=3.4000000000000002e-02;
  a05=arg[0]? arg[0][11] : 0;
  a30=cos(a05);
  a24=(a17*a30);
  a25=sin(a05);
  a06=(a21*a25);
  a24=(a24+a06);
  a06=(a44*a24);
  a37=(a37+a06);
  a00=(a00+a37);
  a37=-7.4099999999999999e-02;
  a06=(a37*a24);
  a42=arg[0]? arg[0][12] : 0;
  a34=sin(a42);
  a40=(a10*a34);
  a21=(a21*a30);
  a17=(a17*a25);
  a21=(a21-a17);
  a17=cos(a42);
  a26=(a21*a17);
  a40=(a40+a26);
  a26=(a29*a40);
  a06=(a06+a26);
  a00=(a00+a06);
  a06=-5.6300000000000003e-02;
  a24=(a06*a24);
  a10=(a10*a17);
  a21=(a21*a34);
  a10=(a10-a21);
  a21=arg[0]? arg[0][13] : 0;
  a26=sin(a21);
  a10=(a10*a26);
  a41=cos(a21);
  a40=(a40*a41);
  a10=(a10+a40);
  a10=(a29*a10);
  a24=(a24+a10);
  a00=(a00+a24);
  if (res[0]!=0) res[0][7]=a00;
  a00=(a01*a14);
  a24=(a12*a09);
  a10=(a19*a38);
  a24=(a24+a10);
  a00=(a00+a24);
  a11=(a11+a00);
  a00=(a18*a14);
  a24=(a09*a30);
  a10=(a38*a25);
  a24=(a24+a10);
  a10=(a44*a24);
  a00=(a00+a10);
  a11=(a11+a00);
  a00=(a37*a24);
  a10=(a14*a34);
  a38=(a38*a30);
  a09=(a09*a25);
  a38=(a38-a09);
  a09=(a38*a17);
  a10=(a10+a09);
  a09=(a29*a10);
  a00=(a00+a09);
  a11=(a11+a00);
  a24=(a06*a24);
  a14=(a14*a17);
  a38=(a38*a34);
  a14=(a14-a38);
  a14=(a14*a26);
  a10=(a10*a41);
  a14=(a14+a10);
  a14=(a29*a14);
  a24=(a24+a14);
  a11=(a11+a24);
  if (res[0]!=0) res[0][8]=a11;
  a01=(a01*a20);
  a12=(a12*a08);
  a19=(a19*a35);
  a12=(a12+a19);
  a01=(a01+a12);
  a16=(a16+a01);
  a18=(a18*a20);
  a01=(a08*a30);
  a12=(a35*a25);
  a01=(a01+a12);
  a44=(a44*a01);
  a18=(a18+a44);
  a16=(a16+a18);
  a37=(a37*a01);
  a18=(a20*a34);
  a35=(a35*a30);
  a08=(a08*a25);
  a35=(a35-a08);
  a08=(a35*a17);
  a18=(a18+a08);
  a08=(a29*a18);
  a37=(a37+a08);
  a16=(a16+a37);
  a06=(a06*a01);
  a20=(a20*a17);
  a35=(a35*a34);
  a20=(a20-a35);
  a20=(a20*a26);
  a18=(a18*a41);
  a20=(a20+a18);
  a29=(a29*a20);
  a06=(a06+a29);
  a16=(a16+a06);
  if (res[0]!=0) res[0][9]=a16;
  a16=casadi_sq(a05);
  a06=(a28<a16);
  a29=(a28<a16);
  a20=(a29?a16:0);
  a29=(!a29);
  a29=(a29?a28:0);
  a20=(a20+a29);
  a20=sqrt(a20);
  a29=(a20/a03);
  a18=cos(a29);
  a18=(a06?a18:0);
  a06=(!a06);
  a41=(a16/a31);
  a41=(a02-a41);
  a26=casadi_sq(a16);
  a26=(a26/a27);
  a41=(a41+a26);
  a26=casadi_sq(a16);
  a26=(a16*a26);
  a26=(a26/a23);
  a41=(a41-a26);
  a06=(a06?a41:0);
  a18=(a18+a06);
  a06=(a15*a18);
  a41=(a28<a16);
  a29=sin(a29);
  a29=(a29/a20);
  a29=(a05*a29);
  a29=(a41?a29:0);
  a41=(!a41);
  a20=(a16/a22);
  a20=(a36-a20);
  a26=casadi_sq(a16);
  a26=(a26/a32);
  a20=(a20+a26);
  a26=casadi_sq(a16);
  a16=(a16*a26);
  a16=(a16/a39);
  a20=(a20-a16);
  a05=(a05*a20);
  a41=(a41?a05:0);
  a29=(a29+a41);
  a41=(a13*a29);
  a06=(a06-a41);
  a41=casadi_sq(a42);
  a05=(a28<a41);
  a20=(a28<a41);
  a16=(a20?a41:0);
  a20=(!a20);
  a20=(a20?a28:0);
  a16=(a16+a20);
  a16=sqrt(a16);
  a20=(a16/a03);
  a26=cos(a20);
  a26=(a05?a26:0);
  a05=(!a05);
  a35=(a41/a31);
  a35=(a02-a35);
  a34=casadi_sq(a41);
  a34=(a34/a27);
  a35=(a35+a34);
  a34=casadi_sq(a41);
  a34=(a41*a34);
  a34=(a34/a23);
  a35=(a35-a34);
  a05=(a05?a35:0);
  a26=(a26+a05);
  a05=(a06*a26);
  a35=(a04*a18);
  a34=(a07*a29);
  a35=(a35+a34);
  a34=(a28<a41);
  a20=sin(a20);
  a20=(a20/a16);
  a20=(a42*a20);
  a20=(a34?a20:0);
  a34=(!a34);
  a16=(a41/a22);
  a16=(a36-a16);
  a17=casadi_sq(a41);
  a17=(a17/a32);
  a16=(a16+a17);
  a17=casadi_sq(a41);
  a41=(a41*a17);
  a41=(a41/a39);
  a16=(a16-a41);
  a42=(a42*a16);
  a34=(a34?a42:0);
  a20=(a20+a34);
  a34=(a35*a20);
  a05=(a05-a34);
  a34=casadi_sq(a21);
  a42=(a28<a34);
  a16=(a28<a34);
  a41=(a16?a34:0);
  a16=(!a16);
  a16=(a16?a28:0);
  a41=(a41+a16);
  a41=sqrt(a41);
  a16=(a41/a03);
  a17=cos(a16);
  a17=(a42?a17:0);
  a42=(!a42);
  a01=(a34/a31);
  a01=(a02-a01);
  a37=casadi_sq(a34);
  a37=(a37/a27);
  a01=(a01+a37);
  a37=casadi_sq(a34);
  a37=(a34*a37);
  a37=(a37/a23);
  a01=(a01-a37);
  a42=(a42?a01:0);
  a17=(a17+a42);
  a42=(a05*a17);
  a06=(a06*a20);
  a35=(a35*a26);
  a06=(a06+a35);
  a35=(a28<a34);
  a16=sin(a16);
  a16=(a16/a41);
  a16=(a21*a16);
  a16=(a35?a16:0);
  a35=(!a35);
  a41=(a34/a22);
  a41=(a36-a41);
  a01=casadi_sq(a34);
  a01=(a01/a32);
  a41=(a41+a01);
  a01=casadi_sq(a34);
  a34=(a34*a01);
  a34=(a34/a39);
  a41=(a41-a34);
  a21=(a21*a41);
  a35=(a35?a21:0);
  a16=(a16+a35);
  a35=(a06*a16);
  a42=(a42-a35);
  a35=arg[0]? arg[0][14] : 0;
  a21=casadi_sq(a35);
  a41=(a28<a21);
  a34=(a28<a21);
  a01=(a34?a21:0);
  a34=(!a34);
  a34=(a34?a28:0);
  a01=(a01+a34);
  a01=sqrt(a01);
  a03=(a01/a03);
  a34=cos(a03);
  a34=(a41?a34:0);
  a41=(!a41);
  a31=(a21/a31);
  a02=(a02-a31);
  a31=casadi_sq(a21);
  a31=(a31/a27);
  a02=(a02+a31);
  a31=casadi_sq(a21);
  a31=(a21*a31);
  a31=(a31/a23);
  a02=(a02-a31);
  a41=(a41?a02:0);
  a34=(a34+a41);
  a41=(a42*a34);
  a05=(a05*a16);
  a06=(a06*a17);
  a05=(a05+a06);
  a28=(a28<a21);
  a03=sin(a03);
  a03=(a03/a01);
  a03=(a35*a03);
  a03=(a28?a03:0);
  a28=(!a28);
  a22=(a21/a22);
  a36=(a36-a22);
  a22=casadi_sq(a21);
  a22=(a22/a32);
  a36=(a36+a22);
  a22=casadi_sq(a21);
  a21=(a21*a22);
  a21=(a21/a39);
  a36=(a36-a21);
  a35=(a35*a36);
  a28=(a28?a35:0);
  a03=(a03+a28);
  a28=(a05*a03);
  a41=(a41-a28);
  if (res[0]!=0) res[0][10]=a41;
  a15=(a15*a29);
  a13=(a13*a18);
  a15=(a15+a13);
  a13=(a15*a26);
  a07=(a07*a18);
  a04=(a04*a29);
  a07=(a07-a04);
  a04=(a07*a20);
  a13=(a13-a04);
  a04=(a13*a17);
  a15=(a15*a20);
  a07=(a07*a26);
  a15=(a15+a07);
  a07=(a15*a16);
  a04=(a04-a07);
  a07=(a04*a34);
  a13=(a13*a16);
  a15=(a15*a17);
  a13=(a13+a15);
  a15=(a13*a03);
  a07=(a07-a15);
  if (res[0]!=0) res[0][11]=a07;
  a42=(a42*a03);
  a05=(a05*a34);
  a42=(a42+a05);
  if (res[0]!=0) res[0][12]=a42;
  a04=(a04*a03);
  a13=(a13*a34);
  a04=(a04+a13);
  if (res[0]!=0) res[0][13]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematics_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int kinematics_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real kinematics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematics_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
